var i18n_resource = {
    home: {
        HOME: 'Home',
        HEADER_TITLE: 'World-leading IoT Artificial Intelligence Platform',
        LEARN_MORE: 'Learn more',
        SCROLL_TO_SATAR: 'Scroll to Explore',
        OUR_FEATURE: 'Features',
        FEATURE_CONTENT: 'BeOP is a one-stop service platform with a collection of IoT and artificial intelligence. Besides innovative vertical solutions, R&B’s been committed to developing infrastructure-level smart services and smart devices for a variety of industries.',
        TECHNOLOGY_IOT: 'IoT',
        AI_EXPERTISE: 'Artificial Intelligence',
        CLOUD_SERVICE: 'Cloud Service',
        ENTERPRISE_APPLICATIONS: 'Enterprise Application',
        TECHNOLOGY_IOT_CONTENT: 'R&B helps customer building flexible and secure data channels and implementing online data access from end terminals (eg. Types of sensors, controllers and etc.). With nodes around the world, no matter where you are, R&B also guarantees that the data can be accessed with low latency access and high quality. Modbus, oBIX and other mainstream types of data access are all supported. Our robust security mechanism with multiple guarantees for data transmission and storage will allow customers to manage data and remotely observe the equipment at any time. ',
        AI_EXPERTISE_CONTENT: 'BeOP has powerful and intelligent data analysis algorithm that provides a wealth of knowledge and responses overall situation in a high speed. In the meantime, it can discover, solve and feedback problems in time to assist user in direction business operations. Combined with experts’ industry knowledge, the data will be processed in such operations like “classification”, “statistics and summarization”, “generating report” and etc. BeOP can mine the data quickly and accurately, refine data meanings, guide the operation of business and achieve the profit.',
        CLOUD_SERVICE_CONTENT: 'Provide a robust security mechanism with multiple guarantees for data transmission and storage. Moreover, it can monitor and process the data at any time. It has features of easy expansion, good extensibility, accessing to any project and supporting global management of enterprise.',
        ENTERPRISE_APPLICATIONS_CONTENT: 'Particularly designed to enterprise level users, assist in completing data accessing, cleansing, processing, displaying and mining, and provide corresponding tool modules in each progress.',
        WHY_RB: 'Why R&B',
        PIONEER_ENTERPRISE: 'Background',
        RICH_EXPERIENCE: 'Customer',
        ADVANCED_TECHNOLOGY: 'Technology Group',
        BUSINESS_DIRECTION: 'Business Intention',
        PIONEER_ENTERPRISE_CONTENT: 'R&B Technology Group which has been committed to maximizing the value of IoT data is one of leading IoT software platform suppliers in China. In the meantime, R&B is backed by reputable venture capitals (eg. SIG, JAFCO Asia).',
        RICH_EXPERIENCE_CONTENT: 'R&B Technology Group is registered in United States and Hong Kong and has been developing business worldwide. With many years of experience in dealing with a variety of practical solutions, R&B’s been cooperated with a lot of domestic and oversea well-known enterprises.',
        ADVANCED_TECHNOLOGY_CONTENT: 'R&B has an excellent team of AI and a number of industry experts to provide a brain for IoT meanwhile R&B’s great technology support team from domestic and oversea are to provide experience of interaction and display with world’s leading technology to our customers. ',
        BUSINESS_DIRECTION_CONTENT: 'Our business intention is transferring from the building to multi-industry networking (eg. Smart buildings, cold chain logistics, intelligent machinery and etc.). To provide a one-stop service platform with data access, process, analysis and display.',
        OUR_CLINETS: 'Business Partners',
        OUR_CLINETS_CONTENT: 'BeOP is backed by reputable venture capitals and has obtained the trust, recognition and support from famous enterprises in a variety of industries. We sincerely look forward to your participation.',
        PRODUCT_FEATURE: 'Features',
        PARTNER: 'Business Partners',
        STATION_MAP: '站点地图',
        OBSERVER: 'Observer',
        FACTORY: 'Factory',
        STRATEGY: 'Algorithm Developer',
        TAG: 'TAG',
        DIAGNOSIS: '诊断',
        DATA_MANAGEMENT: 'Data Management',
        BUILDING_MAINTENANCE: 'Building Maintenance and Operation',
        COLD_CHAIN_LOGISTICS: 'Cold Chain',
        IOT_DATA_MANAGMENT: 'IoT Data Management',
        ENERGY_OPTIMIZATION: 'Energy Optimization',
        PLATFORM_URSERS: 'Platform Users',
        RELATED_DOWNLOAD: '相关下载',
        TECHNICAL_SUPPORT: '技术支持',
        ENTERPRISE_INFO: 'Introduction',
        TEAM_INFO: 'Management Team',
        INVESTMENT_PROGRAM: 'Corporate Investor',
        NEWS: 'News',
        TERMINAL_USER: 'End Users',
        PLATFORM_USER: 'Platform Users',
    },
    product: {
        PRODUCT: 'Production',
        FACTORY: {
            BIG_TITLE: 'Cloud configuration tool, easy to create exclusive data display page',
            SUB_TITLE: 'Is committed to the Internet of things large data presented in the user that it provides a rich and colorful visualization method, allowing you to enjoy the relaxed and pleasant configuration process and all this in the web to achieve',
            STRATEGY_TEXT: '随心所欲的“组态页面”',
            DASHBOARD_TEXT: 'Information highly summarized "Dashboard"',
            REPORT_TEXT: 'Statistical summary of the "report"',
            STRATEGY_TEXT_CONTENT: '用户可以轻松的用Factory来创造属于自己的“组态页面”。线上网页直接编辑和更改信息，无复杂的操作步骤，随心所欲的实现自己所想所要。',
            DASHBOARD_TEXT_CONTENT: '根据数据的科学分析，在这基础上，我们进行了将项目的各个方面进行了汇总、分析、研究，最后将信息进行高度概括，用“Dashboard”的形式表现出来，让用户一目了然的可以掌握自己系统，项目的情况。帮助用户节省了人力时间和精力、从茫茫数据中快速定位于解脱出来。',
            REPORT_TEXT_CONTENT: 'Factory具有统计汇总和“报表”的功能，通过“报表”用户可以轻松掌握任何时间段的数据汇总情况，从而更加了解自己的系统和项目。同时，省去人力大量时间的去总结分析只需要点击一下直接下载，转发与同伴分享、讨论。',
            OPERATION_TITLE: '便捷的云端操作',
            LINK_DATA: '一键接入数据',
            LINK_DATA_TEXT: '只需要轻轻点击一下，每分钟百万级的数据轻而易举的实现，而且只需要拖拽便即可接入系统。做到真正的轻松便捷。',
            CREATE_PAGE: '一键生成页面',
            CREATE_PAGE_TEXT: '我们拥有海量的模板，为用户所需要的内容样式提供强而有力的担保。并且这所有的一切，只需要用户拖拽就能一步用户所需的生成页面。',
            PUBLISH_PROJECT: '一键发布项目',
            PUBLISH_PROJECT_TEXT: '随时随地的让用户接入云端进行系统编辑，并且一键发布后，页面立即上线，让用户省去复杂的部署流程。',
        },
        DATAMANAGEMENT: {
            DATA_MANAGEMENT: 'Data Management',
            BIG_TITLE: '数据接入、处理等一站式解决方案',
            SUB_TITLE: '轻松高效的筛选、清洗、转换、监管数据。',
            LINK_IOT: 'Convenient connection',
            LINK_IOT_CONTENT: 'Data access is no longer a problem, "data terminal" to provide a humane way, through a simple and simple steps, your Internet of things data access system. Support for complex data sources such as Modbus, Obix, Excel, and so on.',
            PRE_DATA: 'Efficient data preprocessing',
            PRE_DATA_SUB_TITLE1: 'Data filtering',
            PRE_DATA_SUB_CONTENT1: 'Most of the raw data is redundant, the filtering function can identify, filter invalid data.',
            PRE_DATA_SUB_TITLE2: 'Data cleansing',
            PRE_DATA_SUB_CONTENT2: 'External environment factors (such as equipment power), will lead to data on the time dimension, data anomalies. Cleaning function, you can intelligently smooth, fill the data.',
            PRE_DATA_SUB_TITLE3: 'Data conversion',
            PRE_DATA_SUB_CONTENT3: 'You can arbitrarily replace the data, you can export any data to Word, Excel, PDF.',
            TAG_TITLE: '用Tag',
            TAG_CONTENT: '增加数据可读性',
            TAG_SUB_TITLE1: 'Easy to understand',
            TAG_SUB_CONTENT1: 'IoT access through the data point will be more complex and redundant, very low readability. But after using Tag, you can let others and others easily grasp all the information related to the data.',
            TAG_SUB_TITLE2: 'Make the machine more intelligent',
            TAG_SUB_CONTENT2: 'Through artificial intelligence, we can more accurate positioning of the required data, can be automated for customers to bring more accurate analysis of the results.',
            TAG_SUB_TITLE3: 'Simplify data usage',
            TAG_SUB_CONTENT3: 'Through the technology, customers can use more auxiliary tools to simplify the cumbersome operation process, greatly reducing the amount of manual work.',
            TAG_SUB_TITLE4: 'Simple Tag',
            TAG_SUB_CONTENT4: 'We will provide advanced technical means, after a simple operation, S can complete the tag tag work.',
            MAINTAIN_TITLE: 'Easy data maintenance',
            MAINTAIN_SUB_TITLE1: 'data analysis',
            MAINTAIN_SUB_TITLE2: 'Data alarm',
            MAINTAIN_SUB_TITLE3: 'Data diagnosis',
            MAINTAIN_SUB_TEXT1: 'Through the chart and other forms of presentation, allowing users to find out the risks in the data, to carry out prevention, to ensure the smooth progress of the project, and master the rules of data, and summed up, allowing users to better grasp the system.',
            MAINTAIN_SUB_TEXT2: 'Through the analysis of data and a certain frontier boundary conditions, intelligent prompt alarm, allowing users to understand and take the first time to reduce unnecessary losses.',
            MAINTAIN_SUB_TEXT3: 'This is a more advanced data management tool, through simple programming to achieve complex and volatile logic, let the machine learn your experience, so you from the boring, complex data liberation.',

        },
        OBSERVER: {
            DATA_MANAGEMENT: 'Observer',
            BIG_TITLE: 'Cloud large data visualization platform',
            SUB_TITLE: 'Observer presents the project in front of you with reports, Dashboards, configuration diagrams, etc., so that you can easily discover, solve problems, view, review, and archive the status of the project.',
            FAST_POS: 'Fast positioning',
            PAGE_STYLE: 'Rich page form',
            PAGE_STYLE_TEXT: 'Reports, Dashboard, system diagrams, etc., to meet a variety of application scenarios.',
            PAGE_CHART: 'Rich data charts.',
            PAGE_CHART_TEXT: 'From different dimensions to show data, guide users from different angles to master the problem.',
            ADVANCED_PRE_DATA: 'Efficient data preprocessing',
            TIME_DEEP: 'Any depth of time dimension.',
            TIME_DEEP_TEXT: 'All the page type, in the display of the current real-time data at the same time, can be a key to switch to any historical time, easy to review the problem, find the law.',
            ANY_PAGE: 'You can customize the page.',
            ANY_PAGE_TEXT: 'All pages can be configured through the Factory, using Algorithm Developer to develop page logic.',
            IO_ECHART: 'Convenient data, chart import and export. ',
            IO_ECHART_TEXT: 'You can arbitrarily replace the data, you can export any data to Word, Excel, PDF.',
            SCALABILITY: 'With high scalability',
            VARIETY_SOLUTIONS: 'Support a variety of solutions',
            VARIETY_SOLUTIONS_TEXT: 'Has a rich solution. In addition to the common solutions, we propose different, diverse solutions based on the different situations in different industries to meet the needs of different customers.',
            ORDER_SYSTEM: 'Talk to work order system',
            ORDER_SYSTEM_TEXT: 'The use of Observer can operate anytime, anywhere work orders, simple and convenient operation of work orders, to solve the work of the problem and can track at any time, so that the problem is more convenient to solve.',
            MOBILE_SUPPORT: 'Mobile support',
            MOBILE_SUPPORT_TEXT: 'We not only in the web to achieve, all the pages can support the mobile side, the real realization of anytime, anywhere, devise in the hand to manage your project.'
        },
        STRATEGY: {
            STRATEGY_TITLE: 'Algorithm Developer',
            BIG_TITLE: 'Cloud Visual Editing Tool',
            SUB_TITLE: 'Algorithm Developer is committed to providing you with professional expertise, so you do not need any programming basis, but also to achieve data analysis data processing, algorithm logic, better grasp your system.',
            DATA_ANALYSIS: 'data analysis',
            DATA_ANALYSIS_TITLE1: 'Cloud generation, debugging, and control algorithms',
            DATA_ANALYSIS_TITLE2: 'Once the algorithm is released, it runs instantly.',
            DATA_ANALYSIS_TITLE3: 'Extensive algorithmic tools.',
            DATA_ANALYSIS_CONTENT3: 'One step positioning to the massive key parameters, easy data preprocessing, a variety of data display form',
            DATA_ANALYSIS_TITLE4: 'Without any programming knowledge.',
            DATA_ANALYSIS_CONTENT4: 'Users no longer have to worry about their own programming and can not achieve the analysis of the data, the entire operation process is simple, easy to operate.',
            BULID_DIAGNOSIS: 'Generate diagnostics',
            BULID_DIAGNOSIS_CONTENT: 'In the diagnosis can be configured algorithm logic, and based on large data to master all the operation of the system. So that the user a full range of the system to view, check and repair, allowing users to more simple and convenient to master the system.',
            BULID_DIAGNOSIS_TITLE1: 'Quickly implement system-level algorithm configuration',
            BULID_DIAGNOSIS_TITLE1_CONTENT: 'In Algorithm Developer, users can easily and easily implement custom algorithms. To achieve the desired effect of the user’s own.',
            BULID_DIAGNOSIS_TITLE2: 'Provide rich algorithm templates',
            BULID_DIAGNOSIS_TITLE2_CONTENT: 'In Algorithm Developer, users can easily and easily implement custom algorithms. To achieve the desired effect of the user’s own.',
            BULID_DIAGNOSIS_TITLE3: 'Customizable algorithms',
            BULID_DIAGNOSIS_TITLE3_CONTENT: 'In Algorithm Developer, users can easily and easily implement custom algorithms. To achieve the desired effect of the user’s own.',

        },
        PRODUCT_TERMINAL: 'End Production',
        PRODUCT_PLATFORM: 'Platform Production',
        ELECTRONIC_WORKFLOW: 'Digital Workflow',
        KPI_MANAGE: 'Smart KPI',
        AUTO_REPORT: 'Automatic Reporting',
        ENERGY_MANAGE: 'Energy Management',
        AUTO_DIAGNOSIS: 'Fault Detection and Diagnostics',
        AUTO_ENERGY_ANALYSIS: 'Data Analysis',
        PLATFORM: {
            TITLE: 'Platform Users',
            CONTENT: 'In the platform users we provide personalized original content, allowing users to enjoy better and more convenient content and services.',
            TITLE_ONE: 'Data Access',
            CONTENT_ONE: 'Data access is no longer a problem on BeOP Platform. “Data terminal” has provided a humane approach that with a few simple steps, platform user can easily complete data access. BeOP support variety of complex data sources, such as Modbus, oBIX, Excel and etc.',
            BOTTOM: 'Learn more',
            TITLE_TWO: 'Data Process',
            CONTENT_TWO: 'An efficient data pre-process scheme is provide for raw data, included data selection, cleansing, conversion and marking.',
            TITLE_THREE: 'Algorithm Configuration',
            CONTENT_THREE: 'It is dedicated to customer’s professional skills of implementing data analysis, processing, algorithm logic and better control of customer’s system without any programming skills.',
            TITLE_FOUR: 'Data Visualization',
            CONTENT_FOUR: 'Data visualization is dedicated to presenting IoT and mass data in front of user, providing a variety of visualizing methods, and allowing customer enjoy relaxing progress of configuration. And it’s all implemented on Website.',
        },
        TERMINAL: {
            TITLE: 'End Users',
            CONTENT: 'In the platform users we provide personalized original content, allowing users to enjoy better and more convenient content and services',
            ELE_TITLE:'Digital Workflow',
            ELE_CONTENT:'Automatically drive actions from raw data. Track and visualize entire process of detected faults by monitoring processing, status, and efficiency.',
            KPI_TITLE:'Smart KPI',
            KPI_CONTENT:'Customized operation KPI management visualizes critical operation parameters and automatically diagnoses KPIs that fails to achieve. Periodic report are automatically generated and delivered to users.',
            AUTO_REPORT:'Automatic Reporting',
            AUTO_REPORT_TEXT:'Reports can be customized according to user’s requirement, generated automatically and downloaded by a variety of formats, which greatly reduce hours of manual forming.',
            ENERGY_TITLE:'Energy Management',
            ENERGY_TEXT:'A complete set of online energy service on BeOP™ Platform, including but not limited to, energy audit, benchmarking and diagnostics, measurement & verification, ROI analysis, and automatic reporting, etc., tremendously improves working efficiency of energy service business.',
            AUTO_DIA_TITLE:'Fault Detection and Diagnostics',
            AUTO_DIA_TEXT:'Based on historical and real-time data, BeOP™ detects faults or incorrect operation of equipment and systems and diagnoses them for further actions.',
            AUTO_ANALY_TITLE:'Data Analysis',
            AUTO_ANALY_TEXT:'Based on powerful industry algorithm library, analysis of abnormal energy efficiency and report can be automatically generated, which helps single customer to analyze in details and group customer to compare multiple projects.'
        }        
    },
    Solution: {
        SOLUTION: 'Solution',
        TITLE: 'R&B based on the experience of major enterprises, a deep understanding of the real needs of enterprises, focusing on intelligent energy management system, to provide you with construction and operation, cold chain logistics, IOT data management, energy optimization, platform users and other services',
        TITLE_ONE: 'Building Maintenance and Operation',
        CONTENT_ONE: 'Comprehensively monitor equipment and facilities, use KPI to evaluate operation and maintenance, analyze the advantages and disadvantages of solution, self-learn from history of operation and maintenance behavior so as to provide optimization advice.',
        BTN: 'Learn more →',
        TITLE_TWO: 'Cold Chain',
        CONTENT_TWO: 'Provide cold chain monitoring， vehicle tracking and temperature changes during transportation and storage. According to staff schedule, record the working path and status.',
        TITLE_THREE: 'IoT Data Management',
        CONTENT_THREE: 'Convenient data access, fast batch data process, use unified language to mark data;Application can use whole equipment to identify referencing data.',
        TITLE_FOUR: 'Energy Optimization',
        CONTENT_FOUR: 'The integration of management is to dig the potential of energy saving and provide professional operation advice. Energy management can achieve real-time monitoring, historical query, fault detection, benchmarking and report.',
        TITLE_FIVE: 'Platform Users',
        CONTENT_FIVE: 'Data Access – Data Process – Algorithm Configuration – Data Visualization .Provide a complete tool and a large number of templates, let platform user quickly finish data visualization from field data accessing to final web page making.'
    },
    Support: {
        SUPPORT: 'Support',
        DOWNLOAD: 'Download',
        BTN: 'Download',
        BEOP: 'BeOP APP',
        APP: 'Smart Device',
        FACTORY: 'Factory Desktop Edition',
        CORE: 'Core',
        DOWNLOADTIP:'Download the android version. For ios version, please click the link.'
    },
    About: {
        ABOUT_US: 'About Us',
        COMPANY_INFO: 'R&B Technology Group is a leading industry pioneer on seamlessly integrating artificial intelligence & vertical industrial applications, e.g., building energy management. Besides innovative vertical solutions, R&B’s been committed to developing and providing infrastructure-level smart services and smart devices to a variety of industries. Purely data-driven, R&B’s proprietary technology tremendously increases efficiency by achieving automatic conversion from raw data to meaningful business-related conclusions by nature language.\
        R&B Technology Co., Ltd. is registered in US and Hong Kong, and headquartered in Shanghai, China. Backed by reputable venture capitals it has 90+ employees and been developing business worldwide.\
        ',
        TEAM_MANAGEMENT: 'Management Team',
        TEAM_TITLE: 'Our management team comes from various fields, has excellent academic background, and deep, experienced and experienced years of experience. And cordial, united team atmosphere. Respect every individual, flat management.',
        MEMBER_NAME_1: 'Charles Wong',
        MEMBER_WORK_1: 'Founder and CEO',
        MEMBER_WORKINFO_1: 'Founder and CEO，responsible for fund procurement and market development, having sufficient business network, with abundant management experience, graduated from British Columbia University',
        MEMBER_NAME_2: 'Glenn Wu',
        MEMBER_WORK_2: 'Founder, COO & CTO',
        MEMBER_WORKINFO_2: 'Founder, COO & CTO, with over 15 years’ experience in building diagnostics, responsible for product development and strategy, graduated from Carnegie Mellon University with a Master degree majored in building performance and diagnostics',
        MEMBER_NAME_3: 'Golding Gu',
        MEMBER_WORK_3: 'Product Director',
        MEMBER_WORKINFO_3: 'PhD from Tsinghua University, with over 10 years research and development experience in HVAC and building management, making outstanding achievements in academic field',
        MEMBER_NAME_4: 'Tony Nie',
        MEMBER_WORK_4: 'Development Director',
        MEMBER_WORKINFO_4: 'Graduated from Shanghai Jiaotong University, worked in world’s top 500 enterprises such as Microsoft and Morgan Stanley, obtained a patent for Microsoft, over 10 years’ experience in IT R&D and management.',
        MEMBER_NAME_5: 'Fei Wang',
        MEMBER_WORK_5: 'Engineering Director',
        MEMBER_WORKINFO_5: 'Over 15 years plentiful experience in project execution of HVAC and building management',
        MEMBER_NAME_6: 'Wayne Ma',
        MEMBER_WORK_6: 'Chief Scientist',
        MEMBER_WORKINFO_6: 'Graduated from Carnegie Mellon University in electronic and computer engineering, worked in Broadcom Inc. and Xpliant Inc., with over 8 years experience in VLSI',
        COO_NAME: '吴',
        COO_WORK: '创办人、COO、CTO',
        COO_WORK_INFO: '',
        CST_NAME: '马伟楠',
        CST_WORK: '首席科学家',
        CST_WORK_INFO: '',
        INSTITUT_INVERST: 'Corporate Investor',
        SIG_CONTAINER: 'SIG\'s China venture capital and private equity activities are operated through SIG Asia Investments, LLLP (SAI) and its wholly foreign owned enterprise (WFOE) based in Shanghai with a branch office in Beijing . The SIG China team seeks to commit the firm’s capital to venture capital and private equity investments in China.',
        JAFCO_CONTAINER: 'JAFCO Asia is the venture capital partner of choice for both technology related companies and investors. As one of the pioneers and leading company in this domain, the objectives of JAFCO Asia are clear: to add value through our experience, professionalism and business development, to build successful businesses together with our entrepreneurs and to obtain excellent return on investment for our investors. As a global venture capital organization, we tap our expertise from our three JAFCO centers - Asia, Japan and the United States - holistically aligned to helping our partners achieve the success they desire.',
        LEARN_MORE: 'Learn more',
        OUR_NEWS: 'News',
        RECENT_NEWS: 'Recent News',
        SIX_YEAR_NEW: '2016',
        FIVE_YEAR_NEW: '2015',
        FOUR_YEAR_NEW: '2014',
        THREE_YEAR_NEW: '2013',
        CHECK_MORE: 'Learn more',
        D201607_DATE: 'July, 2016',
        D201606_DATE: 'June, 2016',
        D201604_DATE: 'April, 2016',
        D201603_DATE: 'March, 2016',
        D201601_DATE: 'January, 2016',
        D201512_DATE: 'December, 2015',
        D201501_DATE: 'January, 2015',
        D201404_DATE: 'April, 2014',
        D201309_DATE: 'September, 2013',
        D201607_NEW: 'Sign strategic cooperation framework agreement with CBRE(world’s largest commercial real estate services and investment firm)',
        D201606_NEW: 'Participate in 2016 Realcomm Conference',
        D201604_NEW: 'Release iOS version of Smart Thermostat Network APP</br>Release IoT solution for high-end commercial buildings',
        D201603_NEW: 'Publish configuration and debugging tools for developers and allied partners',
        D201601_NEW: 'Release cloud services for sophisticated machinery & equipment and IoT',
        D201512_NEW: 'Release version 2.0 of BeOP Platform</br>Release both iOS and Android version of BeOP Platform APP、Complete Series B funding',
        D201501_NEW: 'Release version 1.0 of BeOP Platform</br>Provide smart services for engineering and building energy facilities',
        D201404_NEW: 'Complete Series A funding',
        D201309_NEW: 'Release version 1.0 of Core (field data collection tool) and Observer (desktop edition)',
        OUR_MISSION: 'Our mission',
        ABOUT_TOP_TEXT: 'We uphold the concept of integrity, to provide real energy efficiency optimization for the responsibility, dedication to our customers for innovative products and services'
    },
    Contact: {
        CONTACT: 'Contact',
        CONTACTCONTENT:'R & B invites you to enter the artificial intelligence platform ',
        CONTACTCONTENT_ONE:'to meet the bright future!',
        ADDRESSTITILE: 'Contact address',
        TITLE_ONE: '75 Executive Drive, Suite 106, Aurora, IL 60504',
        COMPANY_ONE: 'Company Name: rnbtech co., Ltd',
        DETAIL: 'Contact',
        CODE: 'Zip Code',
        PHONE: 'Phone',
        TITLE_TWO: 'Room 1103, Building 1, Sandhill Plaza,No.2290 Zuchongzhi Road, Pudong New Area,Shanghai, China.',
        COMPANY_TWO: 'Company Name: rnbtech co., Ltd',
        TITLE_THREE: '19/F Citicorp Centre 18 Whitfield Road,Hong Kong',
        COMPANY_THREE: 'Company Name: rnbtech co., Ltd',
        EMAIL:'Email',
        SHANGHAI:'Shanghai',
        HONGKONG:'Hongkong',
        AMERICA:'America'
    },
    ColdChain: {
        SUBTITLE: 'Provide cold chain monitoring， vehicle tracking and temperature changes during transportation and storage. According to staff schedule, record the working path and status.',
        ITEM_TITLE_ONE: 'Precise Positioning of Cold Chain Vehicles',
        ITEM_TITLE_DESC_ONE: 'Web reflects real-time monitoring on location and routes of vehicles, detecting temperature changes in vehicles and tracking vehicle history playback.',
        ITEM_TITLE_TWO: 'Unified Control of Cold Storage',
        ITEM_TITLE_DESC_TWO: 'Can inquire all storage location of the project and real-time monitor the temperature and equipment operation.',
        ITEM_TITLE_THREE: 'Simplified and Practical Cold Chain Operation Alerts:',
        ITEM_TITLE_DESC_THREE: 'Customized temperature limit and real-time alert.'
    },
    Iot: {
        SUBTITLE: 'Convenient data access, fast batch data process, use unified language to mark data;Application can use whole equipment to identify referencing data.',
        SEC_TITLE: 'Function and Advantage',
        ITEM_TITLE_ONE: 'Direct data input on the spot and support a variety of protocols',
        ITEM_TITLE_DESC_ONE: 'Data terminal module of BeOP support data input of different protocols, and user can quickly access data online.',
        ITEM_TITLE_TWO: 'Fast Data Collection and Labeling',
        ITEM_TITLE_DESC_TWO: 'Use unified language to mark the points which are marked by different methods.',
        ITEM_TITLE_THREE: 'Accurate Iot Diagnostics',
        ITEM_TITLE_DESC_THREE: 'Combine industry knowledge and intelligent learning, mine the data and propose appropriate operational recommendation.',
        BOTTOM_TITLE: 'Operating Steps',
        BOTTOM_CONTENT_ONE: 'Data Access',
        BOTTOM_CONTENT_TWO: 'Preliminary Data Handling',
        BOTTOM_CONTENT_THREE: 'Data Marking',
        BOTTOM_CONTENT_FOUR: 'Data Cleansing and Calculating',
        BOTTOM_CONTENT_FIVE: 'Diagnostics based on Specific Industry',
        BOTTOM_CONTENT_SIX: 'Establish Interface'
    },
    Energy: {
        SUBTITLE: 'The integration of management is to dig the potential of energy saving and provide professional operation advice. Energy management can achieve real-time monitoring, historical query, fault detection, benchmarking and report.',
        ITEM_TITLE_ONE: 'Clear Display of Energy Consumption',
        ITEM_TITLE_DESC_ONE: 'Meter energy consumption categorized by equipment and operating time, and observes the main influence period and factor.',
        ITEM_TITLE_TWO: 'Flexible and Customized Metering',
        ITEM_TITLE_DESC_TWO: 'In order to meet purposes from various buildings, BeOP support customized metering. According to the metering data from different nodes, BeOP can merge or disassemble it to satisfy business demand.',
        ITEM_TITLE_THREE: 'Similar Project Benchmarking',
        ITEM_TITLE_DESC_THREE: 'Support comparison of projects with similar operating behavior and energy consumption, learn and correct from each other.',
        RIGHT_TITLE: 'Key Features',
        ITEM_TITLE_FOUR: 'Modular Service',
        ITEM_TITLE_DESC_FOUR: 'Display data by modules, applicable to different projects, quickly build and display',
        ITEM_TITLE_FIVE: 'Substantial Project Base',
        ITEM_TITLE_DESC_FIVE: 'Yearly accumulation of projects has raised the possibility of benchmarking in energy consumption from various projects, and support operation logic from a large amount of data.',
    },
    Platform: {
        SUBTITLE: 'Data Access – Data Process – Algorithm Configuration – Data Visualization Provide a complete tool and a large number of templates, let platform user quickly finish data visualization from field data accessing to final web page making.',
        ITEM_TITLE_ONE: 'Simple Project Creation',
        ITEM_TITLE_DESC_ONE: 'From project creation to data access, guide platform user to complete the whole process by their own based on workflow.',
        ITEM_TITLE_TWO: 'Applicable to Multiple Industries',
        ITEM_TITLE_DESC_TWO: 'General tools of data sorting, cleansing, identification, calculating and displaying enable BeOP serve in multiple industries and provide a wide range of possibilities for platform users.',
        ITEM_TITLE_THREE: 'Display by Components',
        ITEM_TITLE_DESC_THREE: 'Data display images, tables and letters by each component. Platform users can quickly generate website by different components with a unified style.',
        RIGHT_TITLE: 'Key Features',
        ITEM_TITLE_FOUR: 'Less Skill Requirement from Staff',
        ITEM_TITLE_DESC_FOUR: ' Built-in code function, display the code in graphical and modules, and no more requirements of Internet development skills from staff.',
        ITEM_TITLE_FIVE: 'Time Saving',
        ITEM_TITLE_DESC_FIVE: ' Components and detailed guidance, improve the efficiency of project.',
        BOTTOM_TITLE: 'Process',
        BOTTOM_CONTENT_ONE: 'Data Access',
        BOTTOM_CONTENT_TWO: 'Data Process',
        BOTTOM_CONTENT_THREE: 'Algorithm Configuration',
        BOTTOM_CONTENT_FOUR: 'Data Visualization'
    },
    BuildingMaintenance: {
        SUBTITLE: 'A comprehensive real-time monitoring of construction equipment and facilities, with KPI on the operation and maintenance assessment, analysis of the merits of the operation and maintenance program, according to the history of self-learning behavior, and thus give optimization recommendations',
        ITEM_TITLE_ONE: 'Monitoring',
        ITEM_TITLE_TWO: 'Report',
        ITEM_TITLE_THREE: 'KPI',
        ITEM_TITLE_FOUR: 'Energy Management and Expense Report',
        ITEM_TITLE_FIVE: 'Diagnostics',
        ITEM_TITLE_SIX: 'Simplified Daily Meter Reading',
        ITEM_TITLE_SEVEN: 'Simplified Asset Management',
        ITEM_TITLE_EIGHT: 'Simplified Patrol System',
        ITEM_TITLE_NINE: 'Work Order',
    },
    News: {
        ALL_NEWS: 'All News',
        YEAR_ONE: '2016',
        YEAR_ONE_TITLE_ONE: 'July, 2016',
        YEAR_ONE_TITLE_TWO: 'June, 2016',
        YEAR_ONE_TITLE_THREE: 'April, 2016',
        YEAR_ONE_TITLE_FOUR: 'March, 2016',
        YEAR_ONE_TITLE_FIVE: 'January, 2016',
        YEAR_ONE_DESC_ONE: 'Sign strategic cooperation framework agreement with CBRE</br>(world’s largest commercial real estate services and investment firm)',
        YEAR_ONE_DESC_TWO: 'Participate in 2016 Realcomm Conference',
        YEAR_ONE_DESC_THREE: 'Release iOS version of Smart Thermostat Network APP</br>Release IoT solution for high-end commercial buildings',
        YEAR_ONE_DESC_FOUR: 'Publish configuration and debugging tools for developers and allied partners',
        YEAR_ONE_DESC_FIVE: 'Release cloud services for sophisticated machinery & equipment and IoT',
        YEAR_TWO: '2015',
        YEAR_TWO_TITLE_ONE: 'December, 2015',
        YEAR_TWO_TITLE_TWO: 'January, 2015',
        YEAR_TWO_DESC_ONE: 'Release version 2.0 of BeOP Platform</br>Release both iOS and Android version of BeOP Platform APP</br>Complete Series B funding',
        YEAR_TWO_DESC_TWO:'Release version 1.0 of BeOP Platform</br>Provide smart services for engineering and building energy facilities',
        YEAR_THREE: '2014',
        YEAR_THREE_TITLE_ONE: 'April, 2014',
        YEAR_THREE_DESC_ONE: 'R&Complete Series A funding',
        YEAR_FOUR: '2013',
        YEAR_FOUR_TITLE_ONE: 'September, 2013',
        YEAR_FOUR_DESC_ONE: 'Release version 1.0 of Core (field data collection tool) and Observer (desktop edition)',
    }
};