var i18n_resource = {
    error: {
        token: {
            0: 'Valid lisence',
            1: 'Login error',
            2: 'Invalid lisence',
            3: 'Expired lisence',
            4: 'Invalid account'
        },
        relogin: 'Please relogin',
        noPermission: 'You don\'t have permission to access'
    },
    admin: {
        navTitle: {
            ROOM: 'Room',
            CONTROLLERS: 'List',
            HISTORY_CURVE: 'Curve',
            PATTERN: 'Mode',
            SETPWD: 'Set Password',
            SHOW_SENSOR: 'Show Sensor',
            HIDE_SENSOR: 'Hide Sensor',
            INFO: 'Message',
            SCHEDULE: 'Schedule',
            LAST_VERSION: 'Last version  '
        },
        index: {
            INTER_NAME: 'User name',
            INTEE_PASSWORD: 'Password',
            REGISTER: 'Sign up',
            LOGIN: 'Login',
            LANGUAGE: 'Language',
            FORGET_PASS: 'Forgot your password?',
            NAME_ERROR: 'Invalid account or password',
            LOGIN_ERROR_INFO: 'Failed to Log in, no permission on any project!',
            LOGIN_ERROR: 'Failed to Log in!',
            CONTRY_TITTLE: 'Country',
            CONTRY: 'China',
            YOUR_NUM: 'Your phone number',
            NEXT: 'Next',
            AGREE: 'I have read and agree',
            TOU: 'Terms of Use and Privacy Policy',
            ENTER: 'Enter',
            VERI_CODE: 'verification code received SMS:',
            SMS_CODE: 'Verification code',
            SET_PASS: 'Please set a password:',
            MAN: 'Male',
            WOMEN: 'Female',
            PASS_INFO: 'Password consists of 6-20 characters',
            OVER: 'Complete',
            REPEAT_SEND: 'Resend',
            NUM_INFO: 'Please fill in your phone number! ',
            NUM_ERROR_INFO: 'Phone number is 11 digits! please check! ',
            NUM_REPEAT_INTER: 'Your phone number is incorrect, please check! ',
            NUM_ELEVEN: 'Please fill in completely! ',
            PASS_INFO: 'Please set at least six passwords! ',
            USER_INFO: 'User name or password is incorrect! ',
            USER_PASSWORD_INFO: 'User password is incorrect!',
            ROOM_PASSWORD_INFO: 'Room password is incorrect!',
            VERI_INFO: 'Verification code is incorrect, please re-enter! ',
            REGISTER_INFO: 'Phone number is already registered! ',
            CHECH_INFO: 'The network is not connected, please check',
            CHECH_INFO_ONE: 'Network has broken down, some functions may be influenced.',
            CHECH_INFO_TWO: 'Network has been connected.',
            MECINE_INFO: 'Server busy',
            SERVICE_ONE: '1, confirmed the terms of service and acceptance of the content and services of this website and APP\'s owned by the present owners. ',
            SERVICE_ONE_ONE: 'user before accepting this service, please be sure to carefully read these terms. ',
            SERVICE_ONE_TWO: 'user service, or by completing the registration process, the user indicates acceptance of all the Terms of Service. ',
            SERVICE_TWO: '2, the user agrees:',
            SERVICE_TWO_ONE: '(1) to provide timely, accurate and detailed personal information. ',
            SERVICE_TWO_TWO: '(2) update registration information, with timely, detailed and accurate requirements. ',
            SERVICE_TWO_THREE: 'If the information provided is not accurate, this site has the right to end the service. ',
            SERVICE_TWO_FOUR: 'This website and APP will not disclose the name, address, email address, account number and phone number information (please read the Privacy Policy). ',
            SERVICE_TWO_SIX: 'any user behavior in this site and APP must follow:',
            SERVICE_TWO_SEVEN: '(1)must comply with the relevant Chinese laws and regulations (1) to transfer data. ',
            SERVICE_TWO_EIGHT: '(2) the use of information and services for illegal purposes and unethical behavior. ',
            SERVICE_TWO_NIEN: '(3) does not interfere with or confusion network services. ',
            SERVICE_TWO_TEN: '(4) comply with all network services agreement, regulations, procedures and practices. Conduct user\'s Internet regulations, policies, procedures and practices as a basis. ',
            SERVICE_THREE: '3, to modify the terms of service',
            SERVICE_THREE_ONE: 'This site APP to amend the terms and, if necessary, will be announced in the page. ',
            SERVICE_THREE_TWO: 'If you do not accept the changes to the content, the user can take the initiative to cancel your membership. If you do not cancel your membership, as changes in the terms of service. ',
            SERVICE_FOUR: '4, user accounts, passwords and security',
            SERVICE_FOUR_ONE: 'Once you have successfully registered as a member, you will have a user name and password. ',
            SERVICE_FOUR_TWO: 'Secure User username and password will bear full responsibility. In addition, each user must be on all the activities and events that take full responsibility for their user name. You can always change your password. ',
            SERVICE_FOUR_THREE: 'If users find any illegal use of user account or the existence of security vulnerabilities, please immediately notice the Company. ',
            SERVICE_FIVE: '5, refused to provide guarantees',
            SERVICE_FIVE_ONE: 'User expressly agree to use the company\'s services, at the risk of individual users. ',
            SERVICE_FIVE_TWO: 'This website and APP security services will meet user requirements, nor the security services will not be interrupted, the timeliness of service, security, mistakes do not occur as collateral security. ',
            SERVICE_FIVE_THREE: 'Users understand and accept: usefulness depends on the user reliability of any information obtained through the Service in its sole discretion, the user assumes all risks and liabilities. ',
            SERVICE_SIX: '6, limited liability',
            SERVICE_SIX_ONE: 'APP on this website and the use of any service initiated direct, indirect, incidental and consequential damages irresponsible. ',
            SERVICE_SIX_TWO: 'damage may come from (including but not limited to): improper use of the Services, or transmitted information does not meet the provisions. ',
            SERVICE_SEVEN: '7, the user information storage and restrictions',
            SERVICE_SEVEN_ONE: 'this website and APP does not release user information delete or save responsible for the failure, the company has to determine whether the user\'s compliance with the terms of service requirements and reserves the right spirit. If a user violates the terms of service, we have the right to interrupt its service delivery. ',
            SERVICE_EIGHT: '8, the end of the service',
            SERVICE_EIGHT_ONE: 'This website and APP can be interrupted at any time one or more services based on the actual situation, without any personal or third party or inform. ',
            SERVICE_EIGHT_TWO: 'At the same time the user to any terms of service or to subsequent modify the terms of objections, or dissatisfied with their service, users can exercise the following rights:',
            SERVICE_EIGHT_THREE: '(1) no longer use the company\'s services. ',
            SERVICE_EIGHT_FOUR: '(2) notify the company to stop the users of services. ',
            SERVICE_NINE: '9, proprietary information content',
            SERVICE_NINE_ONE: 'The company\'s information including: text, software, sound, photographs, video, graphics; and other information, all content is protected by copyright, trademarks, labels and other property ownership laws. ',
            SERVICE_NINE_TWO: 'user can only be under the authority of the content, but not unauthorized copying, recycled content, or create content-related derivative products of. ',
            SERVICE_TEN: '10, Privacy Policy ',
            SERVICE_TEN_ONE: 'This website and APP will strictly conservative, user privacy, commitment without your consent will not disclose any of your personal information. ',
            SERVICE_TEN_TWO: 'However, in the following cases, we will not be able to provide you with information about you and disclose the aforementioned guarantee. These circumstances include, but are not limited to: ',
            SERVICE_TEN_THREE: '* For your successful completion of the transaction, we have to put some of your information, such as your name, telephone number, e-mail and other services provided to related parties such as logistics, in order to get in touch with you in them, Provide services. ',
            SERVICE_TEN_FOUR: '* When you conduct this site in violation of terms of service, or may damage the rights of others or cause others to suffer damages, as long as we believe that disclosure of your personal information in order to identify, contact or bring legal action necessary action time. ',
            SERVICE_TEN_FIVE: '* under the laws and regulations or to disclose personal information disclosure. ',
            SERVICE_TEN_SIX: '* When a judicial or other competent authorities to perform official duties, require certain personal information, we must give the necessary cooperation. ',
            SERVICE_ELEVEN: '11, the applicable law ',
            SERVICE_ELEVEN_ONE: 'The foregoing shall apply the law of the People\'s Republic of China, all disputes will resort to this site location People\'s Court. ',
            SERVICE_ELEVEN_TWO: 'In the event of the Terms of Service and the People\'s Republic of China contrary to law, then these provisions will be required by law to re-interpret, while other provisions are still maintain binding. '
        },
        indexMap: {
            EQUIPMENT: 'Equipment',
            HUMIDITY: 'Humidity',
            PAIR: 'Match',
            HISTORY: 'History',
            WIND_SPEED_SETTIG: 'Fan speed',
            CORRECT_ROOM_INFO: 'Please match the room first',
            LAST_REFRESH: 'Updated: ',
            OPEN_CLOSE_INFO: 'Please switch to manual mode',
            SET_SPEED_INFO: 'Please switch to manual mode',
            CURRENT_MODE: 'Current mode: Efficiency',
            SET_TEMPERATURE: 'Comfirm?',
            SET_WIND_SPEED: 'Comfirm?',
            HANDOL_INFO: 'Failed to set',
            LADY_FIRST: 'Current mode is Lady first, only ladies can set the temperature',
            SEX_INFO_REQUIRE: 'Current mode is Lady first, please go to the personal center to improve personal information'
        },
        roomPage: {
            EDIT: 'Edit',
            ADD: 'Add',
            SWEEP: 'QR code',
            INVITE_CODE: 'Invitation code',
            MY_QR_CODE: 'My QR code',
            GENERATE_QR_CODE: 'generate QR code',
            MAP: 'Map',
            LIST: 'List',
            INTER_INVITE_CODE: 'Please input QR code',
            BACK: 'Back',
            SURE: 'OK',
            CANCEL: 'Cancel',
            NO_ROOM_TIP:'No room matched，please press add to match.',
            SELECT_ROOM: 'Please choose a room',
            CORRECT_ASSOCIATION: 'Matching completed',
            ASSOCIATED_FAILURE: 'Failed to match, you can try again',
            INVALID: 'Invalid',
            DELETE: 'Delete',
            INVITE_CODE: 'Invite code',
            COPY_INVITE_CODE: 'Copy Invite code'
        },
        setUp: {
            SCHEDULE_TABLE: 'Schedule',
            INFOS: 'Message',
            LOGOUT: 'Logout',
            LANGUAGE: 'Language',
            CHINESE: 'English',
            INSTALL: 'Install',
            CONFIG: 'Option',
            VERSION: 'Version',
            PERSONAL_CENTER: 'Personal center',
            YOUR_PASSWORD: 'Your account password',
            SET_ROOM_PASSWORD: 'Set room management password',
            ROOM_PASSWORD: 'Room management password'
        },
        controllers: {
            NAME: 'Name',
            TEMPERATURE: 'Temperature',
            WIND_SPEED: 'Fan speed',
            OPEN_CLOSE: 'OnOff',
            SEANSONAL_PATTERN: 'Season mode',
            VALVE: 'Valve position',
            AUTO: 'Auto',
            CLOSE: 'Close',
            OPEN: 'Open',
            REFRIGERATION: 'Cooling',
            HEATING: 'Heating',
            HANDLE: 'Manual',
            SELECT_ONE: 'Please choose one item',
            SET_WIND_SPEED: '-Fan speed(digital)',
            SELECTED_ALL: 'All'
        },
        pattern: {
            MS_PRIORITY_MODE: 'Lady First Mode',
            ENERGY_SAVING_MODE: 'Efficiency Mode',
            COMFORTABLE_MODE: 'Comfort Mode',
            MANUAL_MODE: 'Manual Mode',
            SEASON_MODE_COOLING: 'Season Mode:Cooling',
            SEASON_MODE_HEATING: 'Season Mode:Heating',
            CONFIRM_SWITCH: 'Are you sure to switch to ',
            SWITCHED: 'Switched to ',
            SWITCHED_ERROR: 'Failed to switch mode'
        },
        schedule: {
            MS_FIRST: 'Lady First',
            ENERGY_CONSERVE: 'Efficiency',
            COMFORTABLE: 'Comfort',
            HANDLE: 'Manual',
            SELECT_TIME: 'Please set time',
            SAVE: 'Save',
            REPEAT: 'Repeat',
            SEVEN: 'S',
            ONE: 'M',
            TWO: 'T',
            THREE: 'W',
            FOUR: 'T',
            FIVE: 'F',
            SIX: 'S',
            SUNDAY: 'Sunday',
            MONDAY: 'Monday',
            TUESDAY: 'Tuesday',
            WEDNESDAY: 'Wednesday',
            THURSDAY: 'Thursday',
            FRIDAY: 'Friday',
            SATURDAY: 'Saturday',
            EXIST_SCHEDULE: 'There are schedule for the same time.'
        },
        personalCenter: {
            AVATAR: 'Avatar',
            SEX: 'Gender',
            PHONE_NUM: 'Tel',
            EMAIL: 'Email',
            EDIT: 'Edit',
            FINISH: 'Complete',
            EMAIL_FORMAT_ERROR: 'Mail address is not formatted correctly',
            EMAIL_SEND_SUCCESS: 'Mail sent successfully, please check your mailbox',
            EMAIL_SEND_FAIL: 'Failed to send a message, please try again',
            EMAIL_CHANGED_SUCCESS: 'Email changed successfully',
            SEX_CHANGED_SUCCESS: 'Gender changed successfully',
            SEX_CHANGED_FAILED: 'Gender changed fails'
        },
        avatar: {
            MY_AVATAR: 'Avatar',
            TAKE_PHOTO:'Take photo',
            FROM_ALBUM:'Select from album',
            SAVE_PHOTO: 'Save photo',
            CANCEL: 'Cancel',
            FAIL_CHANGE: 'Fail to change avatar'
        },
        phoneNumber:{
            TITLE: 'Bind phone',
            INPUT_VALID_PHONE_NUM: 'The phone number is not formatted correctly',
            PHONE_NUM_IS_SAME: 'Phone number is the same as the original',
            BIND_PHONE_SUCCESS: 'Bound phone success',
            SMS_CODE_ERROR: 'SMS verification code is not correct',
            SEND_SMS_CODE_FAIL: 'Failed to send a verification code',
            PHONE_NUM_EXIST: 'The phone number already exists'
        }
    },
    iot: {
        IOT: 'IOT',
        PARAMS_CONFIG: 'Config',
        // QUERY_KEYWORD: 'keyword search ...',
        TREE_ALL: 'All',
        TREE_HIDE: 'Hide',
        ADD_THING:'Add Thing',
        ADD_GROUP:'Add Group'
    },
    dataSource: {
        MONTH: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'July', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], //缺
        WEEK: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], //缺
        TITLE: 'Data source',
        DS_CONFIG: 'Data configuration',
        PROJECT_NAME: 'Project Name',
        PROJECT_SEARCH: 'Search',
        NUMBER: 'No.',
        POINT_NAME: 'Point name',
        POINT_DESC: 'Notes',
        POINT_ATTR: 'Attribute',
        SURE: 'Confirm',
        CANCEL: 'Cancel',
        PARAM: 'Parameter',
        USER_NAME: 'Account',
        CUSTOM_NAME: 'Custom name',
        CUSTOM_REPEAT: 'Duplicate customized name',
        CUSTOM_NOT_NULL: 'Customized name is required',
        FILTER_REPEAT_ITEM: 'Filter duplicates',
        FORMULA_TIPS: 'Please enter the formula ( according to variable list ):',
        FORMULA_NAME: 'Formula Name',
        FORMULA_VARIABLE_NAME: 'Variable',
        FORMULA_VARIABLE_VALUE: 'Point name',
        REMOVE_CONFIRM: 'Ensure remove ?',
        REMOVE_CONFIRM_TIPS: 'It relate',
        REMOVE_RESULT: 'deleted.',
        WORKSPACE: 'Workspace',
        TIME_YESTERDAY: 'Yesterday',
        TIME_TODAY: 'Today',
        NO_MATCH_FOUND: 'No matches found',
        NO_SELECT_POINT: 'Please select points !',
        GROUP_SELECTED: 'Selected',
        NO_SELECT_GROUP: 'Please select group !',
        INPUT_GROUP_NAME: 'Please input group name !',
        ADD_GROUP: '+ Add group',
        POINT_TYPE_CUSTOM: 'Custom',
        POINT_TYPE_SYSTEM: 'System',
        POINT_TYPE_DEVICE: 'Equipment',
        POINT_TYPE_TYPE: 'Type',
        ERROR: "Your Data Points has been removed, the chart can't render!",
        ICON_SYS_HVAC: 'HVAC',
        ICON_SYS_POWER: 'Power system',
        ICON_SYS_LIGHT: 'Lighting',
        ICON_SYS_CRAC: 'CRAC',
        ICON_DEV_CHIL: 'Chiller',
        ICON_DEV_PUMP: 'Pump',
        ICON_DEV_COOL: 'Cooling tower',
        ICON_DEV_AHU: 'AHU',
        ICON_DEV_VAV: 'VAV',
        ICON_DEV_SYS: 'System',
        ICON_TYPE_TEMP: 'Temperature',
        ICON_TYPE_FLOW: 'Flow rate',
        ICON_TYPE_FREQ: 'Frequency',
        ICON_TYPE_ONOFF: 'On Off',
        ICON_TYPE_ELEPOW: 'Electrical power',
        ICON_TYPE_ELEPOWMET: 'Electrical power meter',
        ICON_TYPE_THER: 'Thermal meter',
        ICON_TYPE_PRES: 'Pressure',
        ICON_TYPE_ALARM: 'Alarm',
        ICON_TYPE_CURFLOW: 'Current flow',
        NAV_MINE: 'Mine',
        NAV_CLOUD: 'Cloud',
        ALREADY_EXIST: 'It have removed existed item(s).',
        ADD_POINT_GROUP: 'add group',
        ADD_POINT: 'add point',
        ADD_FORMULA: 'add formula',
        RENAME: 'rename',
        REMOVE: 'remove',
        DELETE_GROUP_INFO: 'Please confirm whether to delete?',
        SEARCH_KEYWORD: 'Enter keywords'
    }
};