var i18n_resource = {
    admin: {
        login: {
            PANE_TITLE: "登 录",
            PANE_CHECKBOX_REMEMBER: "记住",
            PANE_PLACEHOLDER_ACCOUNT: "请输入用户名",
            PANE_PLACEHOLDER_PWD: "请输入密码",
            LOG_IN_FAILED: '登录失败',
            LOG_IN_EMPTY: '请输入用户名和密码',
        },
        welcom: {
            start: {
                TITLE: '开始',
                NEW_PROJECT: '新建项目...',
                IMPORT_PROJECT: '导入项目...',
            },
            yourProj:{
                TITLE: '您的项目',
                DELETE: '删除',
                TOP: '置顶',
                EXPORT:'导出',
                EDIT_AUTH: '编辑项目权限'
            },
            newProj: {
                ADD_PROJECT: '新增项目',
                PROJECT_NAME: '项目名称：',
                PROJECT_CHINESE_NAME: '项目中文名称：',
                PROJECT_ENGLISH_NAME: '项目英文名称：',
                ADD:'新增',
                CANSEL: '取消',
                PROJECT_NAME_NEW_PLACEHOLDER:'请输入项目的名称',
                PROJECT_NAME_PLACEHOLDER: '请输入项目名称',
                PROJECT_CHINESE_NAME_PLACEHOLDER: '请输入项目中文名称',
                PROJECT_ENGLISH_NAME_PLACEHOLDER: '请输入项目英文名称',
                LOG_ADD: '项目名称不能为空！',
                LOG_SAME_NAME:'项目已存在'
            },
            deleteProj: {
                DELETE_PROJECT:'删除项目',
                CONFIRM_INFO: '请确认是否删除项目？',
                CONFIRM_INFO_TIP: '请输入密码',
                SURE: '确认删除',
                CANCEL: '取消',
                DELETE_TITLE: '删除项目',
                PASSWORD: '密    码：',
                PROJECT_ENGLISH_NAME: '项目英文名称：',
                PASSWORD_PLACEHOLDER: '请输入密码',
                PROJECT_ENGLISH_NAME_PLACEHOLDER: '请输入项目的英文名称',
                OK: '确定',
            },
            importProjectModal: {
                TITLE: '导入线上项目',
                PROJECT_LIST_LABEL: '线上项目列表',
                CONFIRM_IMPORT: '确认导入',
                CANCEL: '取消'
            }
        },
        navIndex: {
            LINK_LANGUAGE: "语言"
        }
    },
    dataSource: {
        ADD_GROUP: '+ 添加分组',
        ADD_POINT_GROUP: '添加分组',
        ADD_POINT: '添加点',
        ADD_FORMULA: '添加公式',
        RENAME: '重命名',
        REMOVE: '删除'
    },
    toolBox: {
        TITLE: '可选模块',
        modal: {
            HIS_CHART: '历史图',
            HIS_CHART_ENERGY_LINE: '历史柱状图(年/月/周)',
            HIS_CHART_ENERGY_BAR: '历史能耗柱图',
            HIS_CHART_YEAR_LINE: '历史同比折线图',
            HIS_CHART_YEAR_BAR: '历史同比柱图',
            REAL_TIME_CHART: '实时图',
            REAL_TIME_CHART_PIE_ENERGY: '实时饼图',
            REAL_TIME_CHART_PIE_DATAROOM: '数据机房分项能耗饼图',
            REAL_TIME_CHART_LINE_OUTDOOR: '实时折线图',
            REAL_TIME_CHART_LINE_PUE: 'PUE趋势',
            REAL_TIME_CHART_GAUGE: '实时仪表盘',
            REAL_TIME_CHART_BAR_ENERGY: '实时分项柱图',
            REAL_TIME_CHART_LINE_ENERGY: '分项能耗折线图',
            REAL_TIME_CARBON_FOOTPRINT: '碳足迹排放量',
            REAL_TIME_WEATHER: '天气趋势',
            REAL_TIME_ENERGY_SAVE_RATE: '节能率',
            REAL_TIME_COAL_SAVE_TOTAL: '累计节省标煤',
            REAL_TIME_CO2_SAVE_TOTAL: '累计节省CO₂排放',
            REAL_TIME_KPI_CHART: 'KPI仪表盘',
            REAL_TIME_BAR: '实时柱图',
            OBSERVER: '组态页面',
            REAL_TIME_PREDICT_POINT_LINE: '实时预测折线图',
            TRANSIT: '数据分析',
            MULTIPLE: "复合图",
            NOTE: '便签',
            WHIRLWIND_CHART: '旋风图',
            RANK_CHART: '排行图',
            MIX: '组合图',
            MODAL_HTML: 'HTML模块',
            MSG_MIX_NOT_ALLOW_TO_MIX: '组合图不可以拖入组合图',
            CUSTOM_CHART: '自定义图',
            POINT_KPI: 'KPI尊享版',
            REPORT_CHAPTER: '报表章节',
            MSG_KPI_NOT_ALLOW_TO_MIX: 'KPI尊享版不可以拖入组合图',
            INTERACT_CHART: '交互趋势图'
        }
    },
    dashboard: {
        modalHistoryChart: {
            MAXIMUM: '最大值',
            MINIMUM: '最小值',
            EnergyConsumption: '能耗'
        },
        modalWeather: {
            REAL_TIME_TEMPERATURE: '实时温度'
        },
        modalConfig: {
            POINT_DRAG_TIP: "请将数据点拖拽至此……",
            ERR: "点数过多，无法继续增加！"
        },
        resize: {
            ERR1: "输入值大小大于目标允许最大值，请重新输入！",
            ERR2: "输入值大小小于目标允许最小值，请重新输入！",
            ERR3: "输入值必须为纯数字，请检查格式！"
        },
        show: {
            TITLE_TIP: "请输入标题",
            TITLE: '标题',
            SELECT_LINK: '选择链接',
            TYPE: '类别',
            LINK_TO: '链接到',
            DESC: "描述",
            DESC_TIP: "请在这里添加描述",
            WIKI_ID: "Wiki id",
            POP_ID: 'Pop id'
        },
        modalPointKPI: {
            PASS: '达标',
            UNPASS: '未达标',
            MONTH: '月',
            QUARTER: '季度'
        },
        modalJumpPages: {
            IMPORT_PAGE: '导入到数据源',
            POINT_LIST: '数据点名',
            GROUP_LIST: '选择数据源',
            SUCCESS_TIPS: '成功，是否跳转到数据分析页面 ？',
            FAIL_TIPS: '导出失败！',
            NO_FIT_POINT: '无可导数据点',
            SURE: '确定并跳转',
            CANCEL: '确定',
            NEW_GROUP: '新建数据源',
            SELECT_ALL: '全选',
            SELECT_REVERT: '反选',
            NEW_DS_NAME: '新数据源名称'
        }
    },
    analysis: {
        TITLE: "数据分析",
        PANE_POINTS_ALL_TITLE: "所有点（单击选取）",
        PANE_POINTS_SELECTED_TITLE: "已选择的点（单击删除）",
        MARK_SELECTED: "已选",
        PANE_ADD_NOTE: '新建便签',
        BACK_TO_HOMEPAGE: '返回主菜单',
        PANE_CONFIG: '设置',
        PANE_FULL_SCREEN: '全屏',
        modalType: {
            TENDENCY: "趋势图",
            STACK: "面积图",
            SPECTRUM: "频谱图",
            SCATTER: "散点图",
            HISTORY_COMPARE: "历史同比柱图",
            HISTORY_COMPARE_LINE: "历史同比折线图",
            ENERGY: "能耗柱图",
            CLUSTER: "模式分析",
            PIE_REAL_TIME: "实时饼图",
            CLUSTER_AHU: "AHU诊断",
            CLUSTER_CHILLER: "冷机诊断"
        },

        paneConfig: {
            TITLE: "配置数据源",
            DATA_CONFIG_TITLE: "数据点位（每项上限5个）",
            DATA_DRAG_TIP: "请将数据拖拽至此",
            LABEL_INVERAL: "时间间隔",
            LABEL_TIME_START: "开始时间",
            LABEL_TIME_END: "结束时间",
            ALIGN_MODE: "补齐方式",
            ALIGN_FORWARD: "向前补齐",
            ALIGN_BACKWARD: "向后补齐",
            ALIGN_LINEAR: "线性插值",
            START_ANALYSIS: "开始分析",
            FUNCTION: "功  能",
            DATA_DEAL: "数据处理",
            DATA_DIVIDE: "数据分类",
            TREND_ANALYSE: "趋势分析",
            FREQ_ANALYSE: "频谱分析",
            YEAR: "年",
            MONTH: "月",
            DAY: "日",
            HOUR: "小时",
            MINUTE: "分钟",
            SECOND: "秒",
            RECFG_SRC_DATA: "重新配置源数据",
            SEL_PT_NAME: "已选点名",
            TREND_DISTRIBUTE: "趋势分布",
            TYPE_POINT: "分类散点",
            TYPICAL_CONDITION: "典型工况",
            DIAGNOSES_RESULT: "诊断结论",
            DATE: "日期",
            POINT_NUM: "点数",
            MISS_NUM: "丢失数量",
            MISS_RATE: "丢失率",
            ARGUMENTS: "参数",
            NAME: "名称",
            DESC: "描述",
            MAX: "最大值",
            MIN: "最小值",
            MED: "中间值",
            AVG: "平均值",
            STD: "标准值",
            RANGE_TO: "到",
            MODE_FIXED: "固定周期",
            MODE_RECENT: "最近周期",
            MODE_CURRENT: "预设周期",
            MODE_ACTUAL_TIME: "实时",
            INTERVAL_MIN1: "1分钟",
            INTERVAL_MIN5: "5分钟",
            INTERVAL_HOUR1: "1小时",
            INTERVAL_DAY1: "1天",
            INTERVAL_MON1: "1个月",
            TIME_RANGE_SEC: "秒",
            TIME_RANGE_MIN: "分钟",
            TIME_RANGE_HOUR: "小时",
            TIME_RANGE_DAY: "天",
            TIME_RANGE_MON: "月",
            DATA_TYPE_DEFAULT: "数据点位",
            ERR1: "请求后台数据失败",
            ERR2: "已存在于选取点列表中！",
            ERR3: "您还未选择过任何点！",
            ERR4: "请求频谱分析、数据分类数据失败！",
            ERR5: "所选的点在指定时间段内均无数据，请重新选择!",
            ERR6: "无历史数据点：",
            ERR7: "已被自动移除！",
            ERR8: "时间格式错误：开始时间晚于结束时间！",
            ERR9: "时间格式错误：结束时间晚于当前时间！",
            ERR10: "数据点重复：您拖动到此的数据点已存在！",
            ERR11: "数据错误：该时间段无法找到任何数据！",
            ERR12: "数据点过多，无法继续拖拽！"
        }
    },
    modalConfig: {
        TITLE: '配置',
        option: {
            SEARCH: "查询",
            LABEL_MODE: "模式",
            MODE_FIXED: "固定周期",
            MODE_RECENT: "最近周期",
            MODE_CURRENT: "快速配置",
            MODE_REAL_TIME: "实时",
            MODE_HISTORY: "历史",
            MODE_COMPARE_EASY: "快速配置",
            MODE_COMPARE_SENSOR: "传感器数据",
            MODE_COMPARE_METER: "能耗表数据",
            MODE_GAUGE: "仪表盘",
            MODE_WEATHER: "天气",
            LABEL_INTERVAL: "采样周期",
            INTERVAL_MIN1: "1分钟",
            INTERVAL_MIN5: "5分钟",
            INTERVAL_HOUR1: "1小时",
            INTERVAL_DAY1: "1天",
            INTERVAL_MON1: "1个月",
            LABEL_PERIOD: "时间周期",
            PERIOD_DROP_DOWN_LAST_HOUR: "过去1小时",
            PERIOD_DROP_DOWN_TODAY: "过去24小时",
            PERIOD_DROP_DOWN_YESTERDAY: "昨天（24小时）",
            PERIOD_DROP_DOWN_THREE_DAY: "过去72小时",
            PERIOD_DROP_DOWN_THIS_WEEK: "过去7天",
            PERIOD_DROP_DOWN_LAST_WEEK: "上周（7天）",
            PERIOD_DROP_DOWN_LAST_30_DAYS: "过去30天",
            PERIOD_DROP_DOWN_LAST_90_DAYS: "过去90天",
            PERIOD_DROP_DOWN_THIS_YEAR: "过去12个月",
            PERIOD_UNIT_SEC: "秒",
            PERIOD_UNIT_MIN: "分钟",
            PERIOD_UNIT_HOUR: "小时",
            PERIOD_UNIT_DAY: "天",
            PERIOD_UNIT_MON: "月",
            LABEL_TIME_RANGE: "时间范围",
            TIP_RANGE_TO: "到",
            LABEL_GAUGE_MODE: "异常模式",
            GAUGE_MODE_LOW: "低值异常",
            GAUGE_MODE_HIGH: "高值异常",
            GAUGE_GREEN: "节能",
            GAUGE_NORMAL: "正常",
            GAUGE_RED: "警报",
            LABEL_REAL_TIME_INTERVAL: "刷新间隔",
            REAL_TIME_INTERVAL_30_SEC: "30秒",
            REAL_TIME_INTERVAL_1_MIN: "1分钟",
            REAL_TIME_INTERVAL_5_MIN: "5分钟",
            REAL_TIME_INTERVAL_10_MIN: "10分钟",
            REAL_TIME_INTERVAL_30_MIN: "30分钟",
            REAL_TIME_INTERVAL_1_HOUR: "1小时",
            REAL_TIME_INTERVAL_1_DAY: "1天",
            REAL_TIME_INTERVAL_1_MON: "1个月",
            LABEL_WEATHER: "城市代码",
            LABEL_COMPARE_PERIOD: "对比周期",
            LABEL_COMPARE_DATE1: "时间1",
            LABEL_COMPARE_DATE2: "时间2",
            COMPARE_PERIOD_HOUR: "1小时",
            COMPARE_PERIOD_DAY: "1天",
            COMPARE_PERIOD_WEEK: "1星期",
            COMPARE_PERIOD_MONTH: "1个月",
            COMPARE_PERIOD_YEAR: "1年",
            LABEL_HISTORY_RANGE: "时间范围",
            HISTORY_RANGE_HOUR: "1小时",
            HISTORY_RANGE_DAY: "1天",
            HISTORY_RANGE_WEEK: "1周",
            HISTORY_RANGE_MONTH: "1个月",
            HISTORY_RANGE_YEAR: "1年",
            LABEL_CHART_SELECT: "图表类型",
            CHART_SELECT_BAR: "柱图",
            CHART_SELECT_LINE: "折线图",
            CHART_TYPE: '图表类别',
            PIE: '饼图',
            BAR: '柱图',
            DEFAULT_TYPE: '默认类别',
            DEFAULT_LINE: '折线图',
            DEFAULT_BAR: '柱图',
            MODIFY_CHART_TITLE: '标题内容',
            MODIFY_CHART_YAXIS_NAME: '纵坐标名称',
            MODIFY_CHART_YAXIS_UNIT: '纵坐标单位',
            MODIFY_CHART_MAX: '最大值',
            MODIFY_CHART_MIN: '最小值',
            MODIFY_CHART_MARK: '刻度',
            MODIFY_CHART_CONFIG: '高级配置'
        },
        data: {
            DATA_CONFIG_TITLE: "数据点位:",
            DATA_CONFIG_TIPS: '此项最多配置20个点，如需添加新点请删除多余项。',
            //DATA_CONFIG_TITLE_TYPE1: "每项上限5个 ",
            DATA_TYPE_MAX_NUM: " (上限<%maxNum%>个)",
            DEFAULT_NAME: "数据点位",
            DASHBOARD_MULTI_BAR: "柱图参数",
            DASHBOARD_MULTI_LINE: "折线图参数",
            DASHBOARD_MULTI_AREA: "面积图参数",
            DASHBOARD_MULTI_CUMULATIVE_BAR: "累计柱图参数",
            DATA_LOSE: "丢失",
            PT_UPPER: "坐标轴上限",
            PT_LOWER: "坐标轴下限",
            PT_UNIT: "坐标轴单位",
            PT_ACCURACY: "小数点位数",
            PT_COG_SURE: "确认",
            PT_COG_CANCEL: "取消",
            PT_LINE_1: "基线1",
            PT_LINE_2: "基线2",
            PT_LINE_3: "基线3",
            PT_LINE_4: "基线4",
            PT_LINE_NAME: "名称",
            PT_LINE_VAL: "数值",
            DATA_SHOW: "数据",
            TIME_MODE: "时间模式"
        },
        err: {
            TYPE1: "数据点过多，无法继续拖拽！",
            TYPE2: "数据点重复：您拖动到此的数据点已存在！",
            TYPE3: "时间格式错误：开始时间晚于结束时间！",
            TYPE4: "时间格式错误：结束时间晚于当前时间！",
            TYPE5: "仪表盘参数错误：参数大小没有按照从小到大排序",
            TYPE6: "没有历史数据！",
            TYPE7: "时间参数没有传入数据库！",
            TYPE8: "时间格式无法识别！",
            TYPE9: "时间周期数值对于当前时间周期单位过长！",
            TYPE10: "含有非数字参数，请检查！",
            TYPE11: "部分数据点丟失，可能已被删除！",
            TYPE12: "数据点数值范围上限超过下限！"
        },
        btnStartConfig: {
            TYPE1: "开始分析",
            TYPE2: "确定"
        }
    },
    dataSource: {
        MONTH: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
        WEEK: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
        TITLE: '数据源',
        DS_CONFIG: '数据源配置',
        PROJECT_NAME: '项目名',
        PROJECT_SEARCH: '搜索',
        NUMBER: '编号',
        POINT_NAME: '点名',
        POINT_DESC: '注释',
        POINT_ATTR: '属性',
        SURE: '确认',
        CANCEL: '取消',
        PARAM: '参数',
        USER_NAME: '用户名',
        CUSTOM_NAME: '自定义名',
        FILTER_REPEAT_ITEM: '已过滤重复项',
        CUSTOM_REPEAT: '自定义名重复',
        CUSTOM_NOT_NULL: '自定义名不能为空',
        FORMULA_TIPS: '请输入公式（参数请按照参数列表中参数名输入）：',
        FORMULA_NAME: '公式名',
        FORMULA_VARIABLE_NAME: '变量名',
        FORMULA_VARIABLE_VALUE: '实际值',
        REMOVE_CONFIRM: '确认删除？',
        REMOVE_CONFIRM_TIPS: '已关联',
        REMOVE_RESULT: '已删除',
        WORKSPACE: '工作空间',
        TIME_YESTERDAY: '昨天',
        TIME_TODAY: '今天',
        NO_MATCH_FOUND: '未找到匹配结果',
        NO_SELECT_POINT: '请选择点！',
        GROUP_SELECTED: '已选',
        NO_SELECT_GROUP: '请选择组！',
        INPUT_GROUP_NAME: '请输入组名！',
        ADD_GROUP: '+ 添加分组',
        POINT_TYPE_CUSTOM: '自定义',
        POINT_TYPE_SYSTEM: '系统',
        POINT_TYPE_DEVICE: '设备',
        POINT_TYPE_TYPE: '类型',
        ERROR: '你的数据源已被删除，图表无法生成！',
        ICON_SYS_HVAC: '暖通',
        ICON_SYS_POWER: '动力',
        ICON_SYS_LIGHT: '照明插座',
        ICON_SYS_CRAC: '精密空调',
        ICON_DEV_CHIL: '冷机',
        ICON_DEV_PUMP: '水泵',
        ICON_DEV_COOL: '冷却塔',
        ICON_DEV_AHU: 'AHU',
        ICON_DEV_VAV: 'VAV',
        ICON_DEV_SYS: '系统',
        ICON_TYPE_TEMP: '温度',
        ICON_TYPE_FLOW: '流量',
        ICON_TYPE_FREQ: '频率',
        ICON_TYPE_ONOFF: '启停',
        ICON_TYPE_ELEPOW: '功率',
        ICON_TYPE_ELEPOWMET: '电量表',
        ICON_TYPE_THER: '冷量表',
        ICON_TYPE_PRES: '压力',
        ICON_TYPE_ALARM: '报警',
        ICON_TYPE_CURFLOW: '电流',
        NAV_MINE: '我的',
        NAV_CLOUD: '公共',
        ALREADY_EXIST: '添加已去除重复项',
        ADD_POINT_GROUP: '添加分组',
        ADD_POINT: '添加点',
        ADD_FORMULA: '添加公式',
        RENAME: '重命名',
        REMOVE: '删除'
    },
    mainPanel: {
        ueserOpera: {
            CHANGE_PROJECT: '切换项目',
            RELEASE_PROJECT: '发布项目',
            CANCELLATION:'注销'
        },
        navbar: {
            SAVE_PAGE: '保存',
            PREVIEW_PAGE: '预览',
            UNDO: '撤销',
            REDO: '重做',
            RELEASE_PAGE:'发布页面'
        },
        toolbar: {
            ARROW_TOOL:'箭头工具',
            HAND_TOOL: '手型工具',
            TEXT_TOOL: '文本控件',
            BUTTON_TOOL: '按钮控件',
            HTML_TOOL: 'Html容器控件',
            SCREEN_TOOL: 'Screen容器控件',
            IMG_TOOL: '图片控件',
            PIPE_TOOL: '管道控件',
            MATERAL_TOOL: '项目素材控件',
            GRID_TOOL: '显示网格线'
        },
        releaseRepeat: {
            TITLE: '发布',
            RELEASE_INFO: '请确认是否发布？',
            RELEASE_START: '开始发布',
            RELEASE_NO: '取消',
            RELEASE_TITLE: '填写发布信息',
            PASSWORD: '密 码:',
            RELEASE_TO: '发布到:',
            PASSWORD_INFO: '请输入发布密码',
            OK: '发布成功！',
            NO: '发布失败！',
            SELECT: '请选择',
            NEW_PROJECT:'新项目'
        },
        releasePage: {
            PROJECT_NAME: '项目名称:',
            NAME_INFO: '请输入项目英文名称',
            RELEASE_INFO: '密码填写错误！',
            RELEASE_INFO_TIP: '请至少选择一个项目！'
        },
        releaseProject: {
            RELEASE_INFO: '密码填写错误！'
        },
        layerPanel: {
            TITLE: '图层',
            HTML_LAYER: 'Html 图层',
            BG_LAYER:'背景',
            EXPORT_INFO: '请选择一个图层！',
            EXPORT_INFO_TIP: '目前只支持canvas图层模板的导出',
            DELETE_INFO: 'Html图层和背景图层不能被删除',
            DELETE_INFO_TIP: '不可以删除被锁定的图层',
            DRAG_LAYER_INFO: '请选择一个图层进行拖拽！',
            ADD_GROUP: '新建文件夹',
            ADD_PAGE: '新建页面',
            EDIT_PAGE: '编辑页面',
            LOCK_PAGE: '锁定页面',
            EXPORT_PAGE_TEMPLET: '导出页面模板',
            IMPORT_PAGE_TEMPLET: '导入页面模板',
            DELETE_PAGE:'删除页面',
            ADD_LAYER: '新建图层',
            EDIT_LAYER: '编辑图层',
            LOCK_LAYER: '锁定图层',
            EXPORT_LAYER_TEMPLET: '导出图层模板',
            IMPORT_LAYER_TEMPLET: '导入图层模板',
            DELETE_LAYER:'删除图层'
        },
        historyPanel: {
            UNDEFINED: '未定义的操作',
            CREATE_LAYER: '创建图层',
            DELETE_LAYER: '删除图层',
            CHANGE_LAYER_NAME: '修改图层名称',
            SHOW_LAYER: '显示图层',
            HIDE_LAYER: '隐藏图层',
            UNLOCK_LAYER: '解锁图层',
            CREATE_WIDGET: '创建控件',
            DELETE_WIDGET: '删除控件',
            MOVE_WIDGET: '移动位置',
            RESIZE_WIDGET: '调整大小',
            MOVE_WIDGET_OR_RESIZE_WIDGET: '改变控件位置或者大小',
            CREATE_BUTTON_WIDGET: '创建按钮控件',
            DELETE_BUTTON_WIDGET: '删除按钮控件',
            CHANGE_BUTTON_WIDGET_TEXT: '改变按钮文字',
            CHANGE_BUTTON_WIDGET_STYLE: '改变按钮样式',
            ADD_BUTTON_WIDGET_IDDS: '给按钮控件添加数据源',
            CHANGE_BUTTON_WIDGET_ENUMERATE: '改变按钮控件枚举',
            CHANGE_BUTTON_WIDGET_IDDS: '改变按钮控件数据源',
            CHANGE_BUTTON_WIDGET_CUSTOMSTYLE: '改变按钮控件自定义样式',
            CREATE_TEXT_WIDGET: '创建文本控件',
            DELETE_TEXT_WIDGET: '删除文本控件',
            CHANGE_TEXT_WIDGET_TEXT: '改变文本文字',
            CHANGE_TEXT_WIDGET_STYLE: '改变文本样式',
            ADD_TEXT_WIDGET_IDDS: '给文本控件添加数据源',
            CHANGE_TEXT_WIDGET_ENUMERATE: '改变文本控件枚举',
            CHANGE_TEXT_WIDGET_IDDS: '改变文本控件数据源',
            CHANGE_TEXT_WIDGET_CUSTOMSTYLE: '改变文本控件自定义样式',
            CHANGE_TEXT_WIDGET_PRECISION: '改变文本控件的数字精确度',
            CREATE_HTMLCONTAINER_WIDGET: '创建Html容器控件',
            DELETE_HTMLCONTAINER_WIDGET: '删除Html容器控件',
            CHANGE_HTMLCONTAINER_WIDGET_CONTENT: '改变Html容器控件内容',
            EXPORT_HTMLCONTAINER_WIDGET: '导出Html容器控件',
            IMPORT_HTMLCONTAINER_WIDGET: '导入Html容器控件',
            CREATE_HTMLSCREENCONTAINER_WIDGET: '创建Screen容器控件',
            DELETE_HTMLSCREENCONTAINER_WIDGET: '删除Screen容器控件',
            CHANGE_HTMLSCREENCONTAINER_WIDGET_CONTENT: '改变Screen容器控件页面内容',
            CHANGE_HTMLSCREENCONTAINER_WIDGET_CUSTOMSTYLE: '改变Screen容器控件自定义样式',
            CREATE_PIPE_WIDGET: '创建管道控件',
            DELETE_PIPE_WIDGET: '删除管道控件',
            CHANGE_PIPE_WIDGET_WIDTH: '改变管道控件长度',
            CHANGE_PIPE_WIDGET_COLOR: '改变管道控件颜色',
            ADD_PIPE_WIDGET_IDDS: '给管道控件添加数据源',
            CHANGE_PIPE_WIDGET_ENUMERATE: '改变管道控件枚举',
            CHANGE_PIPE_WIDGET_IDDS: '改变管道控件数据源',
            CREATE_IMAGE_WIDGET: '创建图片控件',
            DELETE_IMAGE_WIDGET: '删除图片控件',
            CHANGE_IMAGE_WIDGET_CONTENT: '改变图片控件内容',
            CHANGE_IMAGE_WIDGET_ANGLE: '改变图片控件角度',
            ADD_IMAGE_WIDGET_IDDS: '给图片控件添加数据源',
            CHANGE_IMAGE_WIDGET_ENUMERATE: '改变图片控件枚举',
            CHANGE_IMAGE_WIDGET_IDDS: '改变图片控件数据源'
        },
        exportModal: {
            EXPORT_INFO:'输入模板名称',
        },
        attrPanel: {
            attrTab: {
                TITLE:'属性',
                PAGE_MANAGE: '页面管理',
                DATA_SOURCE: '数据源',
                HISTORY_RECORD: '历史记录',
                REPORT_TPL: '报表模板'
            },
            attrRepeat: {
                STYLE: '样式:',
                CONTENT: '内容:',
                DATA_SOURCE: '数据源:',
                CUSTOMSTYLE: '自定义样式:',
                EDIT_CONTENT_TITLE: '编辑内容',
                SAVE_STYLE_TITLE: '应用',
                EXPORT_STYLE_TITLE: '导出模板',
                IMPORT_STYLE_TITLE: '导入模板',
                PAGE: '页面:',
                SELECT_SCREEN:'选择页面'
            },
            attrText: {
                TEXT_CONDITION: '请此处输入文本',
                TEXT_ONE: '正文1',
                TEXT_TWO: '正文2',
                TITLE_ONE: '标题1',
                TITLE_TWO: '标题2',
                TITLE_THREE: '标题3',
                TITLE_FOUR: '标题4',
                TITLE_FIVE: '标题5',
                SUBTITLE:'副标题',
            },
            attrButton: {
                STYLE_ONE: '默认',
                STYLE_TWO: 'Primary',
                STYLE_THREE: 'Success',
                STYLE_FOUR: 'Info',
                STYLE_FIVE: 'Warning',
                STYLE_SIX: 'Danger',
                STYLE_SEVEN: 'Link',
                STYLE_EIGHT: '粉红色',
                STYLE_NINE: '蓝色',
                STYLE_TEN: '绿色'
            },
            attrHtml: {
                TITLE: '代码编辑器',
                RUNCODE: '运行代码',
                SAVEANDEXIT: '保存并退出',
            },
            attrImg: {
                IMAGE: '图片: ',
                ROTATE: '旋转: ',
                CHOOSE: '选择',
                ENUMER_INFO: '先输入key值,谢谢!'
            },
            attrPipe: {
                PIPE_WIDTH: '管道长度:',
                PIPE_COLOR:'管道颜色:'
            }
        },
        materalPanel: {
            toolbar: {
                TITLE:'项目素材库',
                PRIVATE_MATERAL: '收藏',
                PAGE_MATERAL: '页面',
                LAYER_MATERAL: '图层',
                BUTTON_MATERAL: '控件',
                PUBLIC_MATERAL:'素材'
            },
            materalRepeat: {
                USE_MODAL: '使用素材',
                DELETE_OK: '删除成功',
                ADD_OK:'添加成功',
                PHOTO: '图片',
                ANIMATION:'动画',
                PAGE_NAME: '名称：',
                PAGE_CREATOR: '创建人：',
                PAGE_TIME: '创建时间：',
                FORMAT_LOG: '内容格式错误！'
            },
            privateMateral: {
                ADD_PHOTO: '从素材添加图片',
                DELETE_PHOTO: '删除图片',
                USE_PHOTO:'使用'
            },
            pageMateral: {
                ADD_MODAL: '新建模板',
                BATCH_ADD: '批量生成',
                EDIT_PAGE: '编辑页面',
                DELETE_PAGE: '删除页面',
            },
            layerMateral: {
                EDIT_LAYER: '编辑图层',
                DELETE_LAYER:'删除图层'
            },
            buttonMateral: {
                EDIT_BUTTON: '编辑控件',
                DELETE_BUTTON: '删除控件',
                USE_COPY: '是否保留副本?'
            },
            publicMateral: {
                UPLOAD_PHOTO: '上传图片',
                ADD_PRIVATE: '添加到收藏',
                DELETE_PHOTO: '删除公共素材',
                UPLOAD_INFO: '图片类型应该是.gif,jpg,png,jpeg中的一种',
                UPLOAD_INFO_TIP: '图片应该不大于600K。'
            }
        }
    },
    screen: {
        UNSAVED_PAGE_TIP: '您还有未保存的数据，确定离开吗？'
    },
    modal: {
        memberSelected: {
            CONFIRM: '确认',
            TITLE: "请选择人员",
            INPUT_INFO: "请输入用户名称",
            ALL: '全部',
            MEMBER_SELECTED: '已选成员'
        }
    }
}