FROM beopweb:lastest

WORKDIR /project

COPY . /project

RUN pip3 install -r /project/requirements/requirements-main.txt --index http://pypi.doubanio.com/simple --trusted-host pypi.doubanio.com && \
    pip3 install -r /project/requirements/requirements-dev.txt --index http://pypi.doubanio.com/simple --trusted-host pypi.doubanio.com

EXPOSE 80
