var i18n_resource = {
    equipTree:{
        SEARCH: "搜索",
        SHOW_ALL_STRATEGIES: "显示所有子策略"
    },
    strategyTable:{
        ADD: "新增",
        DELETE: "删除",
        PROJECT_CONFIGURATION: "项目配置",
        SUPPLEMENTARY_DIAGNOSIS:"补诊断",
        UPDATE_DIAGNOSTIC_TABLE: "更新诊断表",
        TAG_TRANSFER: 'tag转换',
        ENABLE: "启用",
        DISABLE: "禁用",
        NO_RECORD: "无记录",
        NAME: "名称",
        DEPENDENCIES: "从属",
        STATE: "状态",
        THE_LAST_TIME_TO_PERFORM: "上次执行",
        TYPE: "类型",
        MODIFIER: "修改人",
        MODIFICATION_TIME: "修改时间",
        DESCRIPTION: "描述",
        DIAGNOSE: "诊断",
        KPI: "KPI",
        CALCULATION_POINT: "计算点",
        NOT_ENABLED: "未启用",
        ENABLED: "已启用",
        OPERATION: '操作'
    },
    propTree:{
        STRATEGIES_DOMINATION: "策略配置",
        RECOVER: "恢复",
        SAVE: "保存",
        NAME: "名字",
        STATE: "状态",
        TYPE: "类型",
        LEVEL: "级别",
        DESCRIPTION: "描述",
        TRAIN_INTERVAL: "运行间隔",
        DEPENDENCIES: "从属",
        THE_LAST_TIME_RUNNING_TIME: "最后运行时间",
        MODIFIER: "修改人",
        THE_LAST_MODIFICATION_TIME: "最后修改时间",
        FAULT_TABLE_STATUS: "Fault表状态",
        FAULT_TABLE_UPDATE: "已更新到最新",
        UPDATE: "更新",
        DISABLE: "不启用",
        ENABLE: "启用",
        DESC: '暂无描述信息'
    },
    app:{
        PROPERTY: "属性",
        LOGOUT: "注销",
        LANGUAGE: "语言",
        CHINESE: "中文"
    },
    sketchpad:{
        LEAD_STRATEGY: "前置策略",
        CONFIGURATION_PARAMETER: "配置参数",
        DEBUG: "调试",
        SAVE: "保存",
        RETURN: "返回",
        MODIFY_THE_MATCH: "修改匹配"
    },
    moduleConfigPanel:{
        INPUT: "输入",
        OUTPUT: "输出",
        DATA_SOURCE: "数据源"
    },
    painter:{
        RULE: "模板",
        DATA_SOURCE: "数据源",
        MODULE_PROPERTIES: "模块属性"
    },
    inputOutputParameter:{
        PACK_UP_A_KEY: "一键收起",
        A_KEY_IN: "一键展开",
        IMPORT: "导入",
        ADD: "新增",
        PARAMETER_NAME: "参数名",
        TYPE: "类型",
        DEFAULT: "默认值",
        ANNOTATION: "注释",
        ENABLE: "启用",
        DISABLE: "禁用",
        INPUT_SOURCE: "输入源",
        BULK_COPY: "批量复制",
        Parameters: "个参数"
    },
    moduleContent:{
        FUZZY_RULE_MODULE_TO_EDIT: "模糊规则 模块编辑",
        CORRELATION_MODULE_TO_EDIT: "相关性分析 模块编辑",
        FORECAST_MODULE_TO_EDIT: "预测 模块编辑",
        HISTORICAL_CURVE_MODULE_TO_EDIT: "历史曲线 模块编辑",
        PYTHON_MODULE_TO_EDIT: "Python 模块编辑",
        TABLE_MODULE_TO_EDIT: "表格 模块编辑",
        TD_VIEW_MODULE_TO_EDIT: "3D视图 模块编辑",
        RETURN: "返回",
        OK: "确认",
        CANCEL: "取消",
        GRAPH: "图形",
        CODE: "代码",
        CONDITION: "条件",
        CONCLUSION: "结论"
    },
    debug:{
        CONSOLE: "控制台",
        RUN: "运行",
        RETURN: "返回",
        INPUT: "输入",
        WATCH: "监视",
        DATA_SOURCE: "数据源"
    },
    moduleProp:{
        NAME: "名字:",
        LABEL: "标签:",
        PATTERN: "模式:",
        FORMULA_OF_INPUT: "显示/隐藏:",
        SHOW: "显示",
        HIDDEN: "隐藏",
        NULL: "无",
        RAPID_CONFIGURATION: "快速配置",
        FIXED_CYCLE: "固定周期",
        RECENT_CYCLE: "最近周期",
        TIME_PERIOD: "时间周期:",
        THE_PAST_24_HOURS: "过去24小时",
        YESTERDAY: "昨天(24小时)",
        THE_PAST_7_DAYS: "过去7天",
        LAST_WEEK: "上周(7天)",
        THE_PAST_12_MONTHS: "过去12个月",
        SAMPLING_PERIOD: "采样周期:",
        ONE_MINUTE: "1分钟",
        FIVE_MINUTES: "5分钟",
        ONE_HOUR: "1小时",
        ONE_DAY: "1天",
        ONE_MONTH: "1月",
        START_TIME: "开始时间:",
        END_TIME: "结束时间:",
        NUMBER: "个数:",
        TIME_UNIT: "时间单位:",
        HOUR: "小时",
        DAY: "天",
        MONTH: "月"
    },
    modal:{
        STRATEGIES_DOMINATION: "策略配置",
        SAVE: "保存",
        OK: "确认",
        CANCEL: "取消",
        SUPPLEMENTARY_DIAGNOSIS:"补诊断",
        START_TIME: "开始时间",
        END_TIME: "结束时间",
        TIME_INTERVAL: "时间间隔",
        FRONT_POLICY_CONFIGURATION: "前置策略配置",
        DRAG_TO_ADD: "拖拽添加",
        REFER_TO_EXTERNAL_POLICY_INPUT_AND_OUTPUT_PARAMETERS_CONFIGURATION: "引用外部策略输入输出参数配置",
        PARAMETER_CONFIGURATION: "参数配置",
        CHECK_ALL: "全选",
        INVERT_SELECTION: "反选",
        EXPORT_TO_EXCEL: "导出Excel",
        IMPORT_TO_EXCEL: "导入Excel",
        IMPORT_EXCEL_FAIL: "导入Excel失败",
        ADD: "新增",
        A_BATCH_OF_NEW: "批量新增",
        DELETE: "删除",
        ADD_PARAMETER: "新增参数",
        EDIT_PARAMETER: "修改参数",
        PARAMETER_GROUP_NAME: "参数组名称",
        CONFIRM_THE_NEW: "确认新增",
        CONFIRM_THE_CHANGE: "确认修改",
        DEBUGGING_VALUES: "调试值 : ",
        VIEW_AS_TEXT: "变量查看 : ",
        SEE_THE_VALUE: "查看值 : ",
        FORMATTING: "格式化",
        NOT_AVAILABLE: "不可用",
        NO_DATA: "没有数据",
        PREDICTED_VALUE: "预测值",
        TD_VIEW: "3D视图",
        HISTORICAL_CURVE: "历史曲线",
        HISTORICAL_VALUE: "历史值",
        TIME: "时间",
        DATA_SOURCE_CONFIGURATION: "数据源配置",
        THE_NEW_INPUT_PARAMETERS: "新增输入参数",
        ALIAS: "别名",
        UNIT: "单位",
        TYPE: "类型",
        SEQUENTIAL_CHECKING: "时序检查",
        YES: "是",
        NO: "否",
        SENSOR_ACCURACY: "传感器精度",
        FORMULA_CONFIGURATION: "公式配置",
        STATE: "状态",
        OPEN: "开启",
        CLOSE: "关闭",
        VIEW: "视图",
        SET: "设置",
        PARAMETER_OF_THE_CODE: "参数代码",
        THE_NEW_OUTPUT_PARAMETERS: "新增输出参数",
        FULL_NAME: "全名",
        FAULT_TEMPLATE: "Fault模板",
        FAULT_IMPACT_RATE: "故障影响率",
        FAULT_TYPES_GROUPED: "故障类型分组",
        FAULT_SOURCE: "故障来源",
        FAULT_TEMPLATE_SELECT: "选择模板",
        FAULT_GROUP: "故障所在组",
        FAULT_EFFECT: "故障影响",
        GRADE: "等级",
        ABNORMAL: "异常",
        FAULT: "故障",
        PEOPLE_GROUP: "人员所在组",
        PERFORM_STAFF: "执行人员",
        RUNNING_MODE: "运行模式",
        ALL: "全部",
        REFRIGERATION: "制冷",
        HEATING: "制热",
        ENERGY_CONSUMPTION_OF_THE_DAY: "能耗所用天",
        ENERGY_CONSUMPTION_OF_THE_WEEK: "能耗所用周",
        ENERGY_CONSUMPTION_OF_THE_MONTH: "能耗所用月",
        ENERGY_CONSUMPTION_OF_THE_YEAR: "能耗所用年",
        ENERGY_CONSUMPTION_OF_THE_UNIT: "能耗单位",
        ENERGY_CONSUMPTION_OF_THE_CONFIGURATION: "能耗配置",
        HOUR: "小时",
        DESCRIPTION: "描述",
        SUGGESTION: "建议",
        CHART_TITLE: "图表标题",
        CHART_LEGEND: "图表图例",
        TRAIN_INTERVAL: "运行间隔",
        JANUARY: "一月",
        FEBRUARY: "二月",
        MARCH: "三月",
        APRIL: "四月",
        MAY: "五月",
        JUNE: "六月",
        JULY: "七月",
        AUGUST: "八月",
        SEPTEMBER: "九月",
        OCTOBER: "十月",
        NOVEMBER: "十一月",
        DECEMBER: "十二月",
        LAST_DAY: "最后一天",
        MONTH: "月份",
        MONDAY: "周一(A)",
        TUESDAY: "周二(T)",
        WEDNESDAY: "周三(Y)",
        THURSDAY: "周四(H)",
        FRIDAY: "周五(F)",
        SATURDAY: "周六(R)",
        SUNDAY: "周日(U)",
        INTERVAL: "间隔",
        EVERY: "每",
        DAY_HAPPENS_ONCE: "天发生一次",
        WEEK_HAPPENS_ONCE: "周发生一次",
        DAY: "天",
        DAYS: "天的",
        WEEKS: "周的",
        HAO: "号",
        ON: "在",
        DE: "的",
        RANGE: "范围",
        GATHER: "集合",
        JIA_ADD: "+ 新增",
        CONFIGURATION_NAME: "配置名称",
        BATCH_PARAMETERS: "批量新增参数",
        PLACEHOLDER: "占位符",
        IMPORT: "导入",
        TAGS_MATCHING: "Tags 匹配",
        TEMPERATURE: "温度(℃)",
        WEIGHT: "重量(Kg)",
        ENERGY: "能量(Kj)",
        POWER: "功率(kW)",
        ELECTRIC_QUANTITY: "电量(kWh)",
        FLOW_S: "流量(l/s)",
        FLOW_H: "流量(m³/h)",
        PASCAL: "帕(Pa)",
        KILOPASCAL: "千帕(kPa)",
        COOLING_CAPACITY: "冷量(RT)",
        COOLING_CAPACITY_H: "冷量(RTH)",
        FREQUENCY: "频率(%)",
        LEVEL: "液位(m)",
        LEVEL_C: "液位(cm)",
        WATER_LEVEL: "水位(m)",
        WATER_LEVEL_C: "水位(cm)",
        HIGHT: "高度(mm)",
        HIGHT_C: "高度(cm)",
        HIGHT_D: "高度(dm)",
        HIGHT_M: "高度(m)",
        SPEED: "速度(m/s)",
        SPEED_K: "速度(km/h)",
        SCALE: "比例(%)",
        CURRENT_PERCENTAGE: "电流百分比(%)",
        OPENING: "开度(%)",
        STATUS: "状态",
        COMMOND: "控制指令",
        RENMINBI: "人民币(RMB)",
        DOLLAR: "美元($)",
        BASE_VALUE: "基准值",
        ANALYSIS_VARIABLE: "分析变量",
        ANALYSIS_MODAL: "分析模型",
        MODAL: "模型",
        RESULT: "结果",
        DATA: "数据",
        ONCE: "一次",
        EVERYDAY: "每天",
        WEEKLY: "每周",
        MONTHLY: "每月",
        TAGS_VALUE_NONE: "可选"
    },
    placeholder:{
        SELECT_TIME: "请选择时间",
        SELECT_MONTH_MORE: "请选择月份,可多选",
        SELECT_DAY_MORE: "请选择天,可多选",
        SELECT_FILL_LABEL: "选择或者填写标签",
        SELECT_TIME_INTERVAL: "请选择时间间隔",
        IMPORT_DATA_CLICK_OK: "在文本域中粘贴要导入的数据文件，点击确定",
        SELECT_DATA_SOURCE: "请选择输入源",
        ENTER_PARAMETER_NAME: "请输入参数名称",
        SELECT_PARAMETER_TYPE: "请选择参数类型",
        INPUT_PARAMETER_DEFAULT: "请输入参数默认值",
        FILL_PARAMETER_ANNOTATION: "可填写参数的注释",
        ENTER_PARAMETER_VALUES: "请输入参数值",
        ENTER_PARAMETER_GROUP_NAME: "请输入参数组名称",
        START: "起始",
        END: "结束",
        STEP: "步进",
        COLLECTION_SAMPLE: '集合-示例:"1, 3, 4, 10, \'a\', \'b\'"',
        NAME: "名称",
        ENTER_FORMAT: "请输入配置名称,占位符格式:<#占位符名称#>",
        ENTER_TEMPLATE: "请输入参数模板,占位符格式:<#占位符名称#>",
        SELECT_PATTERN: "请选择图形",
        FORMULA_PLACEHOLDER: "请填写公式内容，符号+,-,*,/,(,),平方和开方均用**加上系数表示,比如平方:**2,开方:**0.5,**1/2,所有运算符号均为英文符号。公式中的计算值，可以拖拽输入参数，或者数据源，或者直接写常数均可!",
        ENTER_CHART_TITLE: "请输入图表标题",
        ENTER_OR_SELECT_UNIT: "请输入或选择单位",
        SELECT_TYPE: "请选择类型",
        ENTER_VALUE: "请输入数值",
        SELECT_CONFIGURATION_METHOD: "请选择配置方法",
        DRAG_INPUT_PARAMETERS: "请拖拽输入参数",
        SELECT_COORDINATE: "请选择坐标轴",
        ENTER_FULL_NAME: "请输入参数的全名",
        ENTER_FAULT_TYPE: "请输入0-1之间的数字，或者2,其中2表示传感器故障，0-1越大表示设备越不健康",
        SELECT_GROUP: "请选择所在组",
        SELECT_SOURCE: "选择故障来源",
        SELECT_FAULT_EFFECT: "请选择故障影响类型",
        SELECT_GRADE: "请选择等级",
        ENTER_EXECUTIVE_ID: "请输入执行人员ID",
        CALCULATE_ENERGY_DAY_TIME: "计算能耗用的天的时间",
        CALCULATE_ENERGY_WEEK_TIME: "计算能耗用的周的时间",
        CALCULATE_ENERGY_MONTH_TIME: "计算能耗用的月的时间",
        CALCULATE_ENERGY_YEAR_TIME: "计算能耗用的年的时间",
        SELECT_UNIT: "请选择单位",
        FILL_DESCRIPTION: "请填写描述",
        FILL_ADVICE: "请填写建议",
        FILL_CHART_TITLE: "请填写图表标题",
        FILL_IN: "填写",
        CONFIG: "配置",
        PRIMARY_AXIS: "主坐标轴",
        DEPUTY_AXIS: "副坐标轴",
        UNNAMED: "未命名",
    },
    message:{
        MODULE: "模块",
        FAIL_SAVE: "保存失败",
        NOT_JSON: "不支持Json数组",
        NOT_JSON_FORMAT: "不支持非Json格式",
        TIME_NOT_EMPTY: "时间不能为空!",
        INCOMPLETE_CONFIGURATION: "配置信息填写不完整!",
        TYPE_NOT_EMPTY: "类型不能为空!",
        CORRECT_TIME: "请输入正确的时间格式!",
        SAVE_SUCCESS: "保存成功",
        NEW_SUCCESS: "新增成功!",
        NEW_FAIL: "新增失败!",
        NETWORK_FAIL: "网络连接失败!",
        DELETE_SUCCESS: "删除成功!",
        DELETE_FAIL: "删除失败!",
        ENABLE_SUCCESS: "启用成功!",
        ENABLE_FAIL: "启用失败!",
        DISABLE_SUCCESS: "禁用成功",
        DISABLE_FAIL: "禁用失败",
        UPDATE_SUCCESS: "更新成功",
        UPDATE_FAIL: "更新失败",
        DATA_EMPTY: "数据为空",
        INPUT_FORMAT_ERROR: "输入格式错误",
        INPUT_SOURCE_EMPTY: "输入源不能为空!",
        PARAMETER_NAME_EMPTY: "参数名称不能为空!",
        PARAMETER_TYPE_EMPTY: "参数类型不能为空!",
        DEFAULT_EMPTY: "默认值不能为空!",
        PARAMETER_VALUE_EMPTY: "参数值不能为空!",
        CONFIGURATION_NAME_EMPTY: "配置名称不能为空!",
        PARAMETER_TEMPLATE_EMPTY: "参数模板不能为空!",
        POINT_EXIST: "该点已存在!",
        FORMAT_FAIL: "格式化失败!",
        CHART_TITLE_EMPTY: "图表标题不能为空!",
        FULL_NAME_EMPTY: "全名不能为空!",
        FAULT_TYPE_EMPTY: "故障类型不能为空!",
        FAULT_GROUP_EMPTY: "故障所在组不能为空!",
        FAULT_EFFECT_EMPTY: "故障影响不能为空!",
        PEOPLE_GROUP_EMPTY: "人员所在组不能为空!",
        FAULT_TEMPLATE_EMPTY: "Fault模板不能为空!",
        EXECUTIVES_EMPTY: "执行人员不能为空!",
        ENERGY_DAY_EMPTY: "计算能耗用的天的时间不能为空!",
        ENERGY_WEEK_EMPTY: "计算能耗用的周的时间不能为空!",
        ENERGY_MONTH_EMPTY: "计算能耗用的月的时间不能为空!",
        ENERGY_YEAR_EMPTY: "计算能耗用的年的时间不能为空!",
        DESCRIPTION_EMPTY: "描述不能为空!",
        SUGGEST_EMPTY: "建议不能为空!",
        SUCCESS_ADD: "成功添加",
        GROUP_CONFIGURATION: "组配置",
        HAS: "有",
        GROUP_TAG_NO_FOUND: "组Tag未找到匹配",
        GROUP_TAG_NO_EQUIPMENTID: "组Tag没有EquipmentId",
        TAG_NO_ENTITYID: "Tag没有EntityId",
        FAIL_GET_TEMPLATE_DATA: "获取模板数据失败",
        PARAMETER_CONFIGURATION_SUCCESS: "参数配置成功!",
        TIME: "时间：",
        ERROR_NULL: "错误: Null",
        ERROR: "错误：",
        NOTHING: "无",
        OUTPUT: "输出：",
        DESCRIPTION: "描述：",
        SUGGESTION: "建议：",
        UNKNOWN_ERROR: "未知错误",
        ERROR_NETWORK_FAIL: "错误：服务器连接失败",
        FORMULA_HAS_CHINESE_SYMBOLS: "公式中含有中文符号!",
        SERIES_IT_SENSOR_PRECISION_EMPTY: "系列检查为是时，传感器精度不能为空!",
        NO_FAULTS: "未发现异常/故障",
        FAULT_GRADE: '错误级别：',
        DETAILS: '详细信息',
        FAULT_NAME: '错误名称：',
        FAULT_DESCRIPTION: '错误描述：',
        FAULT_SUGGESTION: '处理建议：',
        FAULT_CLASSNAME: '设备类型：',
        TAG_TRANSFER_SUCCESS: 'tag导entity成功',
        TAG_TRANSFER_FAIL: 'tag导entity失败'
    },
    title:{
        LOADING: "加载中...",
        EDIT: "编辑",
        PROMPT: "提示",
        CONFIRM_DELETE_STRATEGY: "确认删除这条策略?",
        CONFIRM_UPDATE_TABLE: "确认更新诊断表?",
        DATA_ERROR: "数据错误!",
        PARAMETER_NAME_REPETITION: "参数名称重复",
        MODULE: "模块",
        IMPORT_EMPTY: "导入的内容不能为空!",
        IMPORT_ERROR: "导入的内容中存在错误!",
        PARAMETER_SET_NAME: "参数命名首位不能为数字，且参数名中不能包括算术符号!",
        CONFIGURATION_PARAMETER: "配置参数",
        DELETE_PARAMETER: "删除参数",
        COPY_PARAMETER: "复制参数",
        UP_PARAMETER: "收起参数",
        DOWN_PARAMETER: "展开参数",
        BULK_COPY_PARAMETER: "批量复制参数",
        PROMPT_MESSAGE: "提示信息!",
        KEEP_LEAST_ONE_PARAMETER: "参数配置至少保留一个!",
        CONFIRM_DELETE: "确认删除?",
        DELETE: "删除",
        PARAMETER_GROUP_NAME: "参数组名称",
        MODULE_NAME: "模块名称",
        PARAMETER_NAME: "参数名称",
        PARAMETER_VALUES: "参数值",
        TERM_FILL_ERROR: "有term的信息填写不准确!",
        ENERGY_CONFIGURATION_NUMBERS: "能耗配置参数写入的值只能为数字!",
        DAYS_EMPTY: "天数不能为空!",
        INTERVAL_EMPTY: "间隔不能为空!",
        MONTH_EMPTY: "月份不能为空!",
        TIME_EMPTY: "时间不能为空!",
        UPDATE_FAULT_TABLE: "更新Fault表"
    },
    dataSource: {
        MONTH: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
        WEEK: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
        TITLE: '数据源',
        DS_CONFIG: '数据源配置',
        PROJECT_NAME: '项目名',
        PROJECT_SEARCH: '搜索',
        NUMBER: '编号',
        POINT_NAME: '点名',
        POINT_DESC: '注释',
        POINT_ATTR: '属性',
        SURE: '确认',
        CANCEL: '取消',
        PARAM: '参数',
        USER_NAME: '用户名',
        CUSTOM_NAME: '自定义名',
        FILTER_REPEAT_ITEM: '已过滤重复项',
        CUSTOM_REPEAT: '自定义名重复',
        CUSTOM_NOT_NULL: '自定义名不能为空',
        FORMULA_TIPS: '请输入公式（参数请按照参数列表中参数名输入）：',
        FORMULA_NAME: '公式名',
        FORMULA_VARIABLE_NAME: '变量名',
        FORMULA_VARIABLE_VALUE: '实际值',
        REMOVE_CONFIRM: '确认删除？',
        REMOVE_CONFIRM_TIPS: '已关联',
        REMOVE_RESULT: '已删除',
        WORKSPACE: '工作空间',
        TIME_YESTERDAY: '昨天',
        TIME_TODAY: '今天',
        NO_MATCH_FOUND: '未找到匹配结果',
        NO_SELECT_POINT: '请选择点！',
        GROUP_SELECTED: '已选',
        NO_SELECT_GROUP: '请选择组！',
        INPUT_GROUP_NAME: '请输入组名！',
        ADD_GROUP: '+ 添加分组',
        POINT_TYPE_CUSTOM: '自定义',
        POINT_TYPE_SYSTEM: '系统',
        POINT_TYPE_DEVICE: '设备',
        POINT_TYPE_TYPE: '类型',
        ERROR: '你的数据源已被删除，图表无法生成！',
        ICON_SYS_HVAC: '暖通',
        ICON_SYS_POWER: '动力',
        ICON_SYS_LIGHT: '照明插座',
        ICON_SYS_CRAC: '精密空调',
        ICON_DEV_CHIL: '冷机',
        ICON_DEV_PUMP: '水泵',
        ICON_DEV_COOL: '冷却塔',
        ICON_DEV_AHU: 'AHU',
        ICON_DEV_VAV: 'VAV',
        ICON_DEV_SYS: '系统',
        ICON_TYPE_TEMP: '温度',
        ICON_TYPE_FLOW: '流量',
        ICON_TYPE_FREQ: '频率',
        ICON_TYPE_ONOFF: '启停',
        ICON_TYPE_ELEPOW: '功率',
        ICON_TYPE_ELEPOWMET: '电量表',
        ICON_TYPE_THER: '冷量表',
        ICON_TYPE_PRES: '压力',
        ICON_TYPE_ALARM: '报警',
        ICON_TYPE_CURFLOW: '电流',
        NAV_MINE: '我的',
        NAV_CLOUD: '公共',
        ALREADY_EXIST: '添加已去除重复项',
        ADD_POINT_GROUP: '添加分组',
        ADD_POINT: '添加点',
        ADD_FORMULA: '添加公式',
        RENAME: '重命名',
        REMOVE: '删除',
        DELETE_GROUP_INFO: '请确认是否删除！',
        SEARCH_KEYWORD: '搜索关键字...',
        SEARCH_ALL: '全部',
        SEARCH_HIDE: '隐藏',
        SEARCH_TOWER_SYSTEM: '冷却塔系统',
        SEARCH_ROOM: '房间',
        SEARCH_AHU: '空调箱',
        SEARCH_TOWER: '冷却塔',
        SEARCH_CHILLER: '冷机',
        SEARCH_CONTROLLER: '控制器',
        SEARCH_FCU: '风机盘管',
        SEARCH_GETAWAY: '网关',
        SEARCH_HEAT: '换热器',
        SEARCH_CHARGE: '蓄冰槽',
        SEARCH_SEANSOR: '温度传感器',
        SEARCH_HVAC: '暖通设备',
        SEARCH_DEVICE: '暖通设备',
        SEARCH_VAV: '变风量系统',
        SEARCH_VALVE: '阀门',
        SEARCH_WATER: '水泵',
        TAG_ALL: '全部',
        TAG_EQUIPMENT: '设备',
        TAG_FLOOR: '楼层',
        TAG_ENERGY: '能耗',
    },
    tag: {
        firstPage: {
            LET_YOUR_CHANGE_TAG_PAGE: '该项目首次进行tag标记,系统将为您筛选出关键字字符串。',
            NEXT_STEP: '下一步',
            MANUAL_CLASSIFICATION: '手动分类',
            ONLINE_SEARCH_POINT_ONE: '系统正在为您搜索关键字,共',
            ONLINE_SEARCH_POINT_TWO: '个点,',
            ONLINE_SEARCH_POINT_THREE: ' 已经处理完。'
        },
        tree: {
            RENAME: '重命名',
            DELETE: '删除',
            RULE: '规则',
            ADD: '添加',
            TAG_RECOGNITION: 'Tag识别',
            CONFIRM_TO_DELETE_DIRECTORY: '确认删除目录',
            LESS_THAN_TWO_NODES_MSG: '请选择2个tree的节点再提交',
            FORMAT_SUCCESS: 'tag 格式复制成功!',
            UNCLASSIFIED_CATALOG: '未分类目录'
        },
        edit: {
            NO_DATA_RETURNED: '无数据返回',
            NEW_DIRECTORY_NAME: '新建目录名称',
            DIRECTORY_EMPTY_ERR: '目录名称不可为空',
            SAME_NAME_MERGE: '发现存在相同名称的目录, 将会合并两个目录的点, 是否确认进行重命名并合并?',
            ENTER_NEW_DIRECTORY_NAME: '请输入新目录名称',
            GENERATE: '生成',
            EDIT_THE_CATALOG: '编辑目录',
            THE_AUTO_MATCH_DEVICE_TYPE: '请选择自动匹配设备类型',
            NOT_SAVED_IS_ABANDONED: '新建还未保存,是否放弃保存?',
            DIRECTORY_EMPTY_MSG: '目录名称不能为空',
            SUBDIRECTORY_EMPTY_MSG: '子目录名称不能为空',
            SUBDIRECTORY_MUST_CONTAIN: '子目录名称必须包含{ }',
            NUMBER_ERROR: '{ }必须有规则序号',
            NUMBER_POSITIVE_INTEGER: '规则序号为正整数',
            CAN_NOT_FIND_RULE: '无法找到规则',
            WHETHER: '是否按: ',
            PRESS_THIS_RULE: '这个规则条件进行',
            GENERATE_SUCCESS: '生成成功',
            SELECT: '选中',
            POINTS: '个点',
            RECOMMENDED_TAG: '推荐Tag',
            SUITABILITY: '匹配度',
            REFERENCE: '参考',
            APPLICABLE: '应用',
            TO: '到',
            CREATE: '新建',
            PRODUCE: '生成生成',
            KEYWORDS: '关键字:',
            NAME: '名称',
            REMARK: '注释',
            VALUE: '值'
        },
        inspect: {
            ALL: '全部',
            CATALOGUE: '结构',
            FINISH_CATALOGUE: '完成结构',
            MODIFY_CATALOGUE: '修改结构',
            FORWARD: '向前',
            BACKWARD: '后退',
            ADD: '添加',
            ADD_EMPTY_FILE: '添加空目录',
            CATALOGUE_NAME: '目录: ',
            NEW_CATALOGUE: '新建目录',
            TAG_BRUSH: 'Tag 格式刷',
            TAG_SOURCE: 'Tag 源',
            TAG_TARGET: 'Tag 目标',
            MARK: '标记TAG',
            CHECK: '查看TAG',
            UNMARK: '未标记',
            MARKED: '已标记',
            ROOT_CATALOGUE: '根目录',
            SELECT_ALL: '全选',
            INVERT_SELECTION: '反选',
            COUNTERMAND: '撤回',
            KEYWORDS: '关键词',
            CREATE_CATALOGUE: '创建目录',
            CLASSIFICATION: '分类',
            COMMON: '常用',
            COMMON_TAG: '系统常用tag',
            NAME_OF_CATALOGUE: '目录名称',
            GENERATE_SUBCATALOG: '是否生成子目录',
            YES: '是',
            NO: '否',
            SUBCATALOG_NAME: '子目录名称',
            SUBCATALOG_NAME_RULE_NUMBER: '子目录名称(规则序号)',
            RULE: '规则',
            RESET: '重置',
            RULE_TEST: '规则测试',
            CREATE: '新建',
            FIXED_STRING: '固定字符串',
            FIXED_LENGTH_NUMBER: '固定长度数字',
            UNSET_LENGTH_NUMBER: '不固定长度数字',
            ARBITRARY_STRING: '任意字符串',
            TEST_CONDITION: '测试条件为:',
            WITHIN_THE_RULE: '符合规则',
            AGAINST_THE_RULE: '不符合规则',
            TABLE_CONTENT: '目录:',
            ADD_THE_SUB_DIRECTORY: '添加子目录',
            CAN_DRAG_CHANGE: '可拖拽以下选中的',
            CAN_DRAG_CHANGE_POINT: '个点',
            DEVICE_PARAMETERS: '设备参数',
            SURE_CREATE_DIRECTORY: '是否确认根据关键字创建目录?',
            DIRECTORY_SELECTION: '目录名称选择',
            CREATE_DIRECTORIES: '分别创建目录',
            CUSTOMIZE: '自定义',
            SYSTEM_SEARCH_FOR: '系统为您搜索到',
            SYSTEM_SEARCH_FOR_RESULT: '个关键字用于分类',
            SAME_NUMBER: '位数字',
            MODIFY: '修改',
            ENTER_SEARCH_CONTENT: '请输入搜索内容',
            ERROR_MESSAGE: '错误信息为：',
            SURE_RESTORE_VERSION: '确定还原{0}的版本吗?',
            RESTORE_VERSION: '还原到{0}的版本.',
            ANY_STRING: '任意字符串',
            FIXED_LENGTH_STRING: '固定长度数字',
            NOT_FIXED_STRING: '不固定长度数字',
            TIP_FOR_KEYWORD: '提示: 尚未选择创建目录的关键字. 请按住CTRL键后鼠标点击你想要创建目录的关键字!',
            DIRECTORY_NOT_EMPTY: '目录名称不能为空!',
            RULE_NOT_EMPTY: '规则输入内容不能为空',
            ENTER_RIGHT_NUMBER: '请输入正确的数字'
        },
        rule: {
            RULE_DETAIL: {
                0: '不限定任何内容',
                1: '固定的数字、字母、符号的一种或者组合  如：abc   abc_1  34!a',
                2: '连续的数字位数，如 345 为3位，填写3   29989 为5位数，填写5',
                3: '不确定数字的位数'
            }
        },
        TAG_TYPE: {
            'BRAND': '品牌',
            'EQUIPMENT': '设备',
            'ADJECTIVE': '修饰',
            'COMPONENT': '部件',
            'PHYSICAL QUANTITY': '物理量',
            'CODE': '控制量',
            'CONDITION': '工况',
            'MEDIA': '介质',
            'RELATIONSHIP': '关系',
            'STATISTICS': '统计',
            'COMPARE': '比较',
            'PHYSICAL PROCESS': '物理过程',
            'CONSUMPTION': '用量',
            'INFORMATION': '信息',
            'DIRECTION': '流向',
            'EFFICIENCY': '效率',
            'ENERGY SOURCES': '能源',
            'AREA':'区域'
        }
    },
    confirm: {
        BE_SURE_BACK: '您还有未保存的数据，确定离开吗？',
        BE_SURE_EXPORT: '您还有未保存的数据，确定导出吗？',
        OKTEXT: '确认',
        CANCELTEXT:'取消'
    },
    templateModal:{
        SELECT_FLODER:'请选择文件夹',
        NAME:'模板名称',
        NAME_ERROR:'模板名称不能为空!',
        TITLE: '导出为模板'
    },
    faultManage: {
        CATEGORY: '类型',
        CONSEQUENCE: '影响',
        GRADE: '级别',
        NAME: '名称',
        DESCRIPTION:'详细描述',
        SUGGESTION: '建议',
        LASTMODIFYUSER: '修改人',
        LASTMODIFYTIME: '修改时间',
        OPERATION: '操作',
        USE: '使用',
        SAVE_AS: '另存为',
        DELETE: '删除',
        DELETE_FAILED: '删除失败'
    }
};

