var unitSystem = {
	'1/K': '1/R',
	'cd/m2': 'FOOTLAMBERT',
	'cm': 'Inch',
	'COP': 'EER',
	'g': 'LB',
	'J/K': 'LB',
	'J/kg-K': 'BTU/LB-F',
	'J/m2': 'BTU/SQFT',
	'J/m2-K': 'BTU/SQFT-F',
	'J/m3': 'BTU/Gallons',
	'J/m-K': 'BTU/FT-F',
	'K': 'R',
	'kg': 'LB',
	'kg/hr': 'LB/HR',
	'kg/kW': 'LBS/KW',
	'kg/m2': 'LB/SQFT',
	'kg/m3': 'LB/CUFT',
	'kgS/kg': 'LBS/LB',
	'kW(refrigeration)': 'TON',
	'kW': 'HP',
	'kW/m3/hr': 'KW/CFM',
	'kWh/m2-yr': 'KBTU/SQFT-YR',
	'l/s': 'GPM',
	'liter': 'GAL',
	'liters/min/kW': 'GALLONS/MIN/TON',
	'lux': 'FOOTCANDLES',
	'm': 'FT',
	'm/s': 'FT/Min',
	'm/sec': 'KNOTS',
	'm2': 'SQFT',
	'm2-K/W': 'HR-SQFT-F/BTU',
	'm3': 'CUFT',
	'm3/h-m2': 'CFM',
	'mbar': 'INCH MER',
	'mbar-gage': 'LBS/SQIN-GAGE',
	'mg/kg': 'ppm',
	'MJ': 'Therm',
	'mm-water': 'IN-WATER',
	'N': 'LBf',
	'Pa': 'Millibar',
	'sec/m': '1/KNOT',
	'THERMIES': 'THERMS',
	'units/cm': 'UNITS/Inch',
	'units/liter/min': 'UNITS/GAL/MIN',
	'W': 'BTU/HR',
	'W/K': 'BTU/HR-F',
	'W/m2': 'BTU/HR-SQFT',
	'W/m2-K': 'BTU/HR-SQFT-F',
	'W/m-K': 'BTU/HR-FT-F',
	'W/person': 'BTU/HR/PERSON',
	'Wh/kg': 'BTU/LB'
};


