export default {
  MODULE_NAME: 'Analysis Correlation',
  SORT: 'Rank',
  RELEVANT_PARAMETER: 'Variable',
  WEIGHT: 'Weight',
  R: 'R²',
  DATA_SOURCE: 'Data Sources',
  FITTING_OBJECT: 'Fitting Objects',
  MODEL_DESCRIPTION: 'Model Description',
  DATA_RANGE: 'Data Range',
  SELECTED_DATA: 'Only selected data',
  TIME: 'Time span',
  METHOD: 'Method',
  PARAMETER: 'Variable',
};
