# -*- encoding=utf-8 -*-
__author__ = 'yan'

# global api
# 添加的时候请注意顺序：有相同前缀的越短的排在前，大概一样长的按照字母顺序排
# api_type 1:时间函数，2:发送，3:写入，4:取数，5:能耗计算
mapping_list = \
    [
        {'name':'sys_get_mq_count', 'add_id':0,'api_type':88},

        {'name':'get_act_time', 'add_id':0,'api_type':1},
        {'name':'get_server_time', 'add_id':0,'api_type':1},
        {'name':'time_get_day_begin','add_id':0,'api_type':1},
        {'name':'time_get_week_begin','add_id':0,'api_type':1},
        {'name':'time_get_hour_begin','add_id':0,'api_type':1},
        {'name':'time_get_month_begin','add_id':0,'api_type':1},
        {'name':'time_get_year_begin','add_id':0,'api_type':1},
        {'name':'time_to_string','add_id':0,'api_type':1},
        {'name':'time_from_string','add_id':0,'api_type':1},
        {'name': 'time_get_last_week_begin','add_id':0,'api_type':1},
        {'name': 'time_get_last_day_begin','add_id':0,'api_type':1},
        {'name': 'time_get_last_month_begin','add_id':0,'api_type':1},
        
        {'name':'send_beopmsg', 'add_id':0,'api_type':2},
        {'name':'send_alarm_simple', 'add_id':1,'api_type':2},
        {'name':'create_all_energy_standard_point_by_tag', 'add_id':0,'api_type':9},

        {'name':'get_hours_ago_fault_sent_user', 'add_id':0,'api_type':2},
        {'name':'send_fault_notice_by_email', 'add_id':0,'api_type':2},
        {'name':'send_message_by_email', 'add_id':0,'api_type':2},
        {'name':'send_message_by_app', 'add_id':0,'api_type':2},
        {'name':'send_message_by_mobile', 'add_id':0,'api_type':2},
        {'name':'send_message_by_phonenum', 'add_id':0,'api_type':2},

        {'name':'get_hours_ago_web_report_sent_user', 'add_id':0,'api_type':2},
        {'name':'send_web_report', 'add_id':0,'api_type':2},

        {'name':'set_data', 'add_id':1,'api_type':3},
        {'name':'set_data_algorithm', 'add_id':1,'api_type':3},
        {'name':'set_data_virtual', 'add_id':1,'api_type':3},
        {'name':'set_data_calcpoint', 'add_id':1,'api_type':3},
        {'name':'set_data_time_range', 'add_id':1,'api_type':3},
        {'name':'set_data_history_of_this_point', 'add_id':0,'api_type':3},
        {'name':'set_data_history', 'add_id':0,'api_type':3},
        
        {'name': 'get_third_party_data', 'add_id':1,'api_type':4},
        {'name':'get_data', 'add_id':1,'api_type':4},
        {'name':'get_data_at_time', 'add_id':1,'api_type':4},
        {'name':'get_data_int', 'add_id':1,'api_type':4},
        {'name':'get_data_time_range', 'add_id':1,'api_type':4},
        {'name':'get_his_data_time_range', 'add_id':1,'api_type':4},
        {'name':'get_his_data_with_time', 'add_id':1,'api_type':4},
        {'name':'get_data_string', 'add_id':1,'api_type':4},
        {'name':'get_data_float', 'add_id':1,'api_type':4},
        {'name':'get_data_json', 'add_id':1,'api_type':4},
        {'name':'get_avg_data_of_last_hour', 'add_id':1,'api_type':4},
        {'name':'get_history_data_of_last_hour', 'add_id':1,'api_type':4},
        {'name':'get_status_timeratio_of_last_hour', 'add_id':1,'api_type':4},
        {'name':'get_status_change_of_last_hour', 'add_id':1,'api_type':4},
        {'name':'get_last_update_time_value','add_id':1,'api_type':4},
        {'name':'get_last_value','add_id':1,'api_type':4},
        {'name':'get_last_update_delta_minutes_of_this_point','add_id':0,'api_type':4},
        {'name':'get_data_all_of_project','add_id':0,'api_type':4},
        {'name':'set_clear_data_from_site','add_id':0,'api_type':4},
        {'name':'set_data_from_site','add_id':0,'api_type':4},
        {'name':'copy_data_to_other_project','add_id':0,'api_type':4},
        {'name':'get_lost_time_ratio_of_today', 'add_id':1,'api_type':4},
        {'name':'get_history_data_of_today', 'add_id':1,'api_type':4},
        {'name':'get_storage_by_projId', 'add_id':1, 'api_type':4},
        {'name':'get_fault_notice_count', 'add_id':1, 'api_type':4},

        {'name':'filter_point_only_increase', 'add_id':1,'api_type':4},
        {'name':'filter_point_gt_zero', 'add_id':1,'api_type':4},
        {'name':'filter_point_change_limit_ratio', 'add_id':1,'api_type':4},
        {'name': 'filter_point_energy_consumption', 'add_id':1,'api_type':4},
        {'name':'calc_avg_of_last_hour_nozero', 'add_id':1,'api_type':5},
        {'name':'calc_avg_if_run', 'add_id':1,'api_type':5},
        {'name':'calc_count_in_day', 'add_id':1,'api_type':5},
        {'name':'calc_sum_hour', 'add_id':1,'api_type':5},
        {'name':'calc_sum_day', 'add_id':1,'api_type':5},
        {'name':'calc_sum_last_day', 'add_id':1,'api_type':5},
        {'name':'calc_sum_one_day', 'add_id':1,'api_type':5},
        {'name':'calc_sum_this_week', 'add_id':1,'api_type':5},
        {'name':'calc_sum_one_week', 'add_id':1,'api_type':5},
        {'name':'calc_sum_this_month', 'add_id':1,'api_type':5},
        {'name':'calc_sum_one_month', 'add_id':1,'api_type':5},
        {'name':'calc_sum_this_year', 'add_id':1,'api_type':5},
        {'name':'calc_sum_last_year', 'add_id':1,'api_type':5},
        {'name':'calc_sum_year', 'add_id':1,'api_type':5},
        {'name':'calc_sum_in_points', 'add_id':1,'api_type':5},
        {'name':'calc_power_by_run', 'add_id':1,'api_type':5},
        {'name':'calc_power_by_amp', 'add_id':1,'api_type':5},
        {'name':'calc_power_by_vsd_run', 'add_id':1,'api_type':5},
        {'name':'calc_delta_if_run', 'add_id':1,'api_type':5},
        {'name':'calc_max_in_points', 'add_id':1,'api_type':5},
        {'name':'calc_min_in_points', 'add_id':1,'api_type':5},
        {'name':'calc_max_in_day', 'add_id':1,'api_type':5},
        {'name':'calc_max_in_month', 'add_id':1,'api_type':5},
        {'name':'calc_load_wo_flow', 'add_id':1,'api_type':5},
        {'name':'calc_load_w_flow', 'add_id':1,'api_type':5},
        {'name':'calc_eff_smooth', 'add_id':1,'api_type':5},
        {'name':'calc_compare_same_time_diff_day','add_id':1,'api_type':5},
        {'name':'calc_subtraction_for_given_time','add_id':1,'api_type':5},
        {'name': 'calc_accumulate', 'add_id':1,'api_type':5},
        {'name': 'calc_hourly_delta_of_accum', 'add_id':0,'api_type':5},
        {'name': 'calc_daily_delta_of_accum', 'add_id':0,'api_type':5},
        {'name': 'calc_weekly_delta_of_accum', 'add_id':0,'api_type':5},
        {'name': 'calc_monthly_delta_of_accum', 'add_id':0,'api_type':5},

        {'name':'patch_data_sharp_clock', 'add_id':0, 'api_type':0},
        {'name':'patch_data_sharp_clock_in_time_range', 'add_id':0, 'api_type':0},
        {'name':'patch_data_sharp_clock_every_day', 'add_id':0, 'api_type':0},
        {'name':'patch_data_sharp_clock_every_hour', 'add_id':0, 'api_type':0},
        {'name':'log_str', 'add_id':0, 'api_type':0},
        {'name':'json_to_data', 'add_id':0, 'api_type':0},
        {'name':'json_from_data', 'add_id':0, 'api_type':0},
        {'name':'get_weather_data', 'add_id':0, 'api_type':0},
        {'name':'weather_get_by_id', 'add_id':0, 'api_type':0},
        {'name':'weather_get_by_cityname', 'add_id':0, 'api_type':0},
        {'name':'weather_get_by_cityid', 'add_id':0, 'api_type':0},
        {'name':'aq_get_by_cityname', 'add_id':0, 'api_type':0},
        {'name':'get_work_order_status', 'add_id':0, 'api_type':0},
        {'name':'get_work_order_create_time', 'add_id':0, 'api_type':0},
        {'name':'send_work_order', 'add_id':0, 'api_type':0},
        {'name':'get_work_order_id', 'add_id':0, 'api_type':0},
        {'name':'close_work_order', 'add_id':0, 'api_type':0},
        {'name':'finish_work_order', 'add_id':0, 'api_type':0},
        {'name':'send_work_order_smart', 'add_id':0, 'api_type':0},
        {'name':'reset_work_order_if_open', 'add_id':0, 'api_type':0},
        {'name':'get_pm25_from_web', 'add_id':0, 'api_type':0},
        {'name':'get_pm25_from_web_v2', 'add_id':0, 'api_type':0},
        {'name':'num_join_int64', 'add_id':0,'api_type':4},
        {'name': 'statistics_equipment_intact_rate_pandect', 'add_id': 0, 'api_type': 4},
        {'name': 'statistics_equipment_intact_rate_pandect_v2', 'add_id': 0, 'api_type': 4},
        {'name': 'patrol_complete_rate', 'add_id': 0, 'api_type': 4},
        {'name': 'checkCaseStatus', 'add_id': 0, 'api_type': 0},
        {'name': 'setCaseNoticeTime', 'add_id': 0, 'api_type': 0},
        {'name':'weather_get_from_weather_com', 'add_id':0, 'api_type':0},
        {'name':'send_diagnosis_notice', 'add_id':0,'api_type':6},
        {'name':'send_diagnosis_notice_by_object', 'add_id':0,'api_type':6},
        {'name': 'diagnosis_equipment_chiller', 'add_id':0,'api_type':6},
        {'name': 'diagnosis_equipment_valve', 'add_id':0,'api_type':6},
        {'name': 'diagnosis_equipment_sensor_common', 'add_id':0,'api_type':6},

        {'name': 'diagnosis_equipment_ahu', 'add_id':0,'api_type':6},
        {'name': 'diagnosis_equipment_sensor_t', 'add_id':0,'api_type':6},
        {'name': 'diagnosis_equipment_sensor_p', 'add_id':0,'api_type':6},
        {'name': 'diagnosis_rank_this_day', 'add_id':1,'api_type':6},
        {'name': 'diagnosis_rank_this_week', 'add_id':1,'api_type':6},
        {'name': 'diagnosis_rank_in_time_range', 'add_id':1,'api_type':6},
        {'name': 'get_fault_last_update_time_status', 'add_id':0,'api_type':6},
        {'name': 'stat_fault_by_faultname', 'add_id':1,'api_type':6},
        {'name': 'stat_fault_worktime_by_faultname', 'add_id':1,'api_type':6},
        {'name': 'stat_fault_by_buildingId', 'add_id':1,'api_type':6},
        {'name': 'stat_fault_by_zoneId', 'add_id':1,'api_type':6},
        {'name': 'stat_fault_by_faultname_time', 'add_id':1,'api_type':6},
        {'name': 'get_failure_number_and_failure_time_of_statistics', 'add_id':1, 'api_type': 6},
        {'name': 'get_energy_by_faultNames', 'add_id':1,'api_type':6},
        {'name': 'get_energy_all_by_time', 'add_id':1,'api_type':6},
        {'name': 'get_energy_all_by_time_v2', 'add_id':1,'api_type':6},
        {'name': 'get_energy_by_systemName', 'add_id':1,'api_type':6},
        {'name': 'get_energy_by_systemName_v2', 'add_id':1,'api_type':6},
        {'name': 'get_energylist_by_faultName_order_by_energy', 'add_id':1,'api_type':6},
        {'name': 'get_energylist_by_faultName_order_by_energy_v2', 'add_id':1,'api_type':6},
        {'name': 'get_new_order_num', 'add_id':1,'api_type':6},
        {'name': 'get_new_order_num_v2', 'add_id':1,'api_type':6},
        {'name': 'get_finished_order_num', 'add_id':1,'api_type':6},
        {'name': 'get_finished_order_num_v2', 'add_id':1,'api_type':6},
        {'name': 'get_response_time_avg', 'add_id':1,'api_type':6},
        {'name': 'get_response_time_avg_v2', 'add_id':1,'api_type':6},

        {'name': 'statistics_realtime_fault_algorithm', 'add_id':0,'api_type':6},
        {'name': 'fault_need_check', 'add_id':0,'api_type':6},

        {'name': 'get_fault_data', 'add_id':1,'api_type':6},

        {'name': 'kpi_calc_from_fault', 'add_id':0,'api_type':7},
        {'name': 'kpi_sum', 'add_id':0,'api_type':7},
        {'name': 'kpi_sum_root', 'add_id':0,'api_type':7},

        {'name': 'send_data_to_mqtt', 'add_id':0,'api_type':8},
        {'name': 'send_points_to_mqtt', 'add_id':0,'api_type':8},

        {'name': 'http_post_json', 'add_id':0,'api_type':9},
        {'name': 'http_get_json', 'add_id':0,'api_type':9},
        {'name': 'http_post_form', 'add_id':0,'api_type':9},
        {'name': 'http_post_json_with_cookie', 'add_id':0,'api_type':9},
        {'name': 'http_get_with_cookie', 'add_id':0,'api_type':9},
        {'name': 'http_get_data_text', 'add_id':0,'api_type':9},
        {'name': 'http_get_directly_text', 'add_id':0,'api_type':9},


        {'name': 'air_calc_ts_by_t_rh', 'add_id':0,'api_type':9},
        {'name': 'air_calc_tl_by_t_rh', 'add_id':0,'api_type':9},
        {'name': 'air_calc_h', 'add_id':0,'api_type':9},
        {'name': 'air_calc_x', 'add_id':0,'api_type':9},

        {'name': 'calibration_by_baseline', 'add_id':0,'api_type':9},

        {'name': 'set_data_to_site', 'add_id':0,'api_type':9},

        {'name': 'get_global_storage', 'add_id':0,'api_type':9},
        {'name': 'set_global_storage', 'add_id':0,'api_type':9},
        {'name': 'cloudpoint_exist', 'add_id':0,'api_type':9},
         {'name': 'cloudpoint_create_virtual', 'add_id':0,'api_type':9},
        {'name': 'get_latest_time', 'add_id':0,'api_type':9},

        {'name': 'hisdata_op_remove_history_data', 'add_id':0,'api_type':9},
        {'name': 'hisdata_op_remove_history_data_in_timerange', 'add_id':0,'api_type':9},
        {'name':'remove_mutation_data', 'add_id':0,'api_type':9},
        {'name':'hisdata_op_remove_data_by_value', 'add_id':0,'api_type':9},
        {'name':'update_history_data_replace_value', 'add_id':0,'api_type':9},
        {'name':'hisdata_op_replace_pointname', 'add_id':0,'api_type':9},

        {'name':'get_cloudpoints_list', 'add_id':0,'api_type':9},
        {'name':'get_rawpoints_list', 'add_id':0,'api_type':9},

        {'name':'autotest_check_name_conflict', 'add_id':0,'api_type':9},

        {'name':'invoke_web_service', 'add_id':3,'api_type':9},
        {'name':'get_web_service_info', 'add_id':1,'api_type':9},
    ]