var i18n_resource = {
    error: {
        token: {
            0: '身份凭证有效',
            1: '未登录',
            2: '身份凭证无效',
            3: '身份凭证过期',
            4: '无效的用户'
        },
        relogin: '请重新登录',
        noPermission: '您没有权限访问。'
    },
    energyManagement: {
        overview: {
            ENERGY_MANAGEMENT: '能源管理',
            ENERGY_OVERVIEW: '能耗概览',
            TODAY_ENERGY: '今日能耗',
            MONTH_ENERGY: '本月能耗',
            YEAR_ENERGY: '今年能耗',
            ACCUMULATIVE_ENERGY: '累计能耗量',
            ACCUMULATIVE_COST:'累计电价',
            COMPARISON_YESTERDAY: '相比昨日',
            COMPARISON_LAST_YEAR: '相比去年',
            YOY: '同比',
            MOM: '环比',
            TOTAL_STATISTICS: "能耗统计",
            SUB_ENERGY: "能耗分项",
            SUB_ITEM_CONPARSION: "分项对比",
            HOURLY_ENERGY: '逐时用电',
            DAILY_ENERGY: '逐日用电',
            MONTH_ENERGY: '逐月用电',
            QUERY: '查询',
            NO_POINT_ALERT:'由于缺少点导致部分图表无法显示！',
            MONTH:'月',
            DAY:'日',
            WEEK:'周'
        },
        history: {
            HISTROY_QUERY: '历史查询',
            CYCLE: "周期",
            THIS_YEAR: "本年",
            THIS_MONTH: "本月",
            THIS_DAY: "本日",
            EnergyConsumption: '能耗',
            POWER: '功率',
            FIVE_MIMUTES:'5分',
            HOUR:'时',
            DAY:'日',
            MONTH:'月',
            ADD_YOY: '增加同比',
            YOY_QUERY: '同比查询'
        },
        subTable: {
            METER_QUERY: '分表查询',
            PARAMETERS_ANALYSIS: '参数分析',
            METER_READING: '一键抄表',
            TOTAL_METER: '总电表',
            TODAY_ENERGY: '今日能耗',
            DAILY_ACC_ENERGY: '日累计量',
            MONTHLY_ACC_ENERGY: '月累计量',
            YEARLY_ACC_ENERGY: '年累计量',
            POWER_TRENDY: '昨今功率趋势',
            REAL_AMOUNT: '实际用量',
            METER_TABLE_TIME: '时刻'
        },
        projectBenchmark: {
            PROJECT_STANDARD: '项目对标',
            WATER: "水",
            ELECTRICITY:"电",
            GAS:"煤",
            TOTAL: "总计",
            COUNTRY: "中国",
            BUSSINESS_TYPE: "业务类型",
            CITY: "城市"         
        },
        energyAnalysis:{
            ENERGY_ANALYSIS:'能效分析'
        },
        reports: {
            REPORT: '能耗报表'
        },
        param_config:{
            PARAM_CONFIG:'参数配置',
            CONFIG_SUCCSS: '配置成功',
            CONFIG_FAILED: '配置失败'
        }
    },
    dataSource: {
        MONTH: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
        WEEK: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
        TITLE: '数据源',
        DS_CONFIG: '数据源配置',
        PROJECT_NAME: '项目名',
        PROJECT_SEARCH: '搜索',
        NUMBER: '编号',
        POINT_NAME: '点名',
        POINT_DESC: '注释',
        POINT_ATTR: '属性',
        SURE: '确认',
        CANCEL: '取消',
        PARAM: '参数',
        USER_NAME: '用户名',
        CUSTOM_NAME: '自定义名',
        FILTER_REPEAT_ITEM: '已过滤重复项',
        CUSTOM_REPEAT: '自定义名重复',
        CUSTOM_NOT_NULL: '自定义名不能为空',
        FORMULA_TIPS: '请输入公式（参数请按照参数列表中参数名输入）：',
        FORMULA_NAME: '公式名',
        FORMULA_VARIABLE_NAME: '变量名',
        FORMULA_VARIABLE_VALUE: '实际值',
        REMOVE_CONFIRM: '确认删除？',
        REMOVE_CONFIRM_TIPS: '已关联',
        REMOVE_RESULT: '已删除',
        WORKSPACE: '工作空间',
        TIME_YESTERDAY: '昨天',
        TIME_TODAY: '今天',
        NO_MATCH_FOUND: '未找到匹配结果',
        NO_SELECT_POINT: '请选择点！',
        GROUP_SELECTED: '已选',
        NO_SELECT_GROUP: '请选择组！',
        INPUT_GROUP_NAME: '请输入组名！',
        ADD_GROUP: '+ 添加分组',
        POINT_TYPE_CUSTOM: '自定义',
        POINT_TYPE_SYSTEM: '系统',
        POINT_TYPE_DEVICE: '设备',
        POINT_TYPE_TYPE: '类型',
        ERROR: '你的数据源已被删除，图表无法生成！',
        ICON_SYS_HVAC: '暖通',
        ICON_SYS_POWER: '动力',
        ICON_SYS_LIGHT: '照明插座',
        ICON_SYS_CRAC: '精密空调',
        ICON_DEV_CHIL: '冷机',
        ICON_DEV_PUMP: '水泵',
        ICON_DEV_COOL: '冷却塔',
        ICON_DEV_AHU: 'AHU',
        ICON_DEV_VAV: 'VAV',
        ICON_DEV_SYS: '系统',
        ICON_TYPE_TEMP: '温度',
        ICON_TYPE_FLOW: '流量',
        ICON_TYPE_FREQ: '频率',
        ICON_TYPE_ONOFF: '启停',
        ICON_TYPE_ELEPOW: '功率',
        ICON_TYPE_ELEPOWMET: '电量表',
        ICON_TYPE_THER: '冷量表',
        ICON_TYPE_PRES: '压力',
        ICON_TYPE_ALARM: '报警',
        ICON_TYPE_CURFLOW: '电流',
        NAV_MINE: '我的',
        NAV_CLOUD: '公共',
        ALREADY_EXIST: '添加已去除重复项',
        ADD_POINT_GROUP: '添加分组',
        ADD_POINT: '添加点',
        ADD_FORMULA: '添加公式',
        RENAME: '重命名',
        REMOVE: '删除',
        DELETE_GROUP_INFO: '确认删除数据源组?',
        SEARCH_KEYWORD: '搜索关键字...',
        TAG_ALL: '全部',
        TAG_EQUIPMENT: '设备',
        TAG_FLOOR: '楼层',
        TAG_ENERGY: '能耗'
    },
}