var i18n_resource = {
    error: {
        token: {
            0: 'Valid lisence',
            1: 'Login error',
            2: 'Invalid lisence',
            3: 'Expired lisence',
            4: 'Invalid account'
        },
        relogin: 'Please relogin',
        noPermission: 'You don\'t have permission to access'
    },
    energyManagement: {
        overview: {
            ENERGY_MANAGEMENT: 'Energy Manage',
            ENERGY_OVERVIEW: 'Overview',
            TODAY_ENERGY: 'Accumulated Today',
            MONTH_ENERGYS: 'Accumulated Month',
            YEAR_ENERGY: 'Accumulated Year',
            ACCUMULATIVE_ENERGY: 'Power Accum',
            ACCUMULATIVE_COST:'Cost Accum',
            COMPARISON_YESTERDAY: 'to YTD',
            COMPARISON_LAST_YEAR: 'to last year',
            YOY: 'YoY',
            MOM: 'MoM',
            TOTAL_STATISTICS: "Energy Use Breakdown",
            SUB_ENERGY: "Breakdown",
            SUB_ITEM_CONPARSION: "Ranking",
            HOURLY_ENERGY: 'Hourly (kWh)',
            DAILY_ENERGY: 'Daily (kWh)',
            MONTH_ENERGY: 'Monthly (kWh)',
            QUERY: 'Query',
            NO_POINT_ALERT:'Some chart maybe crash because of lost of special data points!',
            MONTH:'Month',
            DAY:'Day',
            WEEK:'Week'            
        },
        history: {
            HISTROY_QUERY: 'History',
            CYCLE: "Cycle",
            THIS_YEAR: "This year",
            THIS_MONTH: "This month",
            THIS_DAY: "Today",
            EnergyConsumption: 'Consumption',
            POWER: 'Power',
            FIVE_MIMUTES:'5m',
            HOUR:'h',
            DAY:'d',
            MONTH:'M',
            ADD_YOY: 'Add to comparison',
            YOY_QUERY: 'Comparison'
        },
        subTable: {
            METER_QUERY: 'Meters',
            PARAMETERS_ANALYSIS: 'Overview',
            METER_READING: 'Records',
            TOTAL_METER: 'Parameters',
            TODAY_ENERGY: 'Consumption',
            DAILY_ACC_ENERGY: 'Daily Accum',
            MONTHLY_ACC_ENERGY: 'Monthly Accum',
            YEARLY_ACC_ENERGY: 'Yearly Accum',
            POWER_TRENDY: 'Trends',
            REAL_AMOUNT: 'Power',
            METER_TABLE_TIME: 'Time'
        },
        projectBenchmark: {
            PROJECT_STANDARD: 'Benchmark',
            WATER: "Water",
            ELECTRICITY:"Electricity",
            GAS:"Gas",
            TOTAL: "total",
            COUNTRY: "China",
            BUSSINESS_TYPE: "Business",
            CITY: "City"  
        },
        energyAnalysis:{
            ENERGY_ANALYSIS:'Energy Analysis'
        },
        reports: {
            REPORT: 'Report'
        },
        param_config:{
            PARAM_CONFIG:'Params Config',
            CONFIG_SUCCSS: 'Config Success',
            CONFIG_FAILED: 'Config Failed'            
        },
    },
    dataSource: {
        MONTH: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'July', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], //缺
        WEEK: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], //缺
        TITLE: 'Data source',
        DS_CONFIG: 'Data configuration',
        PROJECT_NAME: 'Project Name',
        PROJECT_SEARCH: 'Search',
        NUMBER: 'No.',
        POINT_NAME: 'Point name',
        POINT_DESC: 'Notes',
        POINT_ATTR: 'Attribute',
        SURE: 'Confirm',
        CANCEL: 'Cancel',
        PARAM: 'Parameter',
        USER_NAME: 'Account',
        CUSTOM_NAME: 'Custom name',
        CUSTOM_REPEAT: 'Duplicate customized name',
        CUSTOM_NOT_NULL: 'Customized name is required',
        FILTER_REPEAT_ITEM: 'Filter duplicates',
        FORMULA_TIPS: 'Please enter the formula ( according to variable list ):',
        FORMULA_NAME: 'Formula Name',
        FORMULA_VARIABLE_NAME: 'Variable',
        FORMULA_VARIABLE_VALUE: 'Point name',
        REMOVE_CONFIRM: 'Ensure remove ?',
        REMOVE_CONFIRM_TIPS: 'It relate',
        REMOVE_RESULT: 'deleted.',
        WORKSPACE: 'Workspace',
        TIME_YESTERDAY: 'Yesterday',
        TIME_TODAY: 'Today',
        NO_MATCH_FOUND: 'No matches found',
        NO_SELECT_POINT: 'Please select points !',
        GROUP_SELECTED: 'Selected',
        NO_SELECT_GROUP: 'Please select group !',
        INPUT_GROUP_NAME: 'Please input group name !',
        ADD_GROUP: '+ Add group',
        POINT_TYPE_CUSTOM: 'Custom',
        POINT_TYPE_SYSTEM: 'System',
        POINT_TYPE_DEVICE: 'Equipment',
        POINT_TYPE_TYPE: 'Type',
        ERROR: "Your Data Points has been removed, the chart can't render!",
        ICON_SYS_HVAC: 'HVAC',
        ICON_SYS_POWER: 'Power system',
        ICON_SYS_LIGHT: 'Lighting',
        ICON_SYS_CRAC: 'CRAC',
        ICON_DEV_CHIL: 'Chiller',
        ICON_DEV_PUMP: 'Pump',
        ICON_DEV_COOL: 'Cooling tower',
        ICON_DEV_AHU: 'AHU',
        ICON_DEV_VAV: 'VAV',
        ICON_DEV_SYS: 'System',
        ICON_TYPE_TEMP: 'Temperature',
        ICON_TYPE_FLOW: 'Flow rate',
        ICON_TYPE_FREQ: 'Frequency',
        ICON_TYPE_ONOFF: 'On Off',
        ICON_TYPE_ELEPOW: 'Electrical power',
        ICON_TYPE_ELEPOWMET: 'Electrical power meter',
        ICON_TYPE_THER: 'Thermal meter',
        ICON_TYPE_PRES: 'Pressure',
        ICON_TYPE_ALARM: 'Alarm',
        ICON_TYPE_CURFLOW: 'Current flow',
        NAV_MINE: 'Mine',
        NAV_CLOUD: 'Cloud',
        ALREADY_EXIST: 'It have removed existed item(s).',
        ADD_POINT_GROUP: 'add group',
        ADD_POINT: 'add point',
        ADD_FORMULA: 'add formula',
        RENAME: 'rename',
        REMOVE: 'remove',
        DELETE_GROUP_INFO: 'Please confirm whether to delete?',
        SEARCH_KEYWORD: 'Enter keywords',
        TAG_ALL: 'All',
        TAG_EQUIPMENT: 'Equipment',
        TAG_FLOOR: 'Floor',
        TAG_ENERGY: 'Energy'
    },
}