export default {
  MODULE_NAME: 'Data Source',
  TITLE_ADD: 'Add',
  EXPORT_TO_EXCEL: 'Export',
  IMPORT_TO_EXCEL: 'Import',
  BULK_MANAGE: 'Batch',
  NEW_POINT: 'Add',
  DELETE_POINT: 'Remove',
  RENAME: 'Rename',
  ADD: 'Add',
  EDIT: 'Edit',
  PARAMETERS_OF_THE_SAMPLE: 'Edit Variables',
  DESCRIPTION: 'Description',
  THE_SAMPLE_POINTS: 'Sample Points',
  TAG: 'Tag',
  PARAMETER_NAME: 'Variable Name',
  POINT_VALUE: 'Point',
  REAL_TIME_VALUE: 'Value',
  ANNOTATION: 'Annotation',
  IS_COMPLETE: 'Filling the missing data',
  OK: 'OK',
  CANCEL: 'Cancel',
  TOOLTIP: 'Tooltip',
  SURE_DELETE_PARAM: 'Do you want to remove the variable group "{num}"?',
  PARAM_GROUP_NAME_BEEN_USED: 'This name ( {num} ) has been used! ',
  PLACEHOLDER_NO_DESCRIPTION: 'No description',
  WARNING: 'Warning',
  SURE_DELETE_PARAM_POINT: 'Do you want to reomve the variable named "{num}"?',
  PARAM_NAME_NOT_EMPTY: 'Variable names cannot be empty and must be unique!',
  PARAM_NAME_BEEN_USED: 'This name ( {name} ) has been used! ',
  HISTORY: 'History',
  POINT_ERROR: 'Error!',
  POINT_FORMAT: 'Format:@projectId|pointName',
  UNSUPPORTED_FILE_FORMAT: 'Unsupported file format',
  PROJECT_NAME: 'Project Name',
};
