var i18n_resource = {
    echarts: {
        MARK: 'Mark',
        MARKUNDO: 'Undo mark',
        MARKCLEAR: 'Clear mark',
        DATAZOOM: 'Zoom',
        DATAZOOMRESET: 'Reset zoom',
        DATAVIEW: 'Data view',
        CLOSE: 'Close',
        REFRESH: 'Refresh',
        LINE: 'Switch to line chart',
        BAR: 'Switch to bar chart',
        STACK: 'Stack view',
        TILED: 'Tiled view',
        FORCE: 'Force',
        CHORD: 'Chord',
        PIE: 'Pie',
        FUNNEL: 'Funnel',
        REDUCTION: 'Restore',
        SAVE_AS_PICTURE: 'Save as picture',
        SAVE: 'Save',
        toolbox: {
            magicType: {
                line: 'for line charts',
                bar: 'for bar charts',
                stack: 'for stacked charts',
                tiled: 'for tiled charts'
            },
            saveAsImage: 'save as image',
            restore: 'restore',
            dataView: 'data view',
            dataZoom: {
                zoom: 'area zooming',
                back: 'restore area zooming'
            },
            brush: {
                rect: 'Rectangle selection',
                polygon: 'Polygon selection',
                lineX: 'Horizontal selection',
                lineY: 'Vertical selection',
                keep: 'Keep previous selection',
                clear: 'Clear selection'
            }
        }
    },
    admin: {
        login: {
            PANE_TITLE: "Log in",
            PANE_CHECKBOX_REMEMBER: "Remember",
            PANE_CHECKBOX_REMEMBER2: "Remember",
            PANE_PLACEHOLDER_ACCOUNT: "Please enter user name",
            PANE_PLACEHOLDER_PWD: "Please enter your password",
            LOG_IN_FAILED: "Login failed",
            LOG_IN_TOKEN_EXPIRED: 'Login token expired, please relogin',
            LOG_IN_EMPTY: "Please enter your username and password",
        },
        welcom: {
            start: {
                TITLE: "Start",
                NEW_PROJECT: "New project ...",
                IMPORT_PROJECT: "Import project ...",
            },
            yourProj: {
                TITLE: "Project",
                DELETE: "Delete",
                TOP: "Sticky",
                EXPORT: "Export",
                EDIT_AUTH: 'Edit Project Authority',
                EDITE_PRO: 'Edit'
            },
            newProj: {
                ADD_PROJECT: "Add items",
                EDIT_PROJECT: "Edit items",
                PROJECT_NAME: "Project name:",
                PROJECT_CHINESE_NAME: "Project name in Chinese:",
                PROJECT_ENGLISH_NAME: "Project name in English:",
                ADD: "New",
                ADD_ONLINE: 'Generate online project',
                EIDT_ONLINE: "Edit online project",
                CANSEL: "Cancel",
                PROJECT_NAME_NEW_PLACEHOLDER: 'Please enter the project name',
                PROJECT_NAME_PLACEHOLDER: "Enter a project name",
                PROJECT_CHINESE_NAME_PLACEHOLDER: "Please enter the project name in Chinese",
                PROJECT_ENGLISH_NAME_PLACEHOLDER: "Please enter the project name in English",
                LOG_ADD: "Project name can not be empty!",
                LOG_SAME_NAME: 'The project already exists'
            },
            deleteProj: {
                DELETE_PROJECT: "Delete project",
                CONFIRM_INFO: "Please confirm whether to delete the project?",
                CONFIRM_INFO_TIP: "Please enter a password",
                SURE: "Confirm deletion",
                CANCEL: "Cancel",
                DELETE_TITLE: "Delete project",
                PASSWORD: "Password:",
                PROJECT_ENGLISH_NAME: "Project name in English:",
                PASSWORD_PLACEHOLDER: "Please enter your password",
                PROJECT_ENGLISH_NAME_PLACEHOLDER: "Please enter the Project name in English",
                OK: "OK",
            },
            importProjectModal: {
                TITLE: "Import online project",
                PROJECT_LIST_LABEL: "List of online projects",
                CONFIRM_IMPORT: "Confirm import",
                CANCEL: "Cancel"
            },
            addByTpl: {
                APPLY_TEMP: 'Template',
                TEMP_NAME: 'template name',
                PAGE_NAME: 'page name',
                REPLACE_STR: 'the replace string',
                REPLEASE_AS: 'Replace as',
                SURE: 'OK',
                BATCH_PLACE: 'Batch placeholder',
                BATCH_PAGE: 'Batch page name',
                PAGE_NAME_EG: 'e.g., myPage',
                REPLACE_STR_EG: 'e.g., chiller01',
                REPLEASE_AS_EG: 'e.g., chiller02',
                BATCH_PLACE_EG: '{x:["1","a"]} or {x: {min: 2, max: 10, step: 1}}',
                BATCH_PAGE_EG: 'e.g., myPage<#x#>',
                SAVE_TEMP_FAIL: 'Failed to save template.',
                TEMP_DATA_FAIL: 'The template\'s data is illegal.',
                PLACEHOLDER_NONE: 'Please enter the palceholder for batch adding pages.',
                PAGE_NAME_NONE: 'Please enter the name of this page.',
                BATCH_PAGE_NAME_CFG_NONE: 'Please fill in batch page name.',
                PAGESCREEN_ADD_SUCCESS: 'PageScreen added successfully.',
                APPLICATION_TEMPLATE: 'Application template',
                TEMPLATE_PARAMETER_CONFIG: 'Template parameter configuration',
                NAME_PARAMETER_CONFIG: 'Naming parameter configuration',
                PARAMETER_NAME: 'Parameter Name',
                TYPE: 'Type',
                VALUE: 'Value',
                DESCRIPTION: 'Description',
                LAST_STEP: 'Last step',
                NEXT_STEP: 'next step',
                ACCOMPLISH: 'Accomplish'
            }
        },
        navIndex: {
            LINK_LANGUAGE: "Language"
        },
        templateTooltip: {
            DRAGE_INFO: "The target folder is the child of the selected folder!",
            UNKNOWN: "unknown",
            CREATEROR: "creater:",
            CREATE_TIME: "time:",
            NAME: "name:",
            SIZE: "size:",
            SPEED: "speed:",
            ONE_SECOND: "One second",
            FRAME: "frame",
            TYPE: "type:",
            PREVIEW: "preview",
            TEMPLATE_IS_YOUR: "The template you selected contains template not created by yourself!",
            ADMIN_CAN_OPERATION: "Only admin can operate!",
            NO_PAGE_OPRATE: "No pages can be operated!",
            NO_PROJECT_OPRATE: "No project can be operated!",
            CONFIRM_EMPTY: "Are you sure to empty the Recycle?",
            CONFIRM_INSTORE: "Are you sure to restore all items?",
            CONFIRM_SELECTED_INSTORE: "Are you sure to restore selected items?",
            CONFIRM_SELECTED: "Are you sure to empty the selected items?"
        },
        projectCreator: {
            REGIST_STEP1_TITLE: 'Create Project',
            REGIST_STEP1_TITLE_2: 'Modify Project',
            REGIST_STEP2_TITLE: 'Upload Data',
            REGIST_PREV_STEP_TITLE: 'Prev',
            REGIST_NEXT_STEP_TITLE: 'Next',
            REGIST_SUBMIT_TITLE: 'Submit',
            PANE1_TITLE: 'Welcome to the Beop system. If you are visiting for the first time, please follow the guide to create project. Wish you have a pleasant experience.',
            PANE1_FORM_ITEM1_LABEL: 'Project Code',
            PANE1_FORM_ITEM1_PLACEHOLDER: 'Please enter your project code.',
            PANE1_FORM_ITEM1_TIP: 'Code criteria: only letters and numbers are allowed.',
            PANE1_FORM_ITEM2_LABEL: 'Native Name',
            PANE1_FORM_ITEM2_PLACEHOLDER: 'Please enter native name of your project .',
            PANE1_FORM_ITEM2_TIP: 'you can defined the native name.',
            PANE1_FORM_ITEM3_LABEL: 'English Name',
            PANE1_FORM_ITEM3_PLACEHOLDER: 'Please enter your project english name.',
            PANE1_FORM_ITEM3_TIP: 'name criteria: only letters and numbers are allowed.',
            PANE1_FORM_ITEM4_LABEL: 'Project Address',
            PANE1_FORM_ITEM4_PLACEHOLDER: 'Please choose your project address on the map.',
            PANE1_FORM_ITEM4_TIP: 'Address criteria: Manually changing is not supported.Please choose it on the map.',
            PANE1_FORM_ITEM5_LABEL: 'Project Preview Image (click the image below to modify it)',
            PANE2_TITLE: 'OK! You could upload your project data now, or skip this step and upload later.',
            PANE2_FORM_ITEM1_LABEL: 'Please choose your project data file on your local system (you can also upload a file by dragging it to this page):',
            PANE2_FORM_ITEM1_TIP1: '(Choose file)',
            PANE2_FORM_ITEM1_TITLE: 'Upload File',
            PANE2_FORM_ITEM1_TIP2: 'File criteria：.csv/.xls/.xlsx file are currently supported, please check it before upload.',
            PANE2_TABLE_TITLE: 'Data Sample',
            ERROR_NOT_EMPTY: 'The project name cannot be empty.',
            ERROR_WRONG_CRITERIA: 'Only letters and numbers are allowed.',
            ERROR_EXIST_NAME: 'Project name already exists. Enter otehr name plaese.',
            ERROR_NOT_CHOOSE_ADDRESS: 'Please choose your project address on the map.',
            CHANGE_MAP_TO_AMAP: 'Switch to AMap.',
            CHANGE_MAP_TO_GOOGLE: 'Switch to Google Map.',
            CHANGE_MAP_ERROR: 'Switch Map Error ! no map instance over there.',
            PJ_REALITY_VALUE_TIPS_DEFAULT: "Note: Please enter the correct project identification",
            PJ_REALITY_VALUE_TIPS_SUCCESS: "Project identification is correct.",
            PJ_REALITY_VALUE_TIPS_FAILED: "Please enter the correct Project identification.",
            PJ_REALITY_VALUE_TIPS_SERVER_ERROR: "Server error:Fail to detect real project identification.",
            PJ_REALITY_VALUE_TIPS_PLACEHOLDER: "Please enter the correct Project identification.",
            PJ_REALITY_VALUE_TIPS_TITLE: "Project identification",
            PJ_TIME_FORMAT: "Time format",
            PJ_TYPE_IDENTIFICATION: 'Project type and identification',
            REAL_PROJECT: 'Real project',
            VIRTUAL_PROJECT: 'Virtual project',
            REAL_DATA: 'Realtime data identification',
            HISTORICAL_DATA: 'History data identification',
            PJ_REAL_DATA_IDENTIFICATION_IS_RIGHT: 'Realtime data identification is correct',
            ENTER_PROJECT_DATA: "Please enter the Project Code",
            ENTER_PROJECT_HISTORY_DATA: "Please enter the historical data identification",
            REAL_TIME_DATA_USED: "Real-time data identification {0} is used",
            DATA_IDENT_NOT_EXIST: "The Project Code {0} does not exist.",
            PROJECT_IDENT_USED: "Project Code {0}  is used by other project",
            IDENT_ILLEGAL: "Project Code is not legal and can not be submitted",
            DATA_FULL_NOT_SUBMIT: "Real-time data identification is used and can not be submitted"
        }
    },
    workflow: {
        memberSelected: {
            TITLE: "Please Select Members",
            TITLE1: "Please See Members",
            INPUT_INFO: "Please Enter Members Name To Search",
            ALL: 'All',
            MEMBER_SELECTED: 'Members',
            INFO_READONLY: 'Only view, can not choose'
        },
        pageInfo: {
            TITLE_MAIN_PAGE: "Project",
            TITLE_WO_DYNAMIC: "Status",
            TITLE_WEEK_REPORT: "Weekly report",
            TITLE_TEAM: "Team",
            TITLE_EFFIC: "Efficiency",
            TITLE_SCHEDULER: "Schedule",
            TITLE_WO_MY: "My order",
            PEOPLE_SEL: "User filter",
            GROUP: "Group",
            MEMBER: "Member",
            ALL_MEMBER: "All members",
            NEWS: "Latest status",
            LOAD_MORE: "Load more",
            LOAD_COMPLETE: 'Load complete',
            SET: "Set",
            PROJECT_TEAM: 'Project team',
            STAFFING: 'Staffing',
            WORKFLOW_MANAGE: 'Workflow Management'
        },
    },
    dataSource: {
        ADD_GROUP: "+ Add group",
        ADD_POINT_GROUP: "Add group",
        ADD_POINT: "Add point",
        ADD_FORMULA: "Add formula",
        RENAME: "Rename",
        REMOVE: "Delete"
    },
    observer: {
        observerScreen: {
            DIALOG_TITLE: "Detail",
            TEXT_EDITOR_CONFIRM: 'Confirm',
            TEXT_EDITOR_SEND_SUCCESS: 'Data set successfully',
            TEXT_EDITOR_SEND_FAIL: 'Data set failed',
            TEXT_ADD_TO_DATASOURCE: 'Add To Datasource'
        }
    },
    toolBox: {
        TITLE: "Module",
        modal: {
            MOBILE_CHART: "Mobile Chart",
            HIS_CHART: "Historical figure",
            HIS_CHART_ENERGY_LINE: "History histogram (year / month / week)",
            HIS_CHART_ENERGY_BAR: "Historical energy bar graph",
            HIS_CHART_YEAR_LINE: "Year history line chart",
            HIS_CHART_YEAR_BAR: "Year history bar graph",
            HIS_CHART_ANALYSE: 'History Data Analysis',
            REAL_TIME_CHART: "realtime charts and graphs",
            REAL_TIME_CHART_PIE_ENERGY: "Pie charts",
            REAL_TIME_CHART_PIE_DATAROOM: "Breakdown of energy consumption data rooms pie",
            REAL_TIME_CHART_LINE_OUTDOOR: "Curves/Bar",
            REAL_TIME_CHART_LINE_PUE: "Pue trend",
            REAL_TIME_CHART_GAUGE: "Dashboards",
            REAL_TIME_CHART_BAR_ENERGY: "Bar charts",
            REAL_TIME_CHART_LINE_ENERGY: "Sub-energy line chart",
            REAL_TIME_CARBON_FOOTPRINT: "Carbon footprint emissions",
            REAL_TIME_WEATHER: "Weather trend",
            REAL_TIME_ENERGY_SAVE_RATE: "Saving rate",
            REAL_TIME_COAL_SAVE_TOTAL: "Cumulative savings of standard coal",
            REAL_TIME_CO2_SAVE_TOTAL: "Cumulative savings co₂ emissions",
            REAL_TIME_KPI_CHART: "Kpi dashboard",
            REAL_TIME_BAR: "Real-time bar graph",
            OBSERVER: "Configuration page",
            REAL_TIME_PREDICT_POINT_LINE: "Real-time prediction line chart",
            TRANSIT: "Data analysis",
            MULTIPLE: "Combined",
            NOTE: "Notes",
            WHIRLWIND_CHART: "Fig whirlwind",
            RANK_CHART: "Top figure",
            MIX: "Assembled",
            Monitor: 'Monitor Page',
            DATA_ITEM_MONITOR: 'Data Item Monitor',
            HIS_DATA_QUERY: 'History Data Query',
            REAL_MONITOR_GAUGE: 'Realtime Monitor Gauge',
            MODAL_HTML: "Html module",
            MSG_MIX_NOT_ALLOW_TO_MIX: "Combination charts can not drag combination chart",
            MSG_BLIND_NOT_TO_MIX: 'Blinds can not be dragged into a combination chart',
            MSG_BLIND_NOT_TO_KPI: 'Blinds can not be dragged into the KPI module',
            MSG_BLIND_NOT_TO_REPORT: 'Blinds can not be dragged into the report section',
            MSG_BLIND_NOT_TO_BLIND: 'Blinds can not be dragged into the blinds',
            CUSTOM_CHART: "Custom fig.",
            POINT_KPI: "Kpi exclusive edition",
            REPORT_CHAPTER: "Reports section",
            MSG_KPI_NOT_ALLOW_TO_MIX: "Kpi exclusive version can not be dragged into a combination of fig.",
            INTERACT_CHART: "Interactive trend",
            APP_CHART: 'APP',
            APP_GAUGE_CHART: 'APP Gauge',
            APP_BUTTON: 'APP Button',
            APP_HISTORY_QUERY: 'APP History Query',
            APP_DIAGNOSTIC_RANKING: 'APP Diagnostic Ranking',
            APP_MONTH_HISTORY_QUERY: 'APP Month History Query',
            APP_BLIND: 'APP Blind',
            KPI_STRUCT: 'KPI Item Evaluation',
            APP_KPI_COLLECT: 'APP KPI Overview',
            DATA_MONITOR_LIST: 'Data Munitor List',
            APP_PIE: 'App Pie',
            DIAGNOSIS_PANEL: 'Diagnosis Panel',
            DIAGNOSIS_SUMMARY: 'Diagnosis Summary',
            KPI_OVERVIEW: 'KPI Overview',
            REALTIME_WEATHER: 'Realtime Weather',
            CUMULANT_CHART: 'Cumulant Chart',
            SLIDER: 'Slider Panel',
            COLD_HOT_AREA_SUMMARY: 'Cold Hot Area Summary',
            EQUIPMENT_PERFECT_RATE: 'Equipment Perfect Rate',
            WORK_ORDER_STATISTICS: 'Work Order Statistics',
            PRIORITY_HAADLING_FAULT_LIST: 'Priority Handling Fault List',
            ENERGY_TREND_ANALYSIS: 'Energy Trend Analysis',
            EQUIPMENT_RATE_AND_HISTORY_DATA: 'Equipment Perfect Rate(new)',
            INTERACTIVE_TREND_CHART: 'Interactive Trend Chart(new)',
            PRIORITY_HAADLING_FAULTS: 'Priority Handling Fault List(new)',
            REAL_TIME_AND_HISTORY_CHART: 'Real Time And History Chart',
            MIX_DISPLAY_MODAL: 'combination chart display mode',
            MIX_SLIDER: 'combination chart slide',
            NO_SLIDER_INFO: '(0 or blanket means no slide)',
            BACKGROUND_COLOR: 'background color',
            NULL: 'none',
            WHITE: 'white',
            BLOCK: 'black',
            BLUE: 'blue',
            GREEN: 'green',
            CUSTOM: 'customize'
        },
        modal_public: {
            NO_DATA: 'No Data',
            NO_FAULT: 'No Fault',
            DETAILS: 'Details'
        },
        APP_HISTORY_QUERY: {
            TITLE: 'History Query',
            CONFIG_BTN: 'Config',
            START_TIME: 'Start Time',
            END_TIME: 'End Time',
            PERIOD: 'Period',
            SEARCH: 'Search',
            MONTH: 'one month',
            DAY: 'one day',
            HOUR: 'one hour',
            MINUTE: 'five minutes',
            MINUTE_ONE: 'one minute'
        },
        COLD_HOT_AREA_SUMMARY: {
            OVER_HOT: 'Overheat',
            OVER_COLD: 'Overcool',
            STANDARD: 'SP. '
        },
        WORK_ORDER_STATISTICS: {
            NEW_WORK: 'New WO',
            REPONSE_TIME: 'Response',
            COMPLETE: 'Complete'
        },
        modalInteractive: {
            START_TIME: 'Start Time',
            END_TIME: 'End Time',
            QUERY: 'Query',
            DATASROUCE_DRAG: 'Please drag datasource point from the panel left.'
        },
        modal_PRIORITY_HAADLING_FAULTS: {
            DETAIL: 'Detail',
            ALL_FAULTS: 'All Faults'
        },
        EQUIPMENT_RATE_AND_HISTORY_DATA: {
            WEEK: 'week',
            MONTH: 'month',
            YEAR: 'year'
        }
    },
    dashboard: {
        modalHistoryChart: {
            MAXIMUM: "Max",
            MINIMUM: "Min",
            EnergyConsumption: "Energy consumption"
        },
        modalWeather: {
            REAL_TIME_TEMPERATURE: "Real-time temperature"
        },
        modalConfig: {
            POINT_DRAG_TIP: "Please drag data points here ......",
            ERR: "Limit reached!"
        },
        resize: {
            ERR1: "Please enter a value smaller than upper limit!",
            ERR2: "Please enter a value bigger than lower limit!",
            ERR3: "Enter the value must be a number, please check the format!"
        },
        show: {
            TITLE_TIP: "Please enter a title",
            TITLE: "Title",
            SELECT_LINK: "Select link",
            TYPE: "Category",
            LINK_TO: "Link to",
            DESC: "Description",
            DESC_TIP: "Please add description here"
                // WIKI_ID: "Wikiid",
                //POP_ID: "Popid"
        },
        modalPointKPI: {
            PASS: "Qualified",
            UNPASS: "Not qualified",
            MONTH: "Month",
            QUARTER: "Quarter"
        },
        modalJumpPages: {
            IMPORT_PAGE: "Import to data source",
            POINT_LIST: "Data name",
            GROUP_LIST: "Select data source",
            SUCCESS_TIPS: "Success, whether to jump to the Data Analysis?",
            FAIL_TIPS: "Export failed!",
            NO_FIT_POINT: "There is no data point to import",
            SURE: "OK and jump",
            CANCEL: "OK",
            NEW_GROUP: "New data source",
            SELECT_ALL: "Select all",
            SELECT_REVERT: "Unselected",
            NEW_DS_NAME: "New data source name",
            PARAM_INTRO: 'Reference variable',
            DATA_EXIST: 'The data source already exists in the list!',
            NO_LABLE: 'Custom tag not found:'
        },
        modalHistoryDataAnalyze: {
            DRAG_TIP_FOR_CHART: 'Drag dataSource here for chart',
            DATE_CONFIRM: 'Confirm',
            DATE_CANCEL: 'Cancel',
            HISTORY_DATA: 'History Data',
            POINT_EXIST_TIP: 'DataSource Exist'
        },
        modalKPIStruct: {
            NO_DATA_TEMP: 'Data not available at present'
        }
    },
    analysis: {
        TITLE: "Data analysis",
        PANE_POINTS_ALL_TITLE: "All points (click to select)",
        PANE_POINTS_SELECTED_TITLE: "Points selected (click to delete)",
        MARK_SELECTED: "Selected",
        PANE_ADD_NOTE: "New notes",
        BACK_TO_HOMEPAGE: "Return to main menu",
        PANE_CONFIG: "Configure",
        PANE_FULL_SCREEN: "Full screen",
        modalType: {
            TENDENCY: "Trend",
            STACK: "Area chart",
            SPECTRUM: "Spectrogram",
            SCATTER: "Scatterplot",
            HISTORY_COMPARE: "Year history bar graph",
            HISTORY_COMPARE_LINE: "Year history line chart",
            ENERGY: "Energy bar graph",
            CLUSTER: "Pattern analysis",
            PIE_REAL_TIME: "Real-time pie",
            CLUSTER_AHU: "Ahu diagnosis",
            CLUSTER_CHILLER: "Cooler diagnosis"
        },

        paneConfig: {
            TITLE: "Configure data source",
            DATA_CONFIG_TITLE: "Data points (each up to 5)",
            DATA_DRAG_TIP: "Please drag data point here",
            LABEL_INVERAL: "Time interval",
            LABEL_TIME_START: "Start time",
            LABEL_TIME_END: "End time",
            ALIGN_MODE: "Filled way",
            ALIGN_FORWARD: "Padded forward",
            ALIGN_BACKWARD: "Padded back",
            ALIGN_LINEAR: "Linear interpolation",
            START_ANALYSIS: "Start analysis",
            FUNCTION: "Function",
            DATA_DEAL: "Data processing",
            DATA_DIVIDE: "Data classification",
            TREND_ANALYSE: "Trend analysis",
            FREQ_ANALYSE: "Spectrum analysis",
            YEAR: "Year",
            MONTH: "Month",
            DAY: "Day",
            HOUR: "Hour",
            MINUTE: "Minute",
            SECOND: "Second",
            RECFG_SRC_DATA: "Reconfigure source data",
            SEL_PT_NAME: "Selected named",
            TREND_DISTRIBUTE: "Distribution trends",
            TYPE_POINT: "Category scatter",
            TYPICAL_CONDITION: "Typical conditions",
            DIAGNOSES_RESULT: "Diagnoses",
            DATE: "Date",
            POINT_NUM: "Count",
            MISS_NUM: "The number of missing",
            MISS_RATE: "Loss rate",
            ARGUMENTS: "Parameter",
            NAME: "Name",
            DESC: "Description",
            MAX: "Max",
            MIN: "Min",
            MED: "Median",
            AVG: "Average value",
            STD: "Standard value",
            RANGE_TO: "To",
            MODE_FIXED: "Fixed period",
            MODE_RECENT: "Recent period",
            MODE_CURRENT: "Preset period",
            MODE_ACTUAL_TIME: "Real time",
            INTERVAL_MIN1: "1 minute",
            INTERVAL_MIN5: "5 minutes",
            INTERVAL_HOUR1: "1 hour",
            INTERVAL_DAY1: "1 day",
            INTERVAL_MON1: "1 month",
            TIME_RANGE_SEC: "Second",
            TIME_RANGE_MIN: "Minute",
            TIME_RANGE_HOUR: "Hour",
            TIME_RANGE_DAY: "Day",
            TIME_RANGE_MON: "Month",
            DATA_TYPE_DEFAULT: "Data points",
            ERR1: "Background data request failed",
            ERR2: "Already exists in the selected point list!",
            ERR3: "You have not select any point!",
            ERR4: "Request spectral analysis, data classification data failed!",
            ERR5: "No data in the specified period , please select again!",
            ERR6: "No historical data points:",
            ERR7: "It has been automatically removed!",
            ERR8: "Time format error: start time is later than the end of time!",
            ERR9: "Malformed time: end time is later than the current time!",
            ERR10: "Data points repeat: you drag this data point already exists!",
            ERR11: "Data error: the period of time could not find any data!",
            ERR12: "Too many data points, can not continue dragging!"
        }
    },
    modalConfig: {
        TITLE: "Configuration",
        option: {
            SEARCH: "Inquiry",
            LABEL_MODE: "Mode",
            LABEL_MODE_ONE: 'Mode1',
            LABEL_MODE_TWO: 'Mode2',
            MODE_FIXED: "Fixed period",
            MODE_RECENT: "Recent period",
            MODE_CURRENT: "Preset period",
            MODE_REAL_TIME: "Real time",
            MODE_HISTORY: "History",
            MODE_COMPARE_EASY: "Quick configuration",
            MODE_COMPARE_SENSOR: "Sensor data",
            MODE_COMPARE_METER: "Power meter data",
            MODE_GAUGE: "Dashboard",
            MODE_WEATHER: "Weather",
            LABEL_INTERVAL: "Sampling period",
            LABEL_INTERVAL_ONE: 'Interval',
            INTERVAL_MIN1: "1 minute",
            INTERVAL_MIN5: "5 minutes",
            INTERVAL_HOUR1: "1 hour",
            INTERVAL_DAY1: "1 day",
            INTERVAL_MON1: "1 month",
            LABEL_PERIOD: "Time period",
            PERIOD_DROP_DOWN_LAST_HOUR: "Past hour",
            PERIOD_DROP_DOWN_TODAY: "Past 24 hours",
            PERIOD_DROP_DOWN_YESTERDAY: "Yesterday (24 hours)",
            PERIOD_DROP_DOWN_THREE_DAY: "Last 72 hours",
            PERIOD_DROP_DOWN_THIS_WEEK: "Last 7 days",
            PERIOD_DROP_DOWN_LAST_WEEK: "Last week (7 days)",
            PERIOD_DROP_DOWN_LAST_30_DAYS: "Past 30 days",
            PERIOD_DROP_DOWN_LAST_90_DAYS: "Past 90 days",
            PERIOD_DROP_DOWN_THIS_YEAR: "Past 12 months",
            PERIOD_UNIT_SEC: "Second",
            PERIOD_UNIT_MIN: "Minute",
            PERIOD_UNIT_HOUR: "Hour",
            PERIOD_UNIT_DAY: "Day",
            PERIOD_UNIT_MON: "Month",
            LABEL_TIME_RANGE: "Time period",
            TIP_RANGE_TO: "To",
            LABEL_GAUGE_MODE: "Display mode",
            GAUGE_MODE_LOW: "Alert by low value",
            GAUGE_MODE_HIGH: "Alert by high value",
            GAUGE_GREEN: "Good",
            GAUGE_NORMAL: "Normal",
            GAUGE_RED: "Alert",
            LABEL_UNIT: "Unit",
            LABEL_REAL_TIME_INTERVAL: "Refresh interval",
            LABEL_REAL_TIME_INTERVAL_ONE: 'Interval',
            REAL_TIME_INTERVAL_30_SEC: "30 seconds",
            REAL_TIME_INTERVAL_1_MIN: "1 minute",
            REAL_TIME_INTERVAL_5_MIN: "5 minutes",
            REAL_TIME_INTERVAL_10_MIN: "10 minutes",
            REAL_TIME_INTERVAL_30_MIN: "30 minutes",
            REAL_TIME_INTERVAL_1_HOUR: "1 hour",
            REAL_TIME_INTERVAL_1_DAY: "1 day",
            REAL_TIME_INTERVAL_1_MON: "1 month",
            LABEL_WEATHER: "City code",
            LABEL_COMPARE_PERIOD: "Comparative period",
            LABEL_COMPARE_DATE:'Time',
            LABEL_COMPARE_DATE1: "Time 1",
            LABEL_COMPARE_DATE2: "Time 2",
            COMPARE_PERIOD_HOUR: "1 hour",
            COMPARE_PERIOD_DAY: "1 day",
            COMPARE_PERIOD_WEEK: "1 week",
            COMPARE_PERIOD_MONTH: "1 month",
            COMPARE_PERIOD_YEAR: "1 year",
            LABEL_HISTORY_RANGE: "Time limit",
            HISTORY_RANGE_HOUR: "1 hour",
            HISTORY_RANGE_DAY: "1 day",
            HISTORY_RANGE_WEEK: "1 week",
            HISTORY_RANGE_MONTH: "1 month",
            HISTORY_RANGE_YEAR: "1 year",
            LABEL_CHART_SELECT: "Chart type",
            CHART_SELECT_BAR: "Bar graph",
            CHART_SELECT_LINE: "Line chart",
            CHART_TYPE: "Chart category",
            PIE: "Pie",
            BAR: "Bar graph",
            DEFAULT_TYPE: "Default category",
            DEFAULT_LINE: "Line chart",
            DEFAULT_BAR: "Bar graph",
            MODIFY_CHART_TITLE: "Title content",
            MODIFY_CHART_YAXIS_NAME: "Ordinate name",
            MODIFY_CHART_YAXIS_UNIT: "Ordinate units",
            MODIFY_CHART_MAX: "Max",
            MODIFY_CHART_MIN: "Min",
            MODIFY_CHART_MARK: "Graduation",
            MODIFY_CHART_CONFIG: "Advanced configuration",
            TEMP_UNIT: 'Temp Unit',
            TEMP_UNIT_C: 'Degrees Celsius',
            TEMP_UNIT_F: 'Degrees Fahrenheit',
            TITLE: 'Title',
            TITLE_TIP: "Please enter title",
            PT_ACCURACY: 'Decimal',
            PT_ACCURACY_TIP: 'Please enter number',
            UINT: 'Unit',
            UNIT_TIP: 'Please enter unit',
            MAX: 'MAX',
            MAX_TIP: 'Please enter maxnum',
            TITLE_NEW: 'Title：',
            TITLE_DATA: 'Data：',
            TITLE_DATA_TIP: 'Please drag data here.',
            DATA_TITLE: 'Data Title',
            DATA_SOURCE: 'Datasousce',
            DATA_UNIT: 'Data Unit',
            DATA_ACCURACY: 'Decimal',
            SHOW_DETAILS: 'Show details',
            APP_BLIND: 'APP Blind',
            BG_COLOR: 'Backgroundcolor',
            COLOR_NULL: 'transparent',
            COLOR_WHITE: 'white',
            COLOR_BLACK: 'black',
            COLOR_BLUE: 'blue',
            COLOR_GREEN: 'green',
            COLOR_CUSTOM: 'custom',
            APP_BLIND_TITLE: 'Title：',
            KPI_SOURCE: 'KPI Source',
            YMAX: 'Maximum axis',
            YMIN: 'Minimum axis',
            YTIP: 'Optional',
            TIME_LIMIT:'The maximum of time period is 20!'
        },
        data: {
            DATA_CONFIG_TITLE: "Data points:",
            DATA_CONFIG_TIPS: "This configure up to 20 points for adding a new point please remove the extra items.",
            //DATA_CONFIG_TITLE_TYPE1:"Each limit 5",
            DATA_TYPE_MAX_NUM: "(upper limit <% maxnum%> a)",
            DEFAULT_NAME: "Data points",
            DASHBOARD_MULTI_BAR: "Column figure parameters",
            DASHBOARD_MULTI_LINE: "Line chart parameters",
            DASHBOARD_MULTI_AREA: "Area chart parameters",
            DASHBOARD_MULTI_CUMULATIVE_BAR: "Cumulative bar graph parameters",
            DATA_LOSE: "Lose",
            PT_UPPER: "Upper limit",
            PT_LOWER: "Lower limit",
            PT_UNIT: "Axis units",
            PT_ACCURACY: "Decimal places",
            PT_COG_SURE: "Confirm",
            PT_COG_CANCEL: "Cancel",
            PT_LINE_1: "Baseline 1",
            PT_LINE_2: "Baseline 2",
            PT_LINE_3: "Baseline 3",
            PT_LINE_4: "Baseline 4",
            PT_LINE_NAME: "Name",
            PT_LINE_VAL: "Numerical",
            DATA_SHOW: "Data",
            TIME_MODE: "Time mode",
            DATA_NAME: "Data Name",
            DATASOURCE: "Datasousce",
            DATA_UNIT: "Data Unit",
            DATA_ACCURACY: "Decimal places",
            DATASOURCE_TIP: 'Please drag data  here',
            ENABLE_STACKING: 'enable stacking',
            VALUE: 'value',
            ALARM: 'alarm',
            ONE_LINE: 'one line',
            HALF_LINE: 'half line',
            SHOW_SUMMARAY: 'show summary only'
        },
        err: {
            TYPE1: "Too many data points, can not continue dragging!",
            TYPE2: "Data points repeat: you drag this data point already exists!",
            TYPE3: "Time format error: start time is later than the end of time!",
            TYPE4: "Malformed time: end time is later than the current time!",
            TYPE5: "Dashboard parameter error: parameter size does not follow from small to large order",
            TYPE6: "No historical data!",
            TYPE7: "Time parameter is not passed database!",
            TYPE8: "Time format is not recognized!",
            TYPE9: "Value for the current time period is too long a time period the unit!",
            TYPE10: "Contains a non-numerical parameters, check!",
            TYPE11: "Some data points lost, may have been deleted!",
            TYPE12: "Data point values ​​exceed the upper range limit!",
            TYPE13: "This can only be dragged into a data point!",
            TYPE14: "please configure the start time / end time",
            TYPE15: "under development"
        },
        btnStartConfig: {
            TYPE1: "Start analysis",
            TYPE2: "Determine"
        },
        modalApp: {
            RANKING: 'Ranking',
            FAULT_NAME: 'Fault Name',
            EQUIPMENT_NAME: 'Equipment Name',
            ZONE_NAME: 'Zone Name',
            TIMES: 'Numbers',
            MOTH_TIME: 'Number of months this month',
            AVE_DURATION: 'Ave. Duration',
            ENERGY_SAVEING: 'Energy Saveing',
            ZONE: 'Zone',
            EQUIPMENT: 'Equipment',
            FREQUENCY: 'Frequency',
            SURE: 'Search',
            CLOSE: 'Close',
            TIME_ERROR: 'Time format error, please check!',
            TIME_INTERVAL: 'Time interval is too long, please check!',
            TIME_DOT: 'Detail:',
            TIME_TITLE: 'Time',
            SEND_ORDER: 'Create WO',
            FAULT: 'Fault',
            FAULT_DETAIL: 'Detail'
        }
    },

    dataSource: {
        MONTH: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        WEEK: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        TITLE: "Data",
        DS_CONFIG: "Data source configuration",
        PROJECT_NAME: "Project name",
        PROJECT_SEARCH: "Search",
        NUMBER: "No.",
        POINT_NAME: "Point name",
        POINT_DESC: "Note",
        POINT_ATTR: "Attributes",
        SURE: "OK",
        CANCEL: "Cancel",
        PARAM: "Parameter",
        USER_NAME: "Username",
        CUSTOM_NAME: "Custom name",
        FILTER_REPEAT_ITEM: "Filtered duplicates",
        CUSTOM_REPEAT: "Custom name duplication",
        CUSTOM_NOT_NULL: "Custom name can not be empty",
        FORMULA_TIPS: "Please enter the formula (parameter follow the parameter list parameter name input):",
        FORMULA_NAME: "Formula name",
        FORMULA_VARIABLE_NAME: "Variable name",
        FORMULA_VARIABLE_VALUE: "Actual value",
        REMOVE_CONFIRM: "Confirm deletion?",
        REMOVE_CONFIRM_TIPS: "Linked",
        REMOVE_RESULT: "Deleted",
        WORKSPACE: "Workspace",
        TIME_YESTERDAY: "Yesterday",
        TIME_TODAY: "Today",
        NO_MATCH_FOUND: "No matches were found",
        NO_SELECT_POINT: "Please select a point!",
        GROUP_SELECTED: "Selected",
        NO_SELECT_GROUP: "Please select a group!",
        INPUT_GROUP_NAME: "Please enter a group name!",
        ADD_GROUP: "+ Add group",
        POINT_TYPE_CUSTOM: "Customize",
        POINT_TYPE_SYSTEM: "System",
        POINT_TYPE_DEVICE: "Equipment",
        POINT_TYPE_TYPE: "Types of",
        ERROR: "Your data source has been deleted, the chart can not be generated!",
        ICON_SYS_HVAC: "HVAC",
        ICON_SYS_POWER: "Power",
        ICON_SYS_LIGHT: "Lighting and socket",
        ICON_SYS_CRAC: "CRAC",
        ICON_DEV_CHIL: "Chiller",
        ICON_DEV_PUMP: "Pump",
        ICON_DEV_COOL: "Cooling tower",
        ICON_DEV_AHU: "AHU",
        ICON_DEV_VAV: "VAV",
        ICON_DEV_SYS: "System",
        ICON_TYPE_TEMP: "Temperature",
        ICON_TYPE_FLOW: "Flow",
        ICON_TYPE_FREQ: "Frequency",
        ICON_TYPE_ONOFF: "OnOff",
        ICON_TYPE_ELEPOW: "Power",
        ICON_TYPE_ELEPOWMET: "Power meter",
        ICON_TYPE_THER: "Thermal energy meter",
        ICON_TYPE_PRES: "Pressure",
        ICON_TYPE_ALARM: "Alert",
        ICON_TYPE_CURFLOW: "Current",
        NAV_MINE: "Mine",
        NAV_CLOUD: "Public",
        ALREADY_EXIST: "Add duplicates have been removed",
        ADD_POINT_GROUP: "Add group",
        ADD_POINT: "Add point",
        ADD_FORMULA: "Add formulas",
        RENAME: "Rename",
        REMOVE: "Delete",
        DELETE_GROUP_INFO: 'Please confirm whether to delete!',
        SEARCH_KEYWORD: 'Enter keywords',
        SEARCH_ALL: 'all',
        SEARCH_HIDE: 'hide',
        SEARCH_TOWER_SYSTEM: 'cooling tower system',
        SEARCH_ROOM: 'room',
        SEARCH_AHU: 'AHU',
        SEARCH_TOWER: 'cooling tower',
        SEARCH_CHILLER: 'chiller',
        SEARCH_CONTROLLER: 'controller',
        SEARCH_FCU: 'FCU',
        SEARCH_GETAWAY: 'getaway',
        SEARCH_HEAT: 'Heat exchanger',
        SEARCH_CHARGE: 'charge',
        SEARCH_SEANSOR: 'Temperature sensor',
        SEARCH_HVAC: 'HVAC system',
        SEARCH_DEVICE: 'smart device',
        SEARCH_VAV: 'VAV',
        SEARCH_VALVE: 'valve',
        SEARCH_WATER: 'Water pump',
        TAG_ALL: 'All',
        TAG_EQUIPMENT: 'Equipment',
        TAG_FLOOR: 'Floor',
        TAG_ENERGY: 'Energy',
    },

    mainPanel: {
        canvasText: {
            CONTENT: 'Content:',
            FONTCOLOR: 'Color:',
            ROUNT: 'Redirect:',
            ROUTER_PLACEHOLDER: 'Please Enter',
            INTERNAL_LINK: 'Interval Link:',
            INTERNAL_LINK_PLACEHOLDER: 'Enter the embedded page ID',
            REPORT_LINK: 'Report Link:',
            REPORT_LINK_PLACEHOLDER: 'Enter report page ID',
            CHAPTER: 'Chapter:',
            CHAPTER_PLACEHOLDER: 'Enter report chapter',
            FONTSIZE: 'FontSize:',
            FONTTYPE: 'Type:',
            HORIZONTAL_ALIGN: 'H Align:',
            VERTICAL_ALIGN: 'V Align :',
            LINEHEIGHT: 'Lineheight:',
            DATASOURCE: 'DataSource:',
            ACCURACY: 'Decimal digits:',
            ENUMERTATE: 'Enumerate:',
            NOTSTRETCHCONTENT: 'No Stretch Content:',
            SKIN: 'Skin:',
            SKIN_BLACK: 'Black',
            SKIN_WHITE: 'White',
            SKIN_COOL: 'Cool',
            TITLE: 'Title:',
            TITLE_TIP: 'Please Enter',
            TITLE_STYLE: 'Title Style:',
            CONTENT_STYLE: 'Content Style:',
            DEBUG_VALUE: 'Value',
            WHETHER_ENABLED_DATA_SOURCE: 'Whether the data source is enabled:',
            CONSEQUENCE: 'Consequence:',
            ENTER_SUBTITLE: 'Enter Subtitle'
        },
        ueserOpera: {
            CHANGE_PROJECT: "Switch project",
            PREVIEW_PROJECT: "Preview project",
            RELEASE_PROJECT: "Publish project",
            CANCELLATION: "Logout",
            CONFIG: 'Config',
            config: {
                IS_REALTIME_SAVE: 'Auto save',
                BTN_CLOSE: 'Close'
            },
            ONLINE_USER_IN_PAGE:"Online user in this page:"
        },
        pageEditModal: {
            ADD_PAGE_TITLE: 'Add Page',
            EDIT_PAGE_TITLE: 'Edit Page',
            EDIT_PAGE_DIRECTORY: 'Edit the directory',
            NAME: 'Page Name',
            PAGE_NAME: 'Untitled',
            TYPE: 'Page Type',
            SIZE: 'Page Size',
            DISPLAY: 'Display',
            STRETCH: 'Stretch',
            CENTER: 'Center',
            ICON: 'Icon',
            BACKGROUND: 'Background',
            SELECT: 'Select',
            SELECTED: 'Selected',
            SURE: 'OK',
            CLOSE: 'Close',
            REPORT_TYPE: 'report type',
            DAY_REPORT: 'daily report',
            WHEEK_REPORT: 'weekly report',
            MONTH_REPORT: 'monthly report',
            PAGE_PATH: 'path',
            ENTER_PAGE_PATH: 'please enter report path!'
        },
        iconSelect: {
            ICON_TITLE: 'Icon Select'
        },
        bgSelect: {
            BG_TITLE: 'Background Select',
            BG_TYPE: 'Background Selection:',
            BG_COLOR: 'color',
            BG_IMAGE: 'image',
            CHOOSE_IMAGE: 'Choose Image',
            IMAGE_STRETCH: 'stretch',
            IMAGE_TILE: 'tile',
            PREVIEW: 'Preview'
        },
        navbar: {
            SAVE_PAGE: "Save",
            PREVIEW_PAGE: "Preview",
            UNDO: "Undo",
            REDO: "Redo",
            RELEASE_PAGE: "Publish page",
            EXIT_EDIT: "Exit edit",
            QUIT_SCENE: "Quit scene",
            VARIABLE_PANEL: 'Variable panel'
        },
        toolbar: {
            ARROW_TOOL: "Arrow tool(v)",
            HAND_TOOL: "Hand tool(m)",
            TEXT_TOOL: "Text widget(t)",
            BUTTON_TOOL: "Button widget(b)",
            HTML_TOOL: "Html container widget(h)",
            SCREEN_TOOL: "Screen container widget(s)",
            IMG_TOOL: "Picture widget(i)",
            PIPE_TOOL: "Pipeline widget(p)",
            ZOOM_TOOL: 'ZOOM',
            MATERAL_TOOL: "Library widget",
            GRID_TOOL: "Show gridlines",
            DEVICE_TOOL: 'Device Settings',
            LAYOUT_TOOL: 'Align',
            THERMODY_TOOL: 'Thermal Mapping',
            HtmlContainer_TOOL: 'HtmlContainer',
            POLYGON_TOOL: 'Hotspot widget',
            LINE_TOOL: 'Line widget'
        },
        tLayout: {
            TOPALIGN: 'Top alignment',
            RIGHTALIGN: 'Right alignment',
            BOTTOMALIGN: 'Bottom alignment',
            LEFTALIGN: 'leftalignment',
            CENTERALIGN: 'Horizontal spacing',
            MODDLEALIGN: 'Vertical spacing',
            HEATAREA: 'Set Heat Area',
            HEATSOURSE: 'Set Heat Source'
        },
        releaseRepeat: {
            TITLE: "Publish",
            RELEASE_INFO: "Please confirm whether to publish?",
            RELEASE_START: "Start publishing",
            RELEASE_NO: "Cancel",
            RELEASE_TITLE: "Fill description",
            PASSWORD: "Password:",
            RELEASE_TO: "Post to:",
            PASSWORD_INFO: "Please enter a release password ",
            OK: "Posted successfully!",
            NO: "Publish failed!",
            SELECT: "Please choose",
            NEW_PROJECT: "New project"
        },
        releasePage: {
            PROJECT_NAME: "Project name:",
            NAME_INFO: "Please enter the Project name in English",
            RELEASE_INFO: "Wrong password!",
            RELEASE_INFO_TIP: "Please select a project!"
        },
        releaseProject: {
            RELEASE_INFO: "Password error!"
        },
        layerPanel: {
            TITLE: "Layer",
            HTML_LAYER: "Html layer",
            BG_LAYER: "Background",
            EXPORT_INFO: "Please select a layer!",
            EXPORT_INFO_TIP: "Currently only supports export template canvas layer",
            DELETE_INFO: "Html layer and the background layer can not be deleted",
            DELETE_INFO_TIP: "You can not delete locked layer",
            DRAG_LAYER_INFO: "Please select a node to drag and drop!",
            ADD_GROUP: "New folder",
            ADD_PAGE: "New page",
            EDIT_PAGE: "Edit page",
            LOCK_PAGE: "Lock page",
            EXPORT_PAGE_TEMPLET: "Export page template",
            IMPORT_PAGE_TEMPLET: "Import page template",
            DELETE_PAGE: "Delete page",
            ADD_GROUP: 'New group',
            ADD_LAYER: "New layer",
            EDIT_LAYER: "Edit layer",
            LOCK_LAYER: "Lock layer",
            EXPORT_LAYER_TEMPLET: "Export layer template",
            IMPORT_LAYER_TEMPLET: "Import layer template",
            DELETE_LAYER: "Delete layer",
            DELETE_LAYER_INFO: 'Are you sure to delete the selected layer?',
            WRITE_TEMPLET_NAME: 'Please enter template name',
            EXPORT_PAGE_TEMPLET_INFO: 'Please choose a page to be exported!',
            SELECT_WORD_INFO: 'Must be checked or can not simultaneously change multiple files name!',
            DIRECTORY_STRUCTRUE: 'Currently it supports up to three directory structure!'
        },
        historyPanel: {
            UNDEFINED: "Undefined action",
            CREATE_LAYER: "Create layer",
            DELETE_LAYER: "Delete layer",
            CHANGE_LAYER_NAME: "Edit layer name",
            SHOW_LAYER: "Show layer",
            HIDE_LAYER: "Hidden layer",
            UNLOCK_LAYER: "Unlock layer",
            LOCK_LAYER: 'Lock layer',
            NODE_MOVE: 'Layer/Widget move',
            CREATE_WIDGET: "Create widget",
            DELETE_WIDGET: "Remove widget",
            CHANGE_WIDGET_NAME: 'Edit widget name',
            SHOW_WIDGET: 'Show widget',
            LOCK_WIDGET: 'Lock widget',
            HIDE_WIDGET: 'Hidden widget',
            UNLOCK_WIDGET: 'Unlock widget',
            MOVE_WIDGET: "Move widget",
            RESIZE_WIDGET: "Adjust size",
            MOVE_WIDGET_OR_RESIZE_WIDGET: "Move widget or Adjust size",
            CREATE_BUTTON_WIDGET: "Create button",
            DELETE_BUTTON_WIDGET: "Delete button",
            CHANGE_BUTTON_WIDGET_TEXT: "Change button text",
            CHANGE_BUTTON_WIDGET_STYLE: "Change button style",
            CHANGE_BUTTON_WIDGET_PAGE: "Change button page jumps",
            CHANGE_BUTTON_WIDGET_FLOAT: "Change button page jumps float",
            CHANGE_BUTTON_WIDGET_ENUMERATE: "Change button enumerate",
            CHANGE_BUTTON_WIDGET_IDDS: "Change button data source",
            CHANGE_BUTTON_WIDGET_CUSTOMSTYLE: "Change button custom style",
            CREATE_TEXT_WIDGET: "Create text widget",
            DELETE_TEXT_WIDGET: "Delete text widget",
            CHANGE_TEXT_WIDGET_TEXT: "Change text",
            CHANGE_TEXT_WIDGET_STYLE: "Change text style",
            CHANGE_TEXT_WIDGET_PAGE: "Change text page jumps",
            CHANGE_TEXT_WIDGET_FLOAT: "Change text page jumps float",
            CHANGE_TEXT_WIDGET_ENUMERATE: "Change text enumerate",
            CHANGE_TEXT_WIDGET_IDDS: "Change text data source",
            CHANGE_TEXT_WIDGET_CUSTOMSTYLE: "Change text custom style",
            CHANGE_TEXT_WIDGET_PRECISION: "change text precision",
            CHANGE_TEXT_WIDGET_FONT_FAMILY: "change text font family",
            CHANGE_TEXT_WIDGET_FONT_SIZE: "change text font size",
            CHANGE_TEXT_WIDGET_FONT_STYLE: "change text font style",
            CHANGE_TEXT_WIDGET_HORIZONTAL_ALIGN: "change text horizontal align",
            CHANGE_TEXT_WIDGET_VERTICAL_ALIGN: "change text vertical align",
            CHANGE_TEXT_WIDGET_COLOR: "change text color",
            CREATE_HTMLCONTAINER_WIDGET: "Create HtmlContainer",
            DELETE_HTMLCONTAINER_WIDGET: "Delete HtmlContainer",
            CHANGE_HTMLCONTAINER_WIDGET_CONTENT: "Change HtmlContainer content",
            EXPORT_HTMLCONTAINER_WIDGET: "Export HtmlContainer",
            IMPORT_HTMLCONTAINER_WIDGET: "Import HtmlContainer",
            CREATE_HTMLSCREENCONTAINER_WIDGET: "Create HtmlScreenContainer",
            DELETE_HTMLSCREENCONTAINER_WIDGET: "Delete HtmlScreenContainer",
            CHANGE_HTMLSCREENCONTAINER_WIDGET_CONTENT: "Change HtmlScreenContainer content",
            CHANGE_HTMLSCREENCONTAINER_WIDGET_CUSTOMSTYLE: "Change HtmlScreenContainer custom style",
            CREATE_PIPE_WIDGET: "Create pipe",
            DELETE_PIPE_WIDGET: "Delete pipe",
            CHANGE_PIPE_WIDGET_WIDTH: "Change pipe width",
            CHANGE_PIPE_WIDGET_COLOR: "Change pipe color",
            CHANGE_PIPE_WIDGET_IDDS: "Change pipe data source",
            CHANGE_PIPE_WIDGET_ENUMERATE: "Change pipe enumerate",
            CHANGE_PIPE_WIDGET_WATERFLOWDIRECTION: "Change pipe waterflowdirection",
            CHANGE_PIPE_WIDGET_ANIMATION: "Change pipe animation",
            CREATE_IMAGE_WIDGET: "Create image",
            DELETE_IMAGE_WIDGET: "Delete image",
            CHANGE_IMAGE_WIDGET_CONTENT: "Change image content",
            CHANGE_IMAGE_WIDGET_ANGLE: "Change image angle",
            CHANGE_IMAGE_WIDGET_IDDS: "Change image data source",
            CHANGE_IMAGE_WIDGET_ENUMERATE: "Change image enumerate",
            CHANGE_IMAGE_WIDGET_PAGE: "Change image page jumps",
            CHANGE_IMAGE_WIDGET_FLOAT: "Change image page jumps float",
            CREATE_HEAT_WIDGET: "Create heat",
            DELETE_HEAT_WIDGET: "Delete heat",
            CHANGE_HEAT_WIDGET_POINTNUM: "Change heat pointNumber",
            CHANGE_HEAT_WIDGET_POINTARR: "Change heat pointArr",
            CHANGE_HEAT_WIDGET_POINTID: "Change heat pointId",
            CREATE_HEATP_WIDGET: "Create heatp",
            DELETE_HEATP_WIDGET: "Delete heatp",
            CREATE_HTMLDASHBOARD_WIDGET: "Create htmlDashboard widget",
            DELETE_HTMLDASHBOARD_WIDGET: "Delete htmlDashboard widget",
            CREATE_LINE_WIDGET: 'Create line',
            DELETE_LINE_WIDGET: 'Delete line',
            CREATE_HOTSPOT_WIDGET: 'Create hotspot',
            DELETE_HOTSPOT_WIDGET: 'Delete hotspot',
            CHANGE_LINE_WIDGET_WIDTH: 'Change line width',
            CHANGE_LINE_WIDGET_COLOR: 'Change line color',
            CHANGE_LINE_WIDGET_STYLE: 'Change line style',
            THE_DEFAULT_SNAPSHOTS: 'The default snapshots'
        },
        exportModal: {
            EXPORT_INFO: "Enter a template name",
            TEM_NAME: 'Name',
            TEM_TYPE: 'Type',
            TEXT: 'Text control',
            BUTTON: 'Button control',
            HTML: 'HtmlContainer',
            SURE: 'OK',
            CANCEL: 'Cancel',
            WRITE_INFO: 'please enter template name',
            EDIT_CON: 'Edit content',
            NO_POINT: 'Can’t find relevant cloud point',
            PHOTO: 'snapshot',
            POINT_FORMAT_ERROR: 'Cloud point format error.',
            PROJECT_ID_ERROR: 'Unable to add cloud point, please check project ID.',
            WIDGET: 'Widget',
            PAGE: 'Page',
            LAYER: 'Layer'
        },
        layerName: {
            TEXT: 'Text',
            BUTTON: 'Button',
            HTML: 'HTML',
            SCREEN: 'Screen',
            IMAGE: 'Image',
            PIPE: 'Pipe',
            DEVICE: 'Device',
            HEAT: 'Heat Area',
            HEATP: 'Heat Sourse',
            POLYGON: 'Hotspot',
            HTML_DASHBOARD: 'HTML Dashboard',
            DASHBOARD: 'HtmlDashboard',
            LINE: 'Line'
        },
        attrPanel: {
            attrTab: {
                TITLE: "Attributes",
                PAGE_MANAGE: "Page",
                DATA_SOURCE: "Data",
                HISTORY_RECORD: "History",
                REPORT_TPL: "Report Template"
            },
            attrRepeat: {
                STYLE: "Style:",
                CONTENT: "Content:",
                DATA_SOURCE: "Data source:",
                CUSTOMSTYLE: "Custom style:",
                EDIT_CONTENT_TITLE: "Edits",
                SAVE_STYLE_TITLE: "Application",
                EXPORT_STYLE_TITLE: "Export template",
                IMPORT_STYLE_TITLE: "Import template",
                PAGE: "Page:",
                SELECT_SCREEN: "Select page",
                LINK_TO: 'Link to:',
                LINK_TO_CON: 'Disable page redirect',
                EXACT_NUMBER: 'Decimal digits:',
                FLOAT: 'Float:',
                LOOK_UP_PAGE_NAME: 'Look up the page name',
                JUMP_S3DB_PAGE: 'Jump s3db page',
                PAGE_NAME: 'Page name:',
                FILL_IN_PAGE_NAME: 'Fill in the page name+<#x#>'
            },
            attrText: {
                TEXT_CONDITION: "Enter text here",
                TEXT_ONE: "Body 1",
                TEXT_TWO: "Body 2",
                TITLE_ONE: "Heading 1",
                TITLE_TWO: "Heading 2",
                TITLE_THREE: "Heading 3",
                TITLE_FOUR: "Heading 4",
                TITLE_FIVE: "Heading 5",
                SUBTITLE: "Subtitle",
            },
            attrButton: {
                STYLE_ONE: "Default",
                STYLE_TWO: "Primary",
                STYLE_THREE: "Success",
                STYLE_FOUR: "Info",
                STYLE_FIVE: "Warning",
                STYLE_SIX: "Danger",
                STYLE_SEVEN: "Link",
                STYLE_EIGHT: "Pink",
                STYLE_NINE: "Blue",
                STYLE_TEN: "Green"
            },
            attrHtml: {
                TITLE: "Code editor",
                RUNCODE: "Run code",
                SAVEANDEXIT: "Save and exit",
                IMAGEMANAGER: 'Image manager'
            },
            attrImg: {
                IMAGE: "Image:",
                ROTATE: "Rotation:",
                CHOOSE: "Select",
                ENUMER_INFO: "Please enter key value"
            },
            attrPipe: {
                PIPE_WIDTH: "Length:",
                PIPE_COLOR: "Color:",
                REVERSE_FLOW: 'Reverse:',
                FLOW_PATTERN: 'Flow pattern:',
                FINE_LINE: 'Fine line',
                THICK_LINE: 'Thick line',
                BUBBLE: 'Bubble',
                FULL_LINE: 'Full line',
                IMAGINARY_LINE: 'Imaginary line',
                UNKNOWN: 'Unknown',
                LOGIC: 'Logic',
                CUSTOM_COLOR: 'Customize',
                PIPE_STYLE: 'Type:'
            },
            attrDevice: {
                DEVICE_TYPE: 'Type:',
                DEVICE_PREFIX: 'Prefix:',
                DEVICE_PROP: 'Attributes:',
                DEVICE_LINK: 'Links:',
                DEVICE_EJECT: 'Pop up:',
                DEVICE_DIAGNOSIS: 'Diagnosis:',
                DEVICE_SKIN: 'Style:',
                DEVICE_DROP_INFO: 'Existing instance of an object can not be changed!'
            },
            attrLine: {
                LINE_WIDTH: 'Length:',
                LINE_COLOR: 'Color:',
                CUSTOM_COLOR: 'Customize',
                LINE_STYLE: 'Type:'
            },
        },
        materalPanel: {
            toolbar: {
                TITLE: "Library",
                PRIVATE_MATERAL: "Favorite",
                PAGE_MATERAL: "Page",
                LAYER_MATERAL: "Layer",
                BUTTON_MATERAL: "Widget",
                PUBLIC_MATERAL: "Library"
            },
            materalRepeat: {
                USE_MODAL: "Use material",
                DELETE_OK: "Deleted successfully ",
                ADD_OK: "Added successfully",
                PHOTO: "Image",
                ANIMATION: "Animation",
                PAGE_NAME: "Name:",
                PAGE_CREATOR: "Creator:",
                PAGE_TIME: "Created:",
                PAGE_TYPE: 'Type',
                FORMAT_LOG: "Format error!"
            },
            privateMateral: {
                ADD_PHOTO: "Add image from library",
                DELETE_PHOTO: "Delete",
                USE_PHOTO: "Use",
                COPY: 'Copy',
                COPY_LINK_SUCCESS: 'Copy link success!',
                COPY_LINK_FAILED: 'Copy link failed, your browser may not support this feature, please manual copy.',
                COPY_TO_CLIPBOARD: 'The clipboard has been copied'
            },
            pageMateral: {
                ADD_MODAL: "New template",
                BATCH_ADD: "Batch production",
                EDIT_PAGE: "Edit page",
                DELETE_PAGE: "Delete page",
            },
            layerMateral: {
                EDIT_LAYER: "Edit layer",
                DELETE_LAYER: "Delete layer"
            },
            buttonMateral: {
                EDIT_BUTTON: "Edit button",
                DELETE_BUTTON: "Remove button",
                USE_COPY: "Whether to keep a copy?"
            },
            publicMateral: {
                UPLOAD_PHOTO: "Upload",
                ADD_PRIVATE: "Add to private library",
                DELETE_PHOTO: "Delete",
                UPLOAD_INFO: "Image type should be .gif, jpg, png, jpeg",
                UPLOAD_INFO_TIP: "Image should be no greater than 600k. ",
                EDIT_PHOTO: "Edit",
                WRITE_KEYWORD: 'Please enter key words'
            }
        }
    },
    report: {
        REPORT_LIST: 'Report List',
        REPORT_NAME: 'Template',
        REPORT: 'report',
        MODULE: 'module',
        REPORT_SUB_NAME: 'Unnamed',
        REPORT_RIGHT_NAME: 'Report',
        VAR_DECLARATION: 'Variable declaration',
        VAR_DECLARATION_NAME: 'variable name',
        VAR_DECLARATION_VALUE: 'variable value',
        VAR_DECLARATION_DESC: 'variable description',
        VAR_DECLARATION_DESC_DETAIL: 'Please enter description information',
        VAR_DECLARATION_EDIT_CODE: 'edit code',
        VAR_DECLARATION_INFO: 'Error: data format error!',
        REMOVE_BTN: 'Delete widget',
        PAGEBREAK_BTN: 'Page break',
        CONFIG_TEMPLATE_PRAM: 'Configuration template parameters',
        EXPORT_BTN: 'Export as template',
        SELECT_INFO: 'Please select a template!',
        REMOVE_INFO: 'Are you sure to delete this template?',
        REMOVE_INFO_SUCCESS: 'Delete successfully',
        ADD: 'New',
        DELETE: 'Delete',
        TEMPLATE_EDIT: 'Template edit',
        CONFIRM_DELETE: 'Confirm delete this ?',
        LABEL_WIDTH: 'Width',
        LABEL_HEIGHT: 'Height',
        ENTER_TEMPLATE_NAME: 'Please enter template name',
        ERROR_TEMPLATE_NAME: 'Please enter the correct template name!',
        EXPORT_SUCCESS: 'Export success!',
        EXPORT_ERROR: 'Export fail!',
        NOT_SUPPORT_EXPORT: 'This module can\'t be export.',
        REPORT_FAIL_INFO: "The current report has not yet formed.",
        optionModal: {
            TITLE: 'Basic',
            TEXT: 'Text',
            HTML: 'Html',
            ECHARTS: 'Chart',
            CHAPTER: 'Chapter',
            SUMMARY: 'Summary',
            BLOCK: 'Dynamic report module',
            DIAGNOSIS_BLOCK: 'Diagnosis report module',
            DATA_BLOCK: 'Data block',
            TABLE: 'Table',
            DRAG: 'Drag',
            CUMULANT_CHART: 'Cumulant Chart'
        },
        reportConfig: {
            TITLE: 'Configuration',
            REPORT_CYCLE: 'Period',
            REPORT_CYCLE_DAY: 'Day',
            REPORT_CYCLE_WEEK: 'Week',
            REPORT_CYCLE_MOUTH: 'Month',
            REPORT_CYCLE_YEAR: 'Year',
            SURE: 'OK'
        },
        chapterConfig: {
            TITLE: 'Configuration',
            CHAPTER_TITLE: 'Titles',
            CHAPTER_SUMMARY: 'Summary',
            CONFIG: 'Configuration',
            SHOWORHIDE: 'Show / Hide',
            NUMBER: 'Chapter ',
            CHAPTER: '. '
        },
        templateConfig: {
            TITLE: 'Template parameters',
            PRAM_NAME: 'Name',
            PRAM_TYPE: 'Type',
            PRAM_VALUE: 'Value',
            NO_PRAM: 'No parameter',
            REFRESH: 'Refresh',
            APPLY: 'Apply',
            WRITE_VALUE: 'Please enter the value'
        },
        blockConfig: {
            TITLE: 'Dynamic report module configuration',
            DATA_ID: 'Data ID ',
            WRITE_ID: 'Please enter data ID'
        },
        diagnosisBlockConfig: {
            TITLE_NO_DATA: "No data"
        },
        chartConfig: {
            TITLE: 'Configuration',
            CHART_TYPE: 'Type',
            CHART_LINE: 'Line',
            CHART_RECT: 'Bar',
            CHART_CIRCLE: 'Pie',
            CONFIG: 'Configuration',
            DATA_DOINT: 'Data source',
            SAMPING_CYCLE: 'Range',
            BEFORE_DAY: 'Last day',
            BEFORE_WEEK: 'Last week',
            BEFORE_MOUTH: 'Last month',
            BEFORE_YEAR: 'Last year',
            SAMPING_SPACE: 'Interval',
            FIVE_MINITER: '5 minutes',
            ONE_HOUR: '1 hour',
            ONE_DAY: '1 day',
            ONE_MONTH: '1 month',
            WRONG_INFO: 'Error: error in chart configuration, change will not be saved.',
            INTER_WORD: 'Legend',
            COPY_LINK: 'Copy link',
            COPY_LINK_SUCCESS: 'Copy success',
            COPY_LINK_FAILED: 'Copy failed',
            COPY_IMAGE_SUCCESS: 'Image URL has been copied to the clipboard',
            START_TIME: 'Start Time',
            END_TIME: 'End Time'
        },
        tableConfig: {
            TYPE: 'Type',
            DATASOURCE: 'Data source',
            TITLE: 'Table Config',
            ISCHANGE: 'Swap rows and columns'
        },
        reportWrap: {
            PDFDOWNLOAD: 'PDF',
            WORDDOWNLOAD: 'Word',
            EXCELDOWNLOAD: 'Excel',
            GENERATED_BY_BEOP: 'Generated by BeOP',
            LOADERROR: 'Failed to load some chapters, please refresh page and try again.'
        }
    },
    screen: {
        UNSAVED_PAGE_TIP: 'This page isn\'t been saved, sure to leave?'
    },
    iot: {
        IOT: 'IOT',
        PARAMS_CONFIG: 'Config',
        // QUERY_KEYWORD: 'keyword search ...',
        TREE_ALL: 'All',
        TREE_HIDE: 'Hide',
        ADD_THING: 'Add Thing',
        ADD_GROUP: 'Add Group'
    },
    modal: {
        memberSelected: {
            CONFIRM: 'Confirm',
            TITLE: "Please Select Members",
            INPUT_INFO: "Please Enter Members Name To Search",
            ALL: 'All',
            MEMBER_SELECTED: 'Members'
        }
    },
    diagnosis: {
        OVERVIEW: 'Navigation',
        DIAGNOSIS_LOG: 'Diagnosis logs',
        LOG_MORE: 'More...',
        LOG_NO_MORE: 'No more data !',
        config: {
            TITLE: 'Config',
            CONFIRM: 'Confirm',
            CANCEL: 'Cancel',
            NORMAL: 'Normal Level',
            ALERT: 'Alert Level',
            WARNING: 'Warning Level',
            RULE_SET: 'Alarm rule config',
            AUTO_PUSH_WO: 'Auto push WO',
            DIAGNOSIS_PAUSE_SET: 'Diagnosis pause config',
            SET: 'Config',
            ACTIVE: 'Active',
            DIAGNOSIS_SHOW: 'Show diagnosis Per hour',
            CHOOSE_DIAGNOSIS_SHOW: 'Choose Show diagnosis Per hour',
            defaultPeriod: {
                REAL_TIME: 'Real time',
                DELAY_1H: 'Delay for 1 hour',
                DELAY_12H: 'Delay for 12 hours',
                DELAY_24H: 'Delay for 24 hours',
                DELAY_7D: 'Delay for 7 days',
                DELAY_1M: 'Delay for 1 month',
                DELAY_FOREVER: 'Delay forever'
            },
            subConfig: {
                CREATE_CASE: 'Create case',
                CASE_NAME: 'Case name',
                CHOOSE_BUILD: 'Choose building',
                CHOOSE_AREA: 'Choose area',
                CHOOSE_EQUIPMENT_TYPE: 'Choose equipment type',
                CHOOSE_STOP_TIME: 'Choose pause time',
                CHOOSE_DISTRIBUTE_PERSON: 'Choose distribute person',
                ALARM_LEVEL: 'Alarm level',
                PROJECT: 'Project',
                USER: 'Member',
                NORMAL: 'Normal',
                ALERT: 'Alert',
                WARNING: 'Warning',
                UPDATE_FAIL: 'Failed to Save',
                MUST_CHOOSE_EQUIP: 'Please choose an Equipment',
                MUST_FILL_IN: 'Please Fill in requirement info',
                FAUTS_LIST:'Faults List',
                ENABLE_FDD:'Enable FDD',
                DISABLE_FDD:'Disable FDD',
                LEVEL:'Level',
                FAULT_NAME:'Fault',
                EQUIOMENT:'Equipment',
                CONSEQUENCE:'Consequence',
                STATUS:'Status',
                ENABLE:'Enable',
                DISABLE:'Disable',
                SHOW_FAULT:'Show disabled faults',
                SHOW_PUSH_FAULT:'Show push faults',
                SELECT_FAULTS:'Please select a fault!',
                ENA_SUCCESS:'Succeed!',
                DIS_SUCCESS:'Succeed!',
                CLOSE:'Close'
            },
            CHANGE_LEVEL: 'Change Level',
            CHANGE_ALARM_TIME: 'Change alarm time',
            LEVEL_SET: {
                NORMAL: 'Normal',
                CRITICAL: 'Warning',
                URGENT: 'Fault'
            }
        },
        historyLog: {
            TITLE: 'Log History',
            TIME: 'Time',
            GRADE: 'Grade',
            EQUIPMENT: 'Equipment',
            ZONE: 'Zone',
            FAULT: 'Fault',
            STATUS: 'Status',
            EXECUTOR: 'Executor',
            RESPONSE_TIME: 'Response Time',
            RESPONSE_CONTENT: 'No Response',
            FEEDBACK: 'Feedback',
            NO_LOG_HISTORY:'No history.'
        },
        diagnosticLog: {
            HISTORY: 'History',
            STICKY_POST: 'Sticky Post',
            CHECK: 'Check',
            HIDE_SHOW: 'Hide Or Show',
            HIDE_SHOW_URGENT: 'Hide Or Show Urgent Log',
            ENERGY_CONSSERVATION: 'Wasted Energy:'
        },
        diagnosisROI: {
            BACK: 'Back',
            QUERY: 'Query',
            EDIT: 'Edit',
            SAVE: 'Save',
            PAINTER: 'Painter',
            PAINTER_ERROR1: 'Please choose the row!',
            PAINTER_ERROR2: 'Please click Format Painter!',
            PAINTER_ERROR3: 'Please save your changes!',
            DOWNLOAD: 'Download',
            TO: 'To',
            FAULT_NAME: 'Fault',
            EQUIPMENT: 'Equipment',
            CONTENT: 'Content',
            COUNT: 'Count',
            TITLE_SAVING: 'Saving(kWh)',
            SAVING: 'Saving per',
            NO: 'No.',
            TIME: 'Time',
            GRADE: 'Grade',
            GROUP: 'Group',
            FAULT: 'Fault',
            ALERT: 'Alert',
            ZONE: 'Zone',
            POWER_PRICE: 'Elc.Price({m}/kWh)',
            HR_PRICE: 'Labor Price({m}/hr)',
            HR: 'Work hour(hr)',
            LABORCOST: 'Labor Cost({m})',
            ROI: 'ROI(yr)',
            DAY: 'Day',
            WEEK: 'Week',
            MONTH: 'Month',
            YEAR: 'Year',
            MSG_CHECK_TIME: 'End time cannot be less than start time',
            SAVE_MONEY: 'Saving({m})'
        }
    },
    asset: {
        navigation: {
            NAV_TITLE: 'Navigation',
            BTN_STATE: 'Log',
            BTN_CLOSE_STATE: 'Close Log'
        },
        state: {
            MAINTAIN: 'Maintain',
            REPAIR: 'Repair Log',
            OPERATION: 'Operate Log',
            START_TIME: 'Start time',
            END_TIME: 'End time',
            BTN_QUERY: 'Query'
        }
    },
    thermalComfort: {
        OVERHEAT_OVERCOOL: 'Overheat/Overcool',
        CONTROL: 'Control',
        SETPOINT: 'Setpoint',
        SUMMARY: 'Summary',
        OVERCOOL_NUMBER: 'Overcool',
        OVERHEAT_NUMBER: 'Overheat',
        STANDARD_SP: 'SP.',
        CONTROL_OVERCOOL: 'Overcool',
        CONTROL_OVERHEAT: 'Overheat',
        ALLOW_SP: 'SP.',
        SETOVERCOOL: 'Overcool',
        SETOVERHEAT: 'Overheat',
        REF: 'Ref.',
        TRENDS: 'Trends',
        OVERCOO_AREA: 'Overcool',
        OVERHEAT_AREA: 'Overheat',
        INQUIRY: 'Inquiry'
    },
    WOSummary: {
        WO_SUMMARY: 'WO Summary',
        NEW_WO: 'New WO',
        AVERAGE_RESPONCE: 'Responce',
        AVERAGE_COMPLETE: 'Complete',
        COMPLETE: 'Complete',
        RESPONCE: 'Responce'
    },
    diagnosticDetails: {
        EMERGENCY_FAULT_LIST: 'Emergency Fault List',
        RANKING: 'No.',
        FAULT: 'Fault',
        COUNTS: 'Counts',
        SAVING: 'Saving',
        QUERY: 'Query',
        CREATE_WO: 'Create WO',
        ZONE: 'Zone',
        EQUIPMENT: 'Equipment',
        COUNTS: 'Counts',
        FREQUENCY_CHART: 'Frequency Chart',
        NEW_WO: 'New_WO'
    },
    energyConsumption: {
        YEARLY_ENERGY_USE_DIAGRAM: 'Yearly Energy Use Diagram',
        MONTHLY_ENERGY_USE_DIAGRAMM: 'Monthly Energy Use Diagramm',
        DAILY_ENERGY_USE_DIAGRAMM: 'Daily Energy Use Diagramm',
        INQUIRY: 'Inquiry',
        MD_MONITORING: 'MD Monitoring',
        NAME: 'Name',
        RATED_CAPACITY: 'Rated Capacity',
        USAGE: 'Usage',
        USAGE_RATE: 'Usage Rate',
        ENERGY_CONSUMPTION_RANKING: 'Energy Consumption Ranking',
        SUMMARY: 'Summary',
        POWER_CONSUMPTION_FOR: 'Power consumption for',
        YEAR_ON_YEAR_COMPARISON: 'Year-on-Year Comparison',
        MONTH_ON_MONTH_COMPARISON: 'Month-on-Month Comparison',
        CURRENT: 'Current',
        YOY: 'YoY',
        MOM: 'MoM',
        NO_DATA: 'No Data'
    },
    equipmentHealth: {
        EQUIPMENT_HEALTH: 'Equipment Health',
        SHOW_HISTORY: 'History',
        SHOW_HEALTH_EQUIPMENT: 'Show health equipment',
        CHILLER: 'Chiller',
        CT: 'CT',
        SENSOR: 'Sensor',
        PUMP: 'Pump',
        IN_PROCESS: 'In process',
        COMPLETED: 'Completed',
        QUERY: 'Query',
        CREATE_WO: 'Create WO',
        ZONE: 'Zone',
        EQUIPMENT: 'Equipment',
        COUNTS: 'Counts',
        FREQUENCY_CHART: 'Frequency Chart',
        NEW_WO: 'New WO',
        CURRENTLY_NO_FAULT_DETECTED: 'Currently no fault detected'
    },
    tag: {
        firstPage: {
            LET_YOUR_CHANGE_TAG_PAGE: 'The project has not yet been labeled, the system will filter out the key word for you.',
            NEXT_STEP: 'Next Step',
            MANUAL_CLASSIFICATION: 'Manual Classification',
            ONLINE_SEARCH_POINT_ONE: 'System is searching for keywords for you, a total of ',
            ONLINE_SEARCH_POINT_TWO: 'points,',
            ONLINE_SEARCH_POINT_THREE: ' points have been processed.'
        },
        tree: {
            RENAME: 'Rename',
            DELETE: 'Delete',
            RULE: 'Rule',
            ADD: 'Add',
            TAG_RECOGNITION: 'Tag recognition',
            CONFIRM_TO_DELETE_DIRECTORY: 'Confirm to delete directory',
            LESS_THAN_TWO_NODES_MSG: 'Please select two nodes of the tree and then submit',
            FORMAT_SUCCESS: 'Tag format is successful!',
            UNCLASSIFIED_CATALOG: 'Unclassified catalog'
        },
        edit: {
            NO_DATA_RETURNED: 'No data returned',
            NEW_DIRECTORY_NAME: 'Create a new directory name',
            DIRECTORY_EMPTY_ERR: 'The directory name can not be empty',
            SAME_NAME_MERGE: 'Found that the same name of the directory, will merge the two directories, whether to confirm the rename and merge',
            ENTER_NEW_DIRECTORY_NAME: 'Please enter a new directory name',
            GENERATE: 'Generate',
            EDIT_THE_CATALOG: 'Edit the catalog',
            THE_AUTO_MATCH_DEVICE_TYPE: 'Please select the auto match device type',
            NOT_SAVED_IS_ABANDONED: 'New is not saved, is it abandoned?',
            DIRECTORY_EMPTY_MSG: 'The directory name can not be empty',
            SUBDIRECTORY_EMPTY_MSG: 'The subdirectory name can not be empty',
            SUBDIRECTORY_MUST_CONTAIN: 'The subdirectory name must contain {}',
            NUMBER_ERROR: '{} Must have a regular sequence number',
            NUMBER_POSITIVE_INTEGER: 'The rule number is a positive integer',
            CAN_NOT_FIND_RULE: 'Can not find rule ',
            WHETHER: 'Are you sure go on with this rule:',
            PRESS_THIS_RULE: '',
            GENERATE_SUCCESS: 'Generate success',
            SELECT: 'Select',
            POINTS: 'points',
            RECOMMENDED_TAG: 'Recommended Tag',
            SUITABILITY: 'suitability',
            REFERENCE: 'reference',
            APPLICABLE: 'applicable',
            TO: ' to',
            CREATE: '',
            PRODUCE: '',
            KEYWORDS: 'Keywords:',
            NAME: 'Name',
            REMARK: 'Remark',
            VALUE: 'Value'
        },
        inspect: {
            ALL: 'All',
            CATALOGUE: 'Catalogue',
            FINISH_CATALOGUE: 'Finish',
            MODIFY_CATALOGUE: 'Modify',
            FORWARD: 'Forward',
            BACKWARD: 'Backward',
            ADD: 'Add',
            ADD_EMPTY_FILE: 'Add Empty File',
            CATALOGUE_NAME: 'Catalogue: ',
            NEW_CATALOGUE: 'New Catalogue',
            TAG_BRUSH: 'Tag Brush',
            TAG_SOURCE: 'Tag Source',
            TAG_TARGET: 'Tag Target',
            MARK: 'Mark',
            CHECK: 'Check',
            UNMARK: 'Unmark',
            MARKED: 'Marked',
            ROOT_CATALOGUE: 'Root catalogue',
            SELECT_ALL: 'Select all',
            INVERT_SELECTION: 'Invert selection',
            COUNTERMAND: 'Countermand',
            KEYWORDS: 'Keywords',
            CREATE_CATALOGUE: 'Create catalogue',
            CLASSIFICATION: 'Classification',
            COMMON: 'Common',
            COMMON_TAG: 'Common tag',
            NAME_OF_CATALOGUE: 'Catalogue',
            GENERATE_SUBCATALOG: 'Generate subcatalog',
            YES: 'Yes',
            NO: 'No',
            SUBCATALOG_NAME: 'Subcatalog name',
            SUBCATALOG_NAME_RULE_NUMBER: 'Subcatalog name (rule number)',
            RULE: 'Rule',
            RESET: 'Reset',
            RULE_TEST: 'Rule test',
            CREATE: 'Create',
            FIXED_STRING: 'Fixed string',
            FIXED_LENGTH_NUMBER: 'Fixed length number',
            UNSET_LENGTH_NUMBER: 'Unset length number',
            ARBITRARY_STRING: 'Arbitrary string',
            TEST_CONDITION: 'Test condition:',
            WITHIN_THE_RULE: 'Within the rule',
            AGAINST_THE_RULE: 'Against the rule',
            TABLE_CONTENT: 'table of Contents:',
            ADD_THE_SUB_DIRECTORY: 'Add subdirectory',
            CAN_DRAG_CHANGE: 'You can drag the following selected',
            CAN_DRAG_CHANGE_POINT: 'points',
            DEVICE_PARAMETERS: 'Device parameters',
            SURE_CREATE_DIRECTORY: 'Do you want to create a directory based on your keywords?',
            DIRECTORY_SELECTION: 'Directory name selection',
            CREATE_DIRECTORIES: 'Create directories separately',
            CUSTOMIZE: 'customize',
            SYSTEM_SEARCH_FOR: 'The system searches for',
            SYSTEM_SEARCH_FOR_RESULT: 'keywords for sorting',
            SAME_NUMBER: 'digit',
            MODIFY: 'modify',
            ENTER_SEARCH_CONTENT: 'Enter search content',
            ERROR_MESSAGE: 'The error message is: ',
            SURE_RESTORE_VERSION: 'Are you sure to restore the version of {0}?',
            RESTORE_VERSION: 'Restore to version of {0}.',
            ANY_STRING: 'Any string',
            FIXED_LENGTH_STRING: 'Fixed length number',
            NOT_FIXED_STRING: 'Not fixed length',
            TIP_FOR_KEYWORD: 'Tip: You have not yet selected the keywords to create the directory. Please hold down the CTRL key and click on the keyword you want to create the directory!',
            DIRECTORY_NOT_EMPTY: 'Directory name can not be empty!',
            RULE_NOT_EMPTY: 'The rule input can not be empty',
            ENTER_RIGHT_NUMBER: 'Please enter the correct number'
        },
        rule: {
            RULE_DETAIL: {
                0: 'Does not limit anything',
                1: 'Fixed number, letters, symbols, or a combination of such as: abc abc_1 34! A',
                2: 'Continuous digits, such as 345 for 3, fill 3 29989 for 5 digits, fill in 5',
                3: 'The number of bits in the indeterminate number'
            }
        },
        TAG_TYPE: {
            EQUIPMENT: 'Equipment',
            MATERIAL: 'Material',
            PARTS: 'Parts',
            OTHER: 'Other'
        }
    },
    pagePreview: {
        CONFIG: 'config',
        ZOOM: 'zoom:',
        PERCENTAGE: 'Enter percentage',
        CLASSIFICATION_TEMP: 'Classification modal',
        LINE_COLOR: 'Line color',
        SHOW_WIDGET: 'show widget',
        SHOW_POINT: 'show pointName',
        NO_SHOW: 'not show',
        CANSEL: 'cansel',
        SURE: 'sure',
        widget: {
            CANVAS_TEXT: 'canvas text',
            HTML_TEXT: 'html text',
            HTML_BUTTON: 'html button',
            HTML_CONTAINER: 'Html container',
            HTML_SCREEN_CONTAINER: 'html screen container',
            CANVAS_IMAGE: 'canvas image',
            CANVAS_PIPE: 'canvas pipe',
            CANVAS_HEAT: 'canvas heat',
            CANVAS_HEATP: 'canvas heatP',
            HTML_DASHBOARD: 'html dashboard',
            CANVAS_POLYGON: 'polygon',
            CANVAS_LINE: 'line',
        },
    },
   homeModal: {
        nav: {
            OVERVIEW: 'Overview',
            EQUIPMENT_HEALTH: 'Equipment Health',
            DIAGNOSIS: 'Diagnosis',
            PRIORITY_FAULTS: 'Priority Faults',
            ENERGY_ANALYSIS: 'Energy Analysis',
            DATA_MONITORING: 'Key Index',
            DIAGNOSIS_STATISTICS: 'Diagnosis Statistics',
            ENERGY_TREND_ANALYSIS: 'Energy Consumption',
            TEMPERRATURE: 'Temperature',
            HUMIDITY: 'Humidity'
        },
        content: {
            DAILY_TOTAL_ENERGY: 'Energy use today',
            DAILY_TOTAL_ELECTRICITY: 'Electricity bill today',
            ENERGY_SAVING_POTENTIAL: 'Energy saving potential',
            ACCUMULATIVE_ENERGY_SAVINGS: 'Accumulative energy savings',
            TOTAL_FAULTS: 'Total faults',
            UNSOLVED_FAULTS: 'Unsolved faults',
            SOLVED_FAULTS: 'Solved faults',
            POTENTIAL_ENERGY_SAVINGS: 'Energy Savings',
            POTENTIAL_COST_SAVINGS: 'Cost Savings',
            SYSTEM_OUTAGE: 'System outage',
            ENERGY_WASTE: 'Energy waste',
            OTHER: 'Other',
            ENERGY_PAST_OF_THIRTY_DAY: 'Last month',
            ENERGY_LAST_THIRTY_DAY: 'The month before last',
            TOTAL_EQUIPMENT: 'Total equipment',
            FAULT_NUM: 'Fault equipment',
            TEMPERRATURE: '',
            HUMIDITY: '',
            OVER_COOL: 'Overcooled',
            OVER_HEATED: 'Overheated',
            TOO_HIGH: 'Too High',
            TOO_LOW: 'Too Low'
        }
    }
}