var i18n_resource = {
    home: {
        HOME: '首页',
        HEADER_TITLE: '全球领先的物联人工智能平台',
        LEARN_MORE: '了解更多',
        SCROLL_TO_SATAR: '向下滚动',
        OUR_FEATURE: '产品特性',
        FEATURE_CONTENT: 'BeOP产品家族是集合了物联网、人工智能的一站式服务平台。除了创新的垂直解决方案，R&B致力于为各行业开发基础设施级别的智慧服务和智慧硬件。',
        TECHNOLOGY_IOT: '物联网',
        AI_EXPERTISE: '领域纵深的人工智能',
        CLOUD_SERVICE: '云服务',
        ENTERPRISE_APPLICATIONS: '企业级应用',
        TECHNOLOGY_IOT_CONTENT: 'R&B帮助客户搭建灵活安全的数据通道，实现终端（如各类型传感器、控制器等）的数据云接入、节点遍布全球，无论身处何方都能保证低延迟与高质量接入。并且支持Modbus、oBIX等多种主流数据类型接入。稳健的安全机制，无论数据传输、数据存储都有多重安全保障。方便客户随时随地进行数据管理以及远程观察设备数据情况。',
        AI_EXPERTISE_CONTENT: 'BeOP拥有强大智能的数据分析算法，在提供丰富行业算法知识的同时，进行全局状态的高速度响应。同时能够及时发现、解决以及反馈问题，协助用户指导业务运作。并结合专家的资深行业知识，对数据进行“分类”、“统计汇总”以及“生成报表”等操作。实现快速、准确地挖掘数据，提炼数据意义，指导现实业务运作，实现资金收益。',
        CLOUD_SERVICE_CONTENT: '“云服务”提供了稳健的安全机制，数据的传输及存储均有多重安全保证。并且可以随时随地对数据进行监管与处理。它具有易扩充，延展性能好，能够方便接入任意项目以及同时支持企业全球管理的特点。',
        ENTERPRISE_APPLICATIONS_CONTENT: '“企业级应用”是指专门开放给企业级物联网用户，帮助企业级用户完成物联网数据接入、数据清洗和处理、数据展示和挖掘，各流程均提供相应的工具模块。',
        WHY_RB: '为什么选择R&B',
        PIONEER_ENTERPRISE: 'R&B背景',
        RICH_EXPERIENCE: '客户对象',
        ADVANCED_TECHNOLOGY: '技术资本',
        BUSINESS_DIRECTION: '业务方向',
        PIONEER_ENTERPRISE_CONTENT: 'R＆B是中国IoT软件平台的领先供应商之一。将数据实现物联网数据的价值最大化。同时，R&B具有可靠、稳定的资本投资，例如（SIG、JAFCO Asia）。',
        RICH_EXPERIENCE_CONTENT: 'R&B集团注册于香港、美国，在全球各地有着自己的业务，并且与众多国内外的著名企业进行合作，有着多年丰富以及处理各种情形的专业实际经验。',
        ADVANCED_TECHNOLOGY_CONTENT: 'R&B拥有强大的AI团队，结合多位资深业界专家，提供最强大脑。同时也拥有来自国内外强大的技术及支持团队用全球领先技术，提供最用心的交互及展示体验。',
        BUSINESS_DIRECTION_CONTENT: '我们的业务方向从建筑物联走向多行业物联。例如：(智慧楼宇、冷链物流、智能机械等）。提供数据接入、处理、分析展示的一站式平台。',
        OUR_CLINETS: '合作伙伴',
        OUR_CLINETS_CONTENT: 'BeOP拥有强大的机构投资者，并获得各行各业的著名企业的信赖和认可和支持。 我们真诚的期待您的加入。',
        PRODUCT_FEATURE: '产品特性',
        PARTNER: '合作伙伴',
        STATION_MAP: '站点地图',
        OBSERVER: 'Observer',
        FACTORY: 'Factory',
        STRATEGY: '策略组态',
        TAG: 'TAG',
        DIAGNOSIS: '诊断',
        DATA_MANAGEMENT: '数据管理',
        BUILDING_MAINTENANCE: '建筑运维解决方案',
        COLD_CHAIN_LOGISTICS: '冷链物流解决方案',
        IOT_DATA_MANAGMENT: 'IOT数据管理解决方案',
        ENERGY_OPTIMIZATION: '能耗优化解决方案',
        PLATFORM_URSERS: '平台用户解决方案',
        RELATED_DOWNLOAD: '相关下载',
        TECHNICAL_SUPPORT: '技术支持',
        ENTERPRISE_INFO: '公司简介',
        TEAM_INFO: '团队介绍',
        INVESTMENT_PROGRAM: '投资方案',
        NEWS: '新闻',
        TERMINAL_USER: '终端用户',
        PLATFORM_USER: '平台用户',
    },
    product: {
        PRODUCT: '产品',
        FACTORY: {
            BIG_TITLE: '云端组态工具，轻松打造专属数据展示页面',
            SUB_TITLE: '致力于将物联网同大数据呈现在用户面前，提供丰富多彩可视化方法，让您享受轻松愉悦的配置过程并且，这一切都在web中实现。',
            STRATEGY_TEXT: '随心所欲的“组态页面”',
            DASHBOARD_TEXT: '信息高度概括的“Dashboard”',
            REPORT_TEXT: '统计汇总用的“报表”',
            STRATEGY_TEXT_CONTENT: '用户可以轻松的用Factory来创造属于自己的“组态页面”。线上网页直接编辑和更改信息，无复杂的操作步骤，随心所欲的实现自己所想所要。',
            DASHBOARD_TEXT_CONTENT: '根据数据的科学分析，在这基础上，我们进行了将项目的各个方面进行了汇总、分析、研究，最后将信息进行高度概括，用“Dashboard”的形式表现出来，让用户一目了然的可以掌握自己系统，项目的情况。帮助用户节省了人力时间和精力、从茫茫数据中快速定位于解脱出来。',
            REPORT_TEXT_CONTENT: 'Factory具有统计汇总和“报表”的功能，通过“报表”用户可以轻松掌握任何时间段的数据汇总情况，从而更加了解自己的系统和项目。同时，省去人力大量时间的去总结分析只需要点击一下直接下载，转发与同伴分享、讨论。',
            OPERATION_TITLE: '便捷的云端操作',
            LINK_DATA: '一键接入数据',
            LINK_DATA_TEXT: '只需要轻轻点击一下，每分钟百万级的数据轻而易举的实现，而且只需要拖拽便即可接入系统。做到真正的轻松便捷。',
            CREATE_PAGE: '一键生成页面',
            CREATE_PAGE_TEXT: '我们拥有海量的模板，为用户所需要的内容样式提供强而有力的担保。并且这所有的一切，只需要用户拖拽就能一步用户所需的生成页面。',
            PUBLISH_PROJECT: '一键发布项目',
            PUBLISH_PROJECT_TEXT: '随时随地的让用户接入云端进行系统编辑，并且一键发布后，页面立即上线，让用户省去复杂的部署流程。',
        },
        DATAMANAGEMENT: {
            DATA_MANAGEMENT: '数据管理',
            BIG_TITLE: '数据接入、处理等一站式解决方案',
            SUB_TITLE: '轻松高效的筛选、清洗、转换、监管数据。',
            LINK_IOT: '便捷的物联接入',
            LINK_IOT_CONTENT: '数据接入不再是难题，“数据终端”提供人性化的方式，通过简单明了的几步操作，把您的物联网数据接入系统。支持各种复杂度的数据源，例如Modbus、Obix、Excel等等。',
            PRE_DATA: '高效的数据预处理',
            PRE_DATA_SUB_TITLE1: '数据筛选',
            PRE_DATA_SUB_CONTENT1: '原始数据绝大部分是冗余的，筛选功能可以识别、过滤无效数据。',
            PRE_DATA_SUB_TITLE2: '数据清洗',
            PRE_DATA_SUB_CONTENT2: '外界环境因素复杂（例如设备断电），会导致时间维度上的数据停更、数据异常等。清洗功能，可以智能平滑、补齐数据。',
            PRE_DATA_SUB_TITLE3: '数据转换',
            PRE_DATA_SUB_CONTENT3: '可以任意替换数据，可以将任意数据导出为Word、Excel、PDF。',
            TAG_TITLE: '用Tag',
            TAG_CONTENT: '增加数据可读性',
            TAG_SUB_TITLE1: '使人容易理解',
            TAG_SUB_CONTENT1: '通过IoT接入数据点名会比较复杂冗余，可读性极低。但是使用Tag之后，可以让您和他人轻松的掌握与数据有关的所有信息。',
            TAG_SUB_TITLE2: '使机器更加智能',
            TAG_SUB_CONTENT2: '通过人工智能，我们可以更加精准的定位所需要的数据，可以为客户自动化的带来更多、精准的分析结果。',
            TAG_SUB_TITLE3: '简化数据使用流程',
            TAG_SUB_CONTENT3: '通过技术，客户可以使用更多的辅助工具，简化繁琐的操作流程，极大的减少了人工的工作量。',
            TAG_SUB_TITLE4: '简单的Tag标记',
            TAG_SUB_CONTENT4: '我们会提供先进的技术手段，经过简单的操作，S即可完成Tag的标记工作。',
            MAINTAIN_TITLE: '轻松的数据维护',
            MAINTAIN_SUB_TITLE1: '数据分析',
            MAINTAIN_SUB_TITLE2: '数据报警',
            MAINTAIN_SUB_TITLE3: '数据诊断',
            MAINTAIN_SUB_TEXT1: '通过图表等展现形式，让用户一目了然的找出数据中存在 的风险，来进行预防、保证项目顺利进行，并且掌握数据 的规律，并进行总结，让用户更好的掌握系统。',
            MAINTAIN_SUB_TEXT2: '通过数据的分析和一定的前沿边界条件，智能提示报警， 让用户第一时间了解和采取措施，来减少不必要的损失。',
            MAINTAIN_SUB_TEXT3: '这是一个更高级的数据管理工具，通过简单的编程实现复杂多变的逻辑，让机器学会您的经验，让您从枯燥、复杂的 数据中解放出来。',

        },
        OBSERVER: {
            DATA_MANAGEMENT: 'Observer',
            BIG_TITLE: '云端大数据可视化平台',
            SUB_TITLE: 'Observer 通过报表、Dashboard、组态图等展现形式，将项目全方位呈现在您的面前，使您可以方便的发现、解决问题，查看、回顾、存档项目的状态。',
            FAST_POS: '快速定位',
            PAGE_STYLE: '丰富的页面形式。',
            PAGE_STYLE_TEXT: '报表、Dashboard、系统图等，能满足各种应用场景',
            PAGE_CHART: '丰富的数据图表。',
            PAGE_CHART_TEXT: '从不同维度展现数据，引导用户从不同角度掌握问题。',
            ADVANCED_PRE_DATA: '高效的数据预处理',
            TIME_DEEP: '时间维度的任意纵深。',
            TIME_DEEP_TEXT: '所有页面类型，在展现当前实时数据的同时，均可一键切换到任意历史时间，方便的回顾问题、发现规律。',
            ANY_PAGE: '可任意定制页面。',
            ANY_PAGE_TEXT: '所有页面均可通过Factory组态，用过Algorithm Developer开发页面逻辑。',
            IO_ECHART: '便捷的数据、图表导入导出。',
            IO_ECHART_TEXT: '可以任意替换数据，可以将任意数据导出为Word、 Excel、PDF',
            SCALABILITY: '具有高扩展性',
            VARIETY_SOLUTIONS: '支持多种解决方案',
            VARIETY_SOLUTIONS_TEXT: '有丰富的解决方案。除了在常见的解决方案例，我们根据 不同行业的不同情况提出不同的、多样化的解决方案， 以此满足不同客户的需求。',
            ORDER_SYSTEM: '与工单系统对接',
            ORDER_SYSTEM_TEXT: '利用Observer可以随时随地的操作工单， 简单方便的操作工单，来解决工作上的问题 并且能随时跟踪，让问题解决更加方便。',
            MOBILE_SUPPORT: '移动端支持',
            MOBILE_SUPPORT_TEXT: '我们不仅仅在web中实现，所有的页面都可以 支持移动端，真正的实现随时随地， 帷幄在手的去管理您的项目。'
        },
        STRATEGY: {
            STRATEGY_TITLE: 'Algorithm Developer',
            BIG_TITLE: '云端可视化编辑工具。',
            SUB_TITLE: 'Algorithm Developer 致力于发挥您的专业特长，让您无需任何编程基础，亦可实现数据分析数据处理、算法逻辑，更好的掌握您的系统。',
            DATA_ANALYSIS: '数据分析',
            DATA_ANALYSIS_TITLE1: '云端生成、调试、控制算法',
            DATA_ANALYSIS_TITLE2: '算法一经发布即时运行。',
            DATA_ANALYSIS_TITLE3: '丰富的算法工具。',
            DATA_ANALYSIS_CONTENT3: '一步定位到海量的关键参数，轻松实现数据预处理， 多样的数据展示形式',
            DATA_ANALYSIS_TITLE4: '无需任何编程知识。',
            DATA_ANALYSIS_CONTENT4: '用户再也不用担心自己不懂编程而不能实现数据的 分析，整个操作过程简单、易操作。',
            BULID_DIAGNOSIS: '生成诊断',
            BULID_DIAGNOSIS_CONTENT: '在诊断里可以配置算法逻辑，并且基于大数据掌握系统所有的运行情况。 以便用户全方位的对系统进行查看、检查和修复， 让用户更加简单、方便的掌握系统。',
            BULID_DIAGNOSIS_TITLE1: '快速实现系统级算法配置',
            BULID_DIAGNOSIS_TITLE1_CONTENT: '在几分钟内，就能够帮助用户快速、简单的实现系统级的算法配置，省去了繁琐的操作步骤，轻松快捷的完成算法配置。',
            BULID_DIAGNOSIS_TITLE2: '提供丰富的算法模板',
            BULID_DIAGNOSIS_TITLE2_CONTENT: '在Algorithm Developer中我们有着丰富的算法模板，用户能够简单快捷的添加算法模板，节省学习成本。',
            BULID_DIAGNOSIS_TITLE3: '可自定义算法',
            BULID_DIAGNOSIS_TITLE3_CONTENT: '在Algorithm Developer中，用户可以方便简洁的实 现自定义的算法。实现用户自己想要的效果。',

        },
        PRODUCT_TERMINAL: '终端产品',
        PRODUCT_PLATFORM: '平台产品',
        ELECTRONIC_WORKFLOW: '电子工作流',
        KPI_MANAGE: '智能KPI管理',
        AUTO_REPORT: '自动化报表',
        ENERGY_MANAGE: '能源管理',
        AUTO_DIAGNOSIS: '自动故障诊断',
        AUTO_ENERGY_ANALYSIS: '自动能效分析',
        PLATFORM: {
            TITLE: '平台用户',
            CONTENT: ' 在平台用户上我们提供个性化的原创内容，让用户享有更好、便捷的内容和服务。',
            TITLE_ONE: '数据接入',
            CONTENT_ONE: 'Beop平台让数据接入不再是难题，“数据终端”提供人性化的方式， 通过简单明了的几步操作，把您的物联网数据接入系统。 支持各种复杂的数据源，例如：Modbus、oBIX、 Excel等等。',
            BOTTOM: '了解更多',
            TITLE_TWO: '数据处理',
            CONTENT_TWO: '数据处理通过对原始数据提供了高效的数据预处理方案，包括筛选、数据清洗、数据转 化及数据的标记等。',
            TITLE_THREE: '算法组态',
            CONTENT_THREE: '算法组态工具致力于发挥您的专业特长，让您无任何编程基础亦可 实现数据分析、数据处理、算法逻辑， 更好的掌握您的系统。',
            TITLE_FOUR: '数据可视化',
            CONTENT_FOUR: '数据可视化工具致力于物联网同大数据呈现在用户面前，提供丰富多彩的可视化方法， 让您享受轻松愉悦的配置过程。并且，这一切都在Web中实现。',
        },
        TERMINAL: {
            TITLE: '终端用户',
            CONTENT: ' 在平台用户上我们提供个性化的原创内容，让用户享有更好、便捷的内容和服务。',
            ELE_TITLE: '电子工作流',
            ELE_CONTENT: '实现从实时数据到行动的自动化和信息化，追踪故障从发生到处理的流程、状态及效率，实现全过程可视化。',
            KPI_TITLE: '智慧KPI管理',
            KPI_CONTENT: '报表可根据用户需求定制，自动生成，支持多种格式下载，极大降低人工制表的时间投入。',
            AUTO_REPORT: '自动化报表',
            AUTO_REPORT_TEXT: '报表可根据用户需求定制，自动生成，支持多种格式下载，极大的降低了人工制表的时间投入。',
            ENERGY_TITLE: '能源管理',
            ENERGY_TEXT: '提供完整的在线能源管理服务，包括能效审计，能效对标与诊断，测量与验证，投资回报分析，自动报表等一系列能源管理云服务，极大提高了能源管理业务的工作效率。',
            AUTO_DIA_TITLE: '自动故障诊断',
            AUTO_DIA_TEXT: '通过对历史和实时数据的分析，BeOP可实时探测到设备与系统存在的故障和不合理的运行，并诊断其原因。',
            AUTO_ANALY_TITLE: '自动能效分析',
            AUTO_ANALY_TEXT: '基于强大的行业算法库，自动生成能效异常的原因分析及报表。不仅可以为单体客户分析能效，更可以为集团客户进行多项目分析比较。'
        }
    },
    Solution: {
        SOLUTION: '解决方案',
        TITLE: '升宝基于服务各大企业的经验，深刻理解企业真实的需求，聚焦智能能源管理系统，为您提供建筑运维、冷链物流、IOT数据管理、能耗优化、平台用户等服务',
        TITLE_ONE: '建筑运维解决方案',
        CONTENT_ONE: '对建筑设备设施全面实时监控，用KPI对运维评估，分析运维方案的优劣，根据历史运维行为自学习，从而给出优化建议。',
        BTN: '了解更多 →',
        TITLE_TWO: '冷链物流解决方案',
        CONTENT_TWO: '提供冷链数据监测功能，车辆追踪功能以及运输和存储过程中的温度情况。同时可对工作人员排班，记录其工作路径和状态。',
        TITLE_THREE: 'IoT数据管理解决方案',
        CONTENT_THREE: '便捷的数据接入，快速批量整理数据，用统一的语言标记数据，后期应用可按设备整体辨识引用数据。',
        TITLE_FOUR: '能耗优化解决方案',
        CONTENT_FOUR: '一体化管理工具深入挖掘节能潜力，给出专业运行建。能耗管理实现实时能耗监控，历史能耗查询，能耗故障诊断，能耗对标以及能耗报表',
        TITLE_FIVE: '平台用户解决方案',
        CONTENT_FIVE: '数据接入→数据识别与清洗→诊断图形化工具→webfactory页面制作工具提供完整的工具和大量模板，让平台用户快速完成从现场数据到网站页面制作。'
    },
    Support: {
        SUPPORT: '技术支持',
        DOWNLOAD: '相关下载',
        BTN: '点击下载',
        BEOP: 'BeOP APP',
        APP: '智能温控 APP',
        FACTORY: 'Factory 桌面版',
        CORE: 'Core',
        DOWNLOADTIP: '本次下载安卓版。如需ios版，请点击链接。'
    },
    About: {
        ABOUT_US: '关于我们',
        COMPANY_INFO: 'R&B科技集团是一家结合人工智能和垂直行业（如：楼宇能源管理）应用的先驱企业。除了创新的垂直解决方案，R&B致力于为各行业开发基础设施级别的智慧服务和智慧硬件。R&B的核心自主技术完全由数据驱动，通过将原始数据自动转换为有意义的商业信息，并以自然语言表达，从而实现极大程度的效率提升。\
        R&B集团注册于美国和香港，业务总部设立于上海。R&B得到全球知名风投的资金支持，现有超过90名员工，并在全球范围内发展业务。\
        ',
        TEAM_MANAGEMENT: '管理团队',
        TEAM_TITLE: '我们的管理团队来自各个领域，有着优秀的学历背景、和深刻的、资深专业知识和多年的经验。并且亲切、团结的团队气氛。尊重每一个个体、扁平化管理。',
        MEMBER_NAME_1: '王豪源',
        MEMBER_WORK_1: '创办人、CEO',
        MEMBER_WORKINFO_1: '主要负责日宝集团的资金筹措以及市场开拓，曾任职于香港的华富集团，在行业中拥有充足的业务网络以及管理经验，毕业于加拿大温哥华British Columbia大学。',
        MEMBER_NAME_2: '吴刚',
        MEMBER_WORK_2: '创办人、COO以及CTO',
        MEMBER_WORKINFO_2: '在建筑领域有用超过15年的丰富经验，主要负责日宝集团的产品开发和战略，毕业于美国Carnegie Mellon University，专业于楼宇性能与诊断。',
        MEMBER_NAME_3: '顾道金',
        MEMBER_WORK_3: '产品总监',
        MEMBER_WORKINFO_3: '清华大学博士，10年以上暖通空调以及楼宇管理系统研究与开发经验，在学术兴趣领域内取得各项前端科技成就，在加入日宝集团之前曾就职于江森自控。',
        MEMBER_NAME_4: '聂青阳',
        MEMBER_WORK_4: '开发总监',
        MEMBER_WORKINFO_4: '毕业于上海交通大学计算机专业，曾就职于微软、摩根士丹利等世界500强企业，并为微软获得一项专利，拥有10年以上IT研发和管理经验。',
        MEMBER_NAME_5: '王飞',
        MEMBER_WORK_5: '工程总监',
        MEMBER_WORKINFO_5: '理学学士,在项目管理以及暖通空调和楼宇管理系统的项目执行方面拥有超过15年的丰富经验，曾就职于特灵空调。主要负责升宝集团的资金筹措以及市场开拓，曾任职于香港的华富集团，在行业中拥有充足的业务网路以及管理经验，毕业于加拿大温哥华British Columbia',
        MEMBER_NAME_6: '马伟楠',
        MEMBER_WORK_6: '首席科学家',
        MEMBER_WORKINFO_6: '曾就职于美国Broadcom Inc.以及Xpliant Inc，在特定用途集成电路设计领域有超过8年工作经验。毕业于美国Carnegie Mellon University，电子和计算机工程专业。',
        COO_NAME: '吴',
        COO_WORK: '创办人、COO、CTO',
        COO_WORK_INFO: '',
        CST_NAME: '马伟楠',
        CST_WORK: '首席科学家',
        CST_WORK_INFO: '',
        INSTITUT_INVERST: '机构投资',
        SIG_CONTAINER: 'SIG在中国的风险投资和私募股权投资活动过海纳亚洲创投基金(SAI)， SIG设于上海的全资境外企业来进行。SIG中国团队具有完全的判断力将资金运用于风险投资及私募股权投资等投资管理活动。',
        JAFCO_CONTAINER: '集富亚洲于1990年成立，亚洲领先的风险投资基金。专注于投资中早期高增长的技术企业，总基金管理规模超过13亿美元。我们的目标是与优秀的企业家一起构建成功的企业，并帮助投资者获得良好的投资回报。 集富也是一家全球性的风险投资机构, 在亚洲、日本和美国均有成功的投资案例。',
        LEARN_MORE: '了解更多',
        OUR_NEWS: '我们的新闻',
        RECENT_NEWS: '最近新闻',
        SIX_YEAR_NEW: '2016年',
        FIVE_YEAR_NEW: '2015年',
        FOUR_YEAR_NEW: '2014年',
        THREE_YEAR_NEW: '2013年',
        CHECK_MORE: '查看所有',
        D201607_DATE: '2016-07',
        D201606_DATE: '2016-06',
        D201604_DATE: '2016-04',
        D201603_DATE: '2016-03',
        D201601_DATE: '2016-01',
        D201512_DATE: '2015-12',
        D201501_DATE: '2015-01',
        D201404_DATE: '2014-04',
        D201309_DATE: '2013-09',
        D201607_NEW: '跟全球最大的资产管理公司CBRE签署战略合作协议',
        D201606_NEW: '参展2016年realcomm展会',
        D201604_NEW: '发布移动端温控APP，支持IOS系统</br>发布面向高端商业楼宇的IoT应用解决方案',
        D201603_NEW: '发布服务于生态圈开发者和合作伙伴的组态、调试工具等平台工具。',
        D201601_NEW: '发布为复杂机械设备和IoT的智慧云服务',
        D201512_NEW: '发布BeOP云平台2.0</br>发布2.0支持移动端、完成B轮融资',
        D201501_NEW: '发布BeOP云平台1.0</br>提供面向工程和楼宇能源设施的智慧服务',
        D201404_NEW: '完成A轮融资',
        D201309_NEW: '发布现场数据采集工具Core1.0以及observer桌面版软件',
        OUR_MISSION: '我们的使命',
        ABOUT_TOP_TEXT: '我们秉承诚信的理念，以提供真实的能效优化为责任，为客户奉献我们创新的产品与服务'
    },
    Contact: {
        CONTACT: '联系我们',
        CONTACTCONTENT: 'R&B邀您进入人工智能平台',
        CONTACTCONTENT_ONE: '共同迎接美好未来！',
        ADDRESSTITILE: '联系地址',
        TITLE_ONE: '75 Executive Drive, Suite 106, Aurora, IL 60504',
        COMPANY_ONE: '公司名称：R&B Tech Co., Ltd',
        DETAIL: '联系方式',
        CODE: '邮编',
        PHONE: 'Phone',
        TITLE_TWO: '中国上海祖冲之路2290弄1号楼103室',
        COMPANY_TWO: '公司名称：升宝节能技术（上海）有限公司',
        TITLE_THREE: '香港威菲道路18号万国宝通中心19楼',
        COMPANY_THREE: '公司名称：升宝节能技术（香港）有限公司',
        EMAIL:'邮箱',
        SHANGHAI:'上海',
        HONGKONG:'香港',
        AMERICA:'美国'
    },
    ColdChain: {
        SUBTITLE: '提供冷链数据监测功能，车辆追踪功能以及运输和存储过程中的温度情况。同时可对工作人员排班，记录其工作路径和状态。',
        ITEM_TITLE_ONE: '精准定位冷链车辆',
        ITEM_TITLE_DESC_ONE: '网页实时体现车辆的位置、轨迹，同时监控车辆内温度情况，以及追溯车辆历史行程',
        ITEM_TITLE_TWO: '统一管控冷库',
        ITEM_TITLE_DESC_TWO: '可查询项目的所有冷库位置，实时监控温度和设备运行状况',
        ITEM_TITLE_THREE: '精简实用的冷链运行报警',
        ITEM_TITLE_DESC_THREE: '自定义冷库温度上下限，实时报警'
    },
    Iot: {
        SUBTITLE: '便捷的数据接入，快速批量整理数据，用统一的语言标记数据，后期应用可按设备整体辨识引用数据',
        SEC_TITLE: '功能与优势',
        ITEM_TITLE_ONE: '现场直接导入且支持多样协议',
        ITEM_TITLE_DESC_ONE: 'BeOP的数据终端模块支持不同协议的数据导入，且用户可在线快速接入',
        ITEM_TITLE_TWO: '快速数据整理与标记',
        ITEM_TITLE_DESC_TWO: '对多种命名方式的点名进行统一语言的标记，清洗数据，形成物理数据结构',
        ITEM_TITLE_THREE: '精准的IoT诊断',
        ITEM_TITLE_DESC_THREE: '行业知识与智能学习相结合，深度挖掘数据的意义，最终形成适合的运行建议',
        BOTTOM_TITLE: '使用步骤',
        BOTTOM_CONTENT_ONE: '数据接入',
        BOTTOM_CONTENT_TWO: '数据初步整理',
        BOTTOM_CONTENT_THREE: '数据标识',
        BOTTOM_CONTENT_FOUR: '数据清洗和计算',
        BOTTOM_CONTENT_FIVE: '根据行业撰写诊断',
        BOTTOM_CONTENT_SIX: '搭建页面'
    },
    Energy: {
        SUBTITLE: '一体化管理工具深入挖掘节能潜力，给出专业运行建议。能耗管理实现实时能耗监控，历史能耗查询，能耗故障诊断，能耗对标以及能耗报表',
        ITEM_TITLE_ONE: '清晰的能耗展示',
        ITEM_TITLE_DESC_ONE: '将能耗按设备、时间进行分项计量，清晰观察能耗的主要影响时段和影响因素',
        ITEM_TITLE_TWO: '灵活自定义计量',
        ITEM_TITLE_DESC_TWO: '为满足多种业态的建筑，BeOP支持自定义计量，可根据不同节点的电表数据，进行合并或拆解，满足业务需求',
        ITEM_TITLE_THREE: '相似项目对标',
        ITEM_TITLE_DESC_THREE: '支持与相似项目的运行行为和能耗进行对比，相互学习和纠正',
        RIGHT_TITLE: '关键特性',
        ITEM_TITLE_FOUR: '模块化服务',
        ITEM_TITLE_DESC_FOUR: '数据展示模块化，适用于不同的项目，迅速搭建和展示',
        ITEM_TITLE_FIVE: '大数据项目基础',
        ITEM_TITLE_DESC_FIVE: '多年的项目积累提高了不同项目间能耗对标的可能性，大量数据支撑运行逻辑',
    },
    Platform: {
        SUBTITLE: '数据接入 —— 数据识别预清洗 —— 诊断图形化工具 —— webfactory页面制作工具，提供完整的工具和大量模板，让平台用户快速完成从现场数据到网站页面制作',
        ITEM_TITLE_ONE: '简便的项目创建机制',
        ITEM_TITLE_DESC_ONE: '从项目创建到项目数据接入过程中，用完善的流程指导平台用户独自完成',
        ITEM_TITLE_TWO: '适用于多个行业',
        ITEM_TITLE_DESC_TWO: '通用的数据整理、清洗、标识、计算、展示工具，使得BeOP可服务于多个行业，为平台用户提供多样的可能性',
        ITEM_TITLE_THREE: '展示组件化',
        ITEM_TITLE_DESC_THREE: '数据展示网页的图表、文字等组件化，平台用户可对不同元素拼接快速生成网页，网页风格统一，样式美观',
        RIGHT_TITLE: '关键特性',
        ITEM_TITLE_FOUR: '降低对人员技能的需求',
        ITEM_TITLE_DESC_FOUR: '平台内置的代码功能，将其以图形和模块化形式呈现，无需人员配备专业互联网开发基础',
        ITEM_TITLE_FIVE: '节约项目搭建时间',
        ITEM_TITLE_DESC_FIVE: '组件化和明细的步骤指导，有效提高项目搭建效率',
        BOTTOM_TITLE: '流程',
        BOTTOM_CONTENT_ONE: '数据接入',
        BOTTOM_CONTENT_TWO: '数据处理',
        BOTTOM_CONTENT_THREE: '算法组态',
        BOTTOM_CONTENT_FOUR: '数据可视化'
    },
    BuildingMaintenance: {
        SUBTITLE: '对建筑设备设施全面实时监控，用KPI对运维评估，分析运维方案的优劣，根据历史运维行为自学习，从而给出优化建议',
        ITEM_TITLE_ONE: '运行监测',
        ITEM_TITLE_TWO: '报表',
        ITEM_TITLE_THREE: 'KPI评价体系',
        ITEM_TITLE_FOUR: '能耗及费用报表',
        ITEM_TITLE_FIVE: '诊断',
        ITEM_TITLE_SIX: '简化日常抄表',
        ITEM_TITLE_SEVEN: '简化资产管理',
        ITEM_TITLE_EIGHT: '简化巡更系统',
        ITEM_TITLE_NINE: '工单系统',
    },
    News: {
        ALL_NEWS: '所有新闻',
        YEAR_ONE: '2016年',
        YEAR_ONE_TITLE_ONE: '2016年07月',
        YEAR_ONE_TITLE_TWO: '2016年06月',
        YEAR_ONE_TITLE_THREE: '2016年04月',
        YEAR_ONE_TITLE_FOUR: '2016年03月',
        YEAR_ONE_TITLE_FIVE: '2016年01月',
        YEAR_ONE_DESC_ONE: 'R&B跟全球最大的资产管理公司CBRE</br>签署战略合作协议',
        YEAR_ONE_DESC_TWO: 'R&B参加2016年realcomm展会',
        YEAR_ONE_DESC_THREE: '发布移动端温控APP，支持IOS系统</br>发布面向高端商业楼宇的IoT应用的解决方案',
        YEAR_ONE_DESC_FOUR: '发布服务于生态圈开发者和合作伙伴的</br>组态、调试工具等平台工具',
        YEAR_ONE_DESC_FIVE: '发布为复杂机械设备和IoT的智慧云服务',
        YEAR_TWO: '2015年',
        YEAR_TWO_TITLE_ONE: '2015年12月',
        YEAR_TWO_TITLE_TWO: '2015年01月',
        YEAR_TWO_DESC_ONE: '发布BeOP云平台2.0</br>发布2.0支持移动端、完成B轮融资',
        YEAR_TWO_DESC_TWO: '发布BeOP云平台1.0，提供面向工程和</br>楼宇能源设施的智慧服务',
        YEAR_THREE: '2014年',
        YEAR_THREE_TITLE_ONE: '2014年04月',
        YEAR_THREE_DESC_ONE: 'R&B成功完成A轮融资',
        YEAR_FOUR: '2013年',
        YEAR_FOUR_TITLE_ONE: '2013年09月',
        YEAR_FOUR_DESC_ONE: 'R&B发布现场数据采集工具Core 1.0</br>以及observer桌面软件',
    }
};