var i18n_resource = {
    echarts: {
        MARK: '辅助线开关',
        MARKUNDO: '删除辅助线',
        MARKCLEAR: '清空辅助线',
        DATAZOOM: '区域缩放',
        DATAZOOMRESET: '区域缩放还原',
        DATAVIEW: '数据视图',
        CLOSE: '关闭',
        REFRESH: '刷新',
        LINE: '折线图',
        BAR: '柱形图',
        STACK: '堆积',
        TILED: '平铺',
        FORCE: '力导向布局图',
        CHORD: '和弦图',
        PIE: '饼图',
        FUNNEL: '漏斗图',
        REDUCTION: '还原',
        SAVE_AS_PICTURE: '保存为图片',
        SAVE: '保存'
    },
    admin: {
        login: {
            PANE_TITLE: "登 录",
            PANE_CHECKBOX_REMEMBER: "记住",
            PANE_CHECKBOX_REMEMBER2: "记住密码",
            PANE_PLACEHOLDER_ACCOUNT: "请输入用户名",
            PANE_PLACEHOLDER_PWD: "请输入密码",
            LOG_IN_FAILED: '登录失败',
            LOG_IN_TOKEN_EXPIRED: '登录凭证过期，请重新登录',
            LOG_IN_EMPTY: '请输入用户名和密码',
        },
        welcom: {
            start: {
                TITLE: '开始',
                NEW_PROJECT: '新建项目...',
                IMPORT_PROJECT: '导入项目...',
            },
            yourProj: {
                TITLE: '您的项目',
                DELETE: '删除',
                TOP: '置顶',
                EXPORT: '导出',
                EDIT_AUTH: '编辑项目权限',
                EDITE_PRO: '编辑'
            },
            newProj: {
                ADD_PROJECT: '新增项目',
                PROJECT_NAME: '项目名称：',
                PROJECT_CHINESE_NAME: '项目中文名称：',
                PROJECT_ENGLISH_NAME: '项目英文名称：',
                ADD: '新增',
                ADD_ONLINE: '生成在线项目',
                CANSEL: '取消',
                PROJECT_NAME_NEW_PLACEHOLDER: '请输入项目的名称',
                PROJECT_NAME_PLACEHOLDER: '请输入项目名称',
                PROJECT_CHINESE_NAME_PLACEHOLDER: '请输入项目中文名称',
                PROJECT_ENGLISH_NAME_PLACEHOLDER: '请输入项目英文名称',
                LOG_ADD: '项目名称不能为空！',
                LOG_SAME_NAME: '项目已存在'
            },
            deleteProj: {
                DELETE_PROJECT: '删除项目',
                CONFIRM_INFO: '请确认是否删除项目？',
                CONFIRM_INFO_TIP: '请输入密码',
                SURE: '确认删除',
                CANCEL: '取消',
                DELETE_TITLE: '删除项目',
                PASSWORD: '密    码：',
                PROJECT_ENGLISH_NAME: '项目英文名称：',
                PASSWORD_PLACEHOLDER: '请输入密码',
                PROJECT_ENGLISH_NAME_PLACEHOLDER: '请输入项目的英文名称',
                OK: '确定'
            },
            importProjectModal: {
                TITLE: '导入线上项目',
                PROJECT_LIST_LABEL: '线上项目列表',
                CONFIRM_IMPORT: '确认导入',
                CANCEL: '取消'
            },
            addByTpl: {
                APPLY_TEMP: '应用模板',
                TEMP_NAME: '模板名称',
                PAGE_NAME: '页面名称',
                REPLACE_STR: '替换点名字符串',
                REPLEASE_AS: '替换为',
                SURE: '确定',
                BATCH_PLACE: '批量占位符',
                BATCH_PAGE: '批量页面名称',
                PAGE_NAME_EG: '如: myPage',
                REPLACE_STR_EG: '如: chiller01',
                REPLEASE_AS_EG: '如: chiller02',
                BATCH_PLACE_EG: '{x:["1","a"]} 或 {x: {min: 2, max: 10, step: 1}}',
                BATCH_PAGE_EG: '如: myPage<#x#>',
                SAVE_TEMP_FAIL: '保存模板失败',
                TEMP_DATA_FAIL: '该模板的数据不符合规范',
                PLACEHOLDER_NONE: '请填写占位符',
                PAGE_NAME_NONE: '请填写页面名',
                BATCH_PAGE_NAME_CFG_NONE: '名称批量设置为空',
                PAGESCREEN_ADD_SUCCESS: '添加PageScreen成功'
            }
        },
        navIndex: {
            LINK_LANGUAGE: "语言"
        },
        projectCreator: {
            REGIST_STEP1_TITLE: '创建项目',
            REGIST_STEP1_TITLE_2: '修改项目',
            REGIST_STEP2_TITLE: '导入数据',
            REGIST_PREV_STEP_TITLE: '上一步',
            REGIST_NEXT_STEP_TITLE: '下一步',
            REGIST_SUBMIT_TITLE: '完成',
            PANE1_TITLE: '欢迎使用Beop系统，如果您是第一次使用，请根据引导逐步实现Beop项目的新建，祝您有一次愉快的体验。',
            PANE1_FORM_ITEM1_LABEL: '项目代码',
            PANE1_FORM_ITEM1_PLACEHOLDER: '请输入您的项目代码',
            PANE1_FORM_ITEM1_TIP: '注：项目代码只能包含英文字母和数字',
            PANE1_FORM_ITEM2_LABEL: '项目中文名',
            PANE1_FORM_ITEM2_PLACEHOLDER: '请输入您的项目中文名',
            PANE1_FORM_ITEM2_TIP: '注：项目中文名只能包含中文汉字',
            PANE1_FORM_ITEM3_LABEL: '项目英文名',
            PANE1_FORM_ITEM3_PLACEHOLDER: '请输入您的项目代码',
            PANE1_FORM_ITEM3_TIP: '注：项目英文名只能包含英文字母和数字',
            PANE1_FORM_ITEM4_LABEL: '项目地址',
            PANE1_FORM_ITEM4_PLACEHOLDER: '请在地图中点选您的项目地址',
            PANE1_FORM_ITEM4_TIP: '注：不支持人工填写，请在地图上点选项目的实际位置',
            PANE1_FORM_ITEM5_LABEL: '项目图片（点击图片进行修改）',
            PANE2_TITLE: '好的！现在导入项目数据以正常使用网站功能，您也可以选择跳过此步骤。',
            PANE2_FORM_ITEM1_LABEL: '请选择需要导入的数据（支持文件拖拽上传）：',
            PANE2_FORM_ITEM1_TIP1: '（请选择文件）',
            PANE2_FORM_ITEM1_TITLE: '上传文件',
            PANE2_FORM_ITEM1_TIP2: '注：目前导入格式支持 csv/xls/xlsx 格式，请注意检查。',
            PANE2_TABLE_TITLE: '示例数据',
            ERROR_NOT_EMPTY: '项目名称不能为空!',
            ERROR_WRONG_CRITERIA: '项目名称只能包含英文字母和数字!',
            ERROR_EXIST_NAME: '该项目名称已经存在，请重新输入!',
            ERROR_NOT_CHOOSE_ADDRESS: '请在地图中选择项目地址!',
            CHANGE_MAP_TO_AMAP: '切换到高德地图',
            CHANGE_MAP_TO_GOOGLE: '切换到谷歌地图',
            CHANGE_MAP_ERROR: '切换地图错误，不存在地图实例',
            PJ_REALITY_VALUE_TIPS_DEFAULT: "注：请输入正确的项目标识",
            PJ_REALITY_VALUE_TIPS_SUCCESS: "项目标识输入正确",
            PJ_REALITY_VALUE_TIPS_FAILED: "请输入正确的项目标识",
            PJ_REALITY_VALUE_TIPS_SERVER_ERROR: "服务器错误：检测真实项目标识失败",
            PJ_REALITY_VALUE_TIPS_PLACEHOLDER: "请输入正确的项目标识",
            PJ_REALITY_VALUE_TIPS_TITLE: "项目标识",
            PJ_TIME_FORMAT: "时间格式",
            PJ_TYPE_IDENTIFICATION: '项目类型和标识',
            REAL_PROJECT: '真实项目',
            VIRTUAL_PROJECT: '虚拟项目',
            REAL_DATA: '实时数据标识',
            HISTORICAL_DATA: '历史数据标识',
            PJ_REAL_DATA_IDENTIFICATION_IS_RIGHT: '实时数据标识输入正确'
        }
    },
    workflow: {
        memberSelected: {
            TITLE: "请选择人员",
            TITLE1: "请查看人员",
            INPUT_INFO: "请输入用户名称",
            ALL: '全部',
            MEMBER_SELECTED: '已选成员',
            INFO_READONLY: '只能查看，不能选择'
        }
    },
    dataSource: {
        ADD_GROUP: '+ 添加分组',
        ADD_POINT_GROUP: '添加分组',
        ADD_POINT: '添加点',
        ADD_FORMULA: '添加公式',
        RENAME: '重命名',
        REMOVE: '删除'
    },
    observer: {
        observerScreen: {
            DIALOG_TITLE: "详情",
            TEXT_EDITOR_CONFIRM: '确认',
            TEXT_EDITOR_SEND_SUCCESS: '数据设置成功',
            TEXT_EDITOR_SEND_FAIL: '数据设置失败',
            TEXT_ADD_TO_DATASOURCE: '加入数据源'
        }
    },
    toolBox: {
        TITLE: '可选模块',
        modal: {
            HIS_CHART: '历史图',
            HIS_CHART_ENERGY_LINE: '历史柱状图(年/月/周)',
            HIS_CHART_ENERGY_BAR: '历史能耗柱图',
            HIS_CHART_YEAR_LINE: '历史同比折线图',
            HIS_CHART_YEAR_BAR: '历史同比柱图',
            HIS_CHART_ANALYSE: '历史数据分析',
            REAL_TIME_CHART: '实时图',
            REAL_TIME_CHART_PIE_ENERGY: '实时饼图',
            REAL_TIME_CHART_PIE_DATAROOM: '数据机房分项能耗饼图',
            REAL_TIME_CHART_LINE_OUTDOOR: '实时折线/柱图',
            REAL_TIME_CHART_LINE_PUE: 'PUE趋势',
            REAL_TIME_CHART_GAUGE: '实时仪表盘',
            REAL_TIME_CHART_BAR_ENERGY: '分项柱图',
            REAL_TIME_CHART_LINE_ENERGY: '分项能耗折线图',
            REAL_TIME_CARBON_FOOTPRINT: '碳足迹排放量',
            REAL_TIME_WEATHER: '天气趋势',
            REAL_TIME_ENERGY_SAVE_RATE: '节能率',
            REAL_TIME_COAL_SAVE_TOTAL: '累计节省标煤',
            REAL_TIME_CO2_SAVE_TOTAL: '累计节省CO₂排放',
            REAL_TIME_KPI_CHART: '实时仪表盘(报警)',
            REAL_TIME_BAR: '实时柱图',
            OBSERVER: '组态页面嵌入面板',
            REAL_TIME_PREDICT_POINT_LINE: '预测折线图',
            TRANSIT: '数据分析',
            MULTIPLE: "复合图",
            NOTE: '文本',
            WHIRLWIND_CHART: '旋风图',
            RANK_CHART: '排行旋风图',
            MIX: '组合面板',
            Monitor: '监视面板',
            MODAL_HTML: 'HTML模块',
            MSG_MIX_NOT_ALLOW_TO_MIX: '组合图不可以拖入组合图',
            CUSTOM_CHART: '自定义图',
            POINT_KPI: 'KPI尊享版',
            REPORT_CHAPTER: '报表章节嵌入面板',
            MSG_KPI_NOT_ALLOW_TO_MIX: 'KPI尊享版不可以拖入组合图',
            INTERACT_CHART: '交互趋势图',
            APP_CHART: 'APP',
            APP_GAUGE_CHART: 'APP仪表盘',
            APP_BUTTON: 'APP导航',
            APP_HISTORY_QUERY: 'APP历史查询',
            APP_DIAGNOSTIC_RANKING: '诊断排名',
            APP_MONTH_HISTORY_QUERY: 'APP历史(月份)查询',
            KPI_STRUCT: 'KPI分项评估',
            APP_BLIND: '百叶窗面板',
            APP_PIE: 'APP饼图',
            APP_KPI_COLLECT: '监视列表',
            DATA_MONITOR_LIST: '数据监视列表',
            DIAGNOSIS_PANEL: '诊断嵌入',
            DIAGNOSIS_SUMMARY: '诊断汇总',
            KPI_OVERVIEW: 'KPI总览',
            REALTIME_WEATHER: '天气',
            CUMULANT_CHART: '累积量柱图',
            SLIDER: 'Slider面板'
        },
        APP_HISTORY_QUERY: {
            TITLE:'历史查询',
            CONFIG_BTN: '配置',
            START_TIME:'开始时间',
            END_TIME:'结束时间',
            PERIOD:'采样周期',
            SEARCH:'查询',
            MONTH:'1月',
            DAY:'1天',
            HOUR:'1小时',
            MINUTE:'5分钟'
        }
    },
    dashboard: {
        modalHistoryChart: {
            MAXIMUM: '最大值',
            MINIMUM: '最小值',
            EnergyConsumption: '能耗'
        },
        modalWeather: {
            REAL_TIME_TEMPERATURE: '实时温度'
        },
        modalConfig: {
            POINT_DRAG_TIP: "请将数据点拖拽至此……",
            ERR: "点数过多，无法继续增加！"
        },
        resize: {
            ERR1: "输入值大小大于目标允许最大值，请重新输入！",
            ERR2: "输入值大小小于目标允许最小值，请重新输入！",
            ERR3: "输入值必须为纯数字，请检查格式！"
        },
        show: {
            TITLE_TIP: "请输入标题",
            TITLE: '标题',
            SELECT_LINK: '选择链接',
            TYPE: '类别',
            LINK_TO: '链接到',
            DESC: "描述",
            DESC_TIP: "请在这里添加描述",
            WIKI_ID: "Wiki id",
            POP_ID: 'Pop id'
        },
        modalPointKPI: {
            PASS: '达标',
            UNPASS: '未达标',
            MONTH: '月',
            QUARTER: '季度'
        },
        modalJumpPages: {
            IMPORT_PAGE: '导入到数据源',
            POINT_LIST: '数据点名',
            GROUP_LIST: '选择数据源',
            SUCCESS_TIPS: '成功，是否跳转到数据分析页面 ？',
            FAIL_TIPS: '导出失败！',
            NO_FIT_POINT: '无可导数据点',
            SURE: '确定并跳转',
            CANCEL: '确定',
            NEW_GROUP: '新建数据源',
            SELECT_ALL: '全选',
            SELECT_REVERT: '反选',
            NEW_DS_NAME: '新数据源名称',
            PARAM_INTRO: '引用变量名',
            DATA_EXIST: '该数据源已存在于列表中！',
            NO_LABLE: '没有找到自定义标签:'
        },
        modalHistoryDataAnalyze: {
            DRAG_TIP_FOR_CHART: '拖拽数据源至此生成图表',
            DATE_CONFIRM: '查询',
            DATE_CANCEL: '取消',
            HISTORY_DATA: '历史数据',
            POINT_EXIST_TIP: '该点已存在'
        },
        modalKPIStruct: {
            NO_DATA_TEMP: '暂无数据'
        }
    },
    analysis: {
        TITLE: "数据分析",
        PANE_POINTS_ALL_TITLE: "所有点（单击选取）",
        PANE_POINTS_SELECTED_TITLE: "已选择的点（单击删除）",
        MARK_SELECTED: "已选",
        PANE_ADD_NOTE: '新建便签',
        BACK_TO_HOMEPAGE: '返回主菜单',
        PANE_CONFIG: '设置',
        PANE_FULL_SCREEN: '全屏',
        modalType: {
            TENDENCY: "趋势图",
            STACK: "面积图",
            SPECTRUM: "频谱图",
            SCATTER: "散点图",
            HISTORY_COMPARE: "历史同比柱图",
            HISTORY_COMPARE_LINE: "历史同比折线图",
            ENERGY: "能耗柱图",
            CLUSTER: "模式分析",
            PIE_REAL_TIME: "实时饼图",
            CLUSTER_AHU: "AHU诊断",
            CLUSTER_CHILLER: "冷机诊断"
        },

        paneConfig: {
            TITLE: "配置数据源",
            DATA_CONFIG_TITLE: "数据点位（每项上限5个）",
            DATA_DRAG_TIP: "请将数据拖拽至此",
            LABEL_INVERAL: "时间间隔",
            LABEL_TIME_START: "开始时间",
            LABEL_TIME_END: "结束时间",
            ALIGN_MODE: "补齐方式",
            ALIGN_FORWARD: "向前补齐",
            ALIGN_BACKWARD: "向后补齐",
            ALIGN_LINEAR: "线性插值",
            START_ANALYSIS: "开始分析",
            FUNCTION: "功  能",
            DATA_DEAL: "数据处理",
            DATA_DIVIDE: "数据分类",
            TREND_ANALYSE: "趋势分析",
            FREQ_ANALYSE: "频谱分析",
            YEAR: "年",
            MONTH: "月",
            DAY: "日",
            HOUR: "小时",
            MINUTE: "分钟",
            SECOND: "秒",
            RECFG_SRC_DATA: "重新配置源数据",
            SEL_PT_NAME: "已选点名",
            TREND_DISTRIBUTE: "趋势分布",
            TYPE_POINT: "分类散点",
            TYPICAL_CONDITION: "典型工况",
            DIAGNOSES_RESULT: "诊断结论",
            DATE: "日期",
            POINT_NUM: "点数",
            MISS_NUM: "丢失数量",
            MISS_RATE: "丢失率",
            ARGUMENTS: "参数",
            NAME: "名称",
            DESC: "描述",
            MAX: "最大值",
            MIN: "最小值",
            MED: "中间值",
            AVG: "平均值",
            STD: "标准值",
            RANGE_TO: "到",
            MODE_FIXED: "固定周期",
            MODE_RECENT: "最近周期",
            MODE_CURRENT: "预设周期",
            MODE_ACTUAL_TIME: "实时",
            INTERVAL_MIN1: "1分钟",
            INTERVAL_MIN5: "5分钟",
            INTERVAL_HOUR1: "1小时",
            INTERVAL_DAY1: "1天",
            INTERVAL_MON1: "1个月",
            TIME_RANGE_SEC: "秒",
            TIME_RANGE_MIN: "分钟",
            TIME_RANGE_HOUR: "小时",
            TIME_RANGE_DAY: "天",
            TIME_RANGE_MON: "月",
            DATA_TYPE_DEFAULT: "数据点位",
            ERR1: "请求后台数据失败",
            ERR2: "已存在于选取点列表中！",
            ERR3: "您还未选择过任何点！",
            ERR4: "请求频谱分析、数据分类数据失败！",
            ERR5: "所选的点在指定时间段内均无数据，请重新选择!",
            ERR6: "无历史数据点：",
            ERR7: "已被自动移除！",
            ERR8: "时间格式错误：开始时间晚于结束时间！",
            ERR9: "时间格式错误：结束时间晚于当前时间！",
            ERR10: "数据点重复：您拖动到此的数据点已存在！",
            ERR11: "数据错误：该时间段无法找到任何数据！",
            ERR12: "数据点过多，无法继续拖拽！"
        }
    },
    modalConfig: {
        TITLE: '配置',
        option: {
            SEARCH: "查询",
            LABEL_MODE: "模式",
            MODE_FIXED: "固定周期",
            MODE_RECENT: "最近周期",
            MODE_CURRENT: "快速配置",
            MODE_REAL_TIME: "实时",
            MODE_HISTORY: "历史",
            MODE_COMPARE_EASY: "快速配置",
            MODE_COMPARE_SENSOR: "传感器数据",
            MODE_COMPARE_METER: "能耗表数据",
            MODE_GAUGE: "仪表盘",
            MODE_WEATHER: "天气",
            LABEL_INTERVAL: "采样周期",
            LABEL_INTERVAL_ONE: '采样周期',
            INTERVAL_MIN1: "1分钟",
            INTERVAL_MIN5: "5分钟",
            INTERVAL_HOUR1: "1小时",
            INTERVAL_DAY1: "1天",
            INTERVAL_MON1: "1个月",
            LABEL_PERIOD: "时间周期",
            PERIOD_DROP_DOWN_LAST_HOUR: "过去1小时",
            PERIOD_DROP_DOWN_TODAY: "过去24小时",
            PERIOD_DROP_DOWN_YESTERDAY: "昨天（24小时）",
            PERIOD_DROP_DOWN_THREE_DAY: "过去72小时",
            PERIOD_DROP_DOWN_THIS_WEEK: "过去7天",
            PERIOD_DROP_DOWN_LAST_WEEK: "上周（7天）",
            PERIOD_DROP_DOWN_LAST_30_DAYS: "过去30天",
            PERIOD_DROP_DOWN_LAST_90_DAYS: "过去90天",
            PERIOD_DROP_DOWN_THIS_YEAR: "过去12个月",
            PERIOD_UNIT_SEC: "秒",
            PERIOD_UNIT_MIN: "分钟",
            PERIOD_UNIT_HOUR: "小时",
            PERIOD_UNIT_DAY: "天",
            PERIOD_UNIT_MON: "月",
            LABEL_TIME_RANGE: "时间范围",
            TIP_RANGE_TO: "到",
            LABEL_GAUGE_MODE: "异常模式",
            GAUGE_MODE_LOW: "低值异常",
            GAUGE_MODE_HIGH: "高值异常",
            GAUGE_GREEN: "节能",
            GAUGE_NORMAL: "正常",
            GAUGE_RED: "警报",
            LABEL_REAL_TIME_INTERVAL: "刷新间隔",
            LABEL_REAL_TIME_INTERVAL_ONE: '刷新时间',
            REAL_TIME_INTERVAL_30_SEC: "30秒",
            REAL_TIME_INTERVAL_1_MIN: "1分钟",
            REAL_TIME_INTERVAL_5_MIN: "5分钟",
            REAL_TIME_INTERVAL_10_MIN: "10分钟",
            REAL_TIME_INTERVAL_30_MIN: "30分钟",
            REAL_TIME_INTERVAL_1_HOUR: "1小时",
            REAL_TIME_INTERVAL_1_DAY: "1天",
            REAL_TIME_INTERVAL_1_MON: "1个月",
            LABEL_WEATHER: "城市代码",
            LABEL_COMPARE_PERIOD: "对比周期",
            LABEL_COMPARE_DATE1: "时间1",
            LABEL_COMPARE_DATE2: "时间2",
            COMPARE_PERIOD_HOUR: "1小时",
            COMPARE_PERIOD_DAY: "1天",
            COMPARE_PERIOD_WEEK: "1星期",
            COMPARE_PERIOD_MONTH: "1个月",
            COMPARE_PERIOD_YEAR: "1年",
            LABEL_HISTORY_RANGE: "时间范围",
            HISTORY_RANGE_HOUR: "1小时",
            HISTORY_RANGE_DAY: "1天",
            HISTORY_RANGE_WEEK: "1周",
            HISTORY_RANGE_MONTH: "1个月",
            HISTORY_RANGE_YEAR: "1年",
            LABEL_CHART_SELECT: "图表类型",
            CHART_SELECT_BAR: "柱图",
            CHART_SELECT_LINE: "折线图",
            CHART_TYPE: '图表类别',
            PIE: '饼图',
            BAR: '柱图',
            DEFAULT_TYPE: '默认类别',
            DEFAULT_LINE: '折线图',
            DEFAULT_BAR: '柱图',
            MODIFY_CHART_TITLE: '标题内容',
            MODIFY_CHART_YAXIS_NAME: '纵坐标名称',
            MODIFY_CHART_YAXIS_UNIT: '纵坐标单位',
            MODIFY_CHART_MAX: '最大值',
            MODIFY_CHART_MIN: '最小值',
            MODIFY_CHART_MARK: '刻度',
            MODIFY_CHART_CONFIG: '高级配置',
            TEMP_UNIT: '温度单位',
            TEMP_UNIT_C: '摄氏度',
            TEMP_UNIT_F: '华氏度'
        },
        data: {
            DATA_CONFIG_TITLE: "数据点位:",
            DATA_CONFIG_TIPS: '此项最多配置20个点，如需添加新点请删除多余项。',
            //DATA_CONFIG_TITLE_TYPE1: "每项上限5个 ",
            DATA_TYPE_MAX_NUM: " (上限<%maxNum%>个)",
            DEFAULT_NAME: "数据点位",
            DASHBOARD_MULTI_BAR: "柱图参数",
            DASHBOARD_MULTI_LINE: "折线图参数",
            DASHBOARD_MULTI_AREA: "面积图参数",
            DASHBOARD_MULTI_CUMULATIVE_BAR: "累计柱图参数",
            DATA_LOSE: "丢失",
            PT_UPPER: "坐标轴上限",
            PT_LOWER: "坐标轴下限",
            PT_UNIT: "坐标轴单位",
            PT_ACCURACY: "小数点位数",
            PT_COG_SURE: "确认",
            PT_COG_CANCEL: "取消",
            PT_LINE_1: "基线1",
            PT_LINE_2: "基线2",
            PT_LINE_3: "基线3",
            PT_LINE_4: "基线4",
            PT_LINE_NAME: "名称",
            PT_LINE_VAL: "数值",
            DATA_SHOW: "数据",
            TIME_MODE: "时间模式"
        },
        err: {
            TYPE1: "数据点过多，无法继续拖拽！",
            TYPE2: "数据点重复：您拖动到此的数据点已存在！",
            TYPE3: "时间格式错误：开始时间晚于结束时间！",
            TYPE4: "时间格式错误：结束时间晚于当前时间！",
            TYPE5: "仪表盘参数错误：参数大小没有按照从小到大排序",
            TYPE6: "没有历史数据！",
            TYPE7: "时间参数没有传入数据库！",
            TYPE8: "时间格式无法识别！",
            TYPE9: "时间周期数值对于当前时间周期单位过长！",
            TYPE10: "含有非数字参数，请检查！",
            TYPE11: "部分数据点丟失，可能已被删除！",
            TYPE12: "数据点数值范围上限超过下限！",
            TYPE13: "此处只可拖入一个数据点！"
        },
        btnStartConfig: {
            TYPE1: "开始分析",
            TYPE2: "确定"
        },
        modalApp: {
            RANKING: '排名',
            FAULT_NAME: '故障名称',
            EQUIPMENT_NAME: '设备名称',
            ZONE_NAME: '区域名称',
            TIMES: '次数',
            DURATION: '时长',
            MOTH_TIME: '本月发生次数',
            AVE_DURATION: '平均时长',
            ZONE: '区域',
            EQUIPMENT: '设备',            FREQUENCY: '频谱',
            SURE: '确定',
            CLOSE: '关闭',
            TIME_ERROR: '时间格式错误！请重新选择！',
            TIME_INTERVAL: '时间间隔太长请重新选择！',
            TIME_DOT:'具体时间点:',
            TIME_TITLE:'时间',
            SEND_ORDER:'发送工单'
        }
    },
    dataSource: {
        MONTH: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
        WEEK: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
        TITLE: '数据源',
        DS_CONFIG: '数据源配置',
        PROJECT_NAME: '项目名',
        PROJECT_SEARCH: '搜索',
        NUMBER: '编号',
        POINT_NAME: '点名',
        POINT_DESC: '注释',
        POINT_ATTR: '属性',
        SURE: '确认',
        CANCEL: '取消',
        PARAM: '参数',
        USER_NAME: '用户名',
        CUSTOM_NAME: '自定义名',
        FILTER_REPEAT_ITEM: '已过滤重复项',
        CUSTOM_REPEAT: '自定义名重复',
        CUSTOM_NOT_NULL: '自定义名不能为空',
        FORMULA_TIPS: '请输入公式（参数请按照参数列表中参数名输入）：',
        FORMULA_NAME: '公式名',
        FORMULA_VARIABLE_NAME: '变量名',
        FORMULA_VARIABLE_VALUE: '实际值',
        REMOVE_CONFIRM: '确认删除？',
        REMOVE_CONFIRM_TIPS: '已关联',
        REMOVE_RESULT: '已删除',
        WORKSPACE: '工作空间',
        TIME_YESTERDAY: '昨天',
        TIME_TODAY: '今天',
        NO_MATCH_FOUND: '未找到匹配结果',
        NO_SELECT_POINT: '请选择点！',
        GROUP_SELECTED: '已选',
        NO_SELECT_GROUP: '请选择组！',
        INPUT_GROUP_NAME: '请输入组名！',
        ADD_GROUP: '+ 添加分组',
        POINT_TYPE_CUSTOM: '自定义',
        POINT_TYPE_SYSTEM: '系统',
        POINT_TYPE_DEVICE: '设备',
        POINT_TYPE_TYPE: '类型',
        ERROR: '你的数据源已被删除，图表无法生成！',
        ICON_SYS_HVAC: '暖通',
        ICON_SYS_POWER: '动力',
        ICON_SYS_LIGHT: '照明插座',
        ICON_SYS_CRAC: '精密空调',
        ICON_DEV_CHIL: '冷机',
        ICON_DEV_PUMP: '水泵',
        ICON_DEV_COOL: '冷却塔',
        ICON_DEV_AHU: 'AHU',
        ICON_DEV_VAV: 'VAV',
        ICON_DEV_SYS: '系统',
        ICON_TYPE_TEMP: '温度',
        ICON_TYPE_FLOW: '流量',
        ICON_TYPE_FREQ: '频率',
        ICON_TYPE_ONOFF: '启停',
        ICON_TYPE_ELEPOW: '功率',
        ICON_TYPE_ELEPOWMET: '电量表',
        ICON_TYPE_THER: '冷量表',
        ICON_TYPE_PRES: '压力',
        ICON_TYPE_ALARM: '报警',
        ICON_TYPE_CURFLOW: '电流',
        NAV_MINE: '我的',
        NAV_CLOUD: '公共',
        ALREADY_EXIST: '添加已去除重复项',
        ADD_POINT_GROUP: '添加分组',
        ADD_POINT: '添加点',
        ADD_FORMULA: '添加公式',
        RENAME: '重命名',
        REMOVE: '删除',
        DELETE_GROUP_INFO: '请确认是否删除！',
        SEARCH_KEYWORD: '搜索关键字...',
        SEARCH_ALL: '全部',
        SEARCH_HIDE: '隐藏',
        SEARCH_TOWER_SYSTEM: '冷却塔系统',
        SEARCH_ROOM: '房间',
        SEARCH_AHU: '空调箱',
        SEARCH_TOWER: '冷却塔',
        SEARCH_CHILLER: '冷机',
        SEARCH_CONTROLLER: '控制器',
        SEARCH_FCU: '风机盘管',
        SEARCH_GETAWAY: '网关',
        SEARCH_HEAT: '换热器',
        SEARCH_CHARGE: '蓄冰槽',
        SEARCH_SEANSOR: '温度传感器',
        SEARCH_HVAC: '暖通设备',
        SEARCH_DEVICE: '暖通设备',
        SEARCH_VAV: '变风量系统',
        SEARCH_VALVE: '阀门',
        SEARCH_WATER: '水泵'
    },
    mainPanel: {
        ueserOpera: {
            CHANGE_PROJECT: '切换项目',
            PREVIEW_PROJECT: "预览项目",
            RELEASE_PROJECT: '发布项目',
            CANCELLATION: '注销'
        },
        pageEditModal: {
            ADD_PAGE_TITLE: '新增页面',
            EDIT_PAGE_TITLE: '编辑页面',
            NAME: '页面名称',
            PAGE_NAME: '未命名',
            TYPE: '页面类型',
            SIZE: '页面大小',
            DISPLAY: '页面位置',
            STRETCH: '拉伸',
            CENTER: '居中',
            ICON: '图标',
            BACKGROUND: '背景',
            SELECT: '选择',
            SELECTED: '已选择',
            SURE: '确认',
            CLOSE: '关闭'
        },
        iconSelect: {
            ICON_TITLE: '选择图标'
        },
        bgSelect: {
            BG_TITLE: '选择背景',
            BG_TYPE: '背景类型：',
            BG_COLOR: '纯色',
            BG_IMAGE: '图片',
            CHOOSE_IMAGE: '选择图片',
            IMAGE_STRETCH: '拉伸',
            IMAGE_TILE: '重复',
            PREVIEW: '效果图'
        },
        navbar: {
            SAVE_PAGE: '保存',
            PREVIEW_PAGE: '预览',
            UNDO: '撤销',
            REDO: '重做',
            RELEASE_PAGE: '发布页面',
            EXIT_EDIT: "退出编辑",
            QUIT_SCENE: "退出场景",
            VARIABLE_PANEL: '变量面板'
        },
        toolbar: {
            ARROW_TOOL: '箭头工具(快捷键v)',
            HAND_TOOL: '手型工具(快捷键m)',
            TEXT_TOOL: '文本控件(快捷键t)',
            BUTTON_TOOL: '按钮控件(快捷键b)',
            HTML_TOOL: 'Html容器控件(快捷键h)',
            SCREEN_TOOL: 'Screen容器控件(快捷键s)',
            IMG_TOOL: '图片控件(快捷键i)',
            PIPE_TOOL: '管道控件(快捷键p)',
            ZOOM_TOOL: '缩放工具',
            MATERAL_TOOL: '项目素材控件',
            GRID_TOOL: '显示网格线',
            DEVICE_TOOL: '设备控件',
            LAYOUT_TOOL: '对齐',
            THERMODY_TOOL: '热力图控件',
            HtmlContainer_TOOL: 'Html容器',
            POLYGON_TOOL: '多边形控件'
        },
        tLayout: {
            TOPALIGN: '上端对齐',
            RIGHTALIGN: '右端对齐',
            BOTTOMALIGN: '下端对齐',
            LEFTALIGN: '左端对齐',
            CENTERALIGN: '水平等间距',
            MODDLEALIGN: '垂直等间距',
            HEATAREA: '热力图选区',
            HEATSOURSE: '热力图标记'
        },
        releaseRepeat: {
            TITLE: '发布',
            RELEASE_INFO: '请确认是否发布？',
            RELEASE_START: '开始发布',
            RELEASE_NO: '取消',
            RELEASE_TITLE: '填写发布信息',
            PASSWORD: '密 码:',
            RELEASE_TO: '发布到:',
            PASSWORD_INFO: '请输入发布密码',
            OK: '发布成功！',
            NO: '发布失败！',
            SELECT: '请选择',
            NEW_PROJECT: '新项目'
        },
        releasePage: {
            PROJECT_NAME: '项目名称:',
            NAME_INFO: '请输入项目英文名称',
            RELEASE_INFO: '密码填写错误！',
            RELEASE_INFO_TIP: '请至少选择一个项目！'
        },
        releaseProject: {
            RELEASE_INFO: '密码填写错误！'
        },
        layerPanel: {
            TITLE: '图层',
            HTML_LAYER: 'Html 图层',
            BG_LAYER: '背景',
            EXPORT_INFO: '请选择一个图层！',
            EXPORT_INFO_TIP: '目前只支持canvas图层模板的导出',
            DELETE_INFO: 'Html图层和背景图层不能被删除',
            DELETE_INFO_TIP: '不可以删除被锁定的图层',
            DRAG_LAYER_INFO: '请选择一个节点进行拖拽！',
            ADD_GROUP: '新建文件夹',
            ADD_PAGE: '新建页面',
            EDIT_PAGE: '编辑页面',
            LOCK_PAGE: '锁定页面',
            EXPORT_PAGE_TEMPLET: '导出页面模板',
            IMPORT_PAGE_TEMPLET: '导入页面模板',
            DELETE_PAGE: '删除页面',
            ADD_GROUP: '新建组',
            ADD_LAYER: '新建图层',
            EDIT_LAYER: '编辑图层',
            LOCK_LAYER: '锁定图层',
            EXPORT_LAYER_TEMPLET: '导出图层模板',
            IMPORT_LAYER_TEMPLET: '导入图层模板',
            DELETE_LAYER: '删除图层',
            DELETE_LAYER_INFO: '是否要删除所选图层！',
            WRITE_TEMPLET_NAME: '输入模板名称',
            EXPORT_PAGE_TEMPLET_INFO: '请选择一个需要导出的页面！',
            SELECT_WORD_INFO: '必须选中或者不能同时改多个文件的name！',
            DIRECTORY_STRUCTRUE: '目前最多支持三级目录结构！'
        },
        historyPanel: {
            UNDEFINED: '未定义的操作',
            CREATE_LAYER: '创建图层',
            DELETE_LAYER: '删除图层',
            CHANGE_LAYER_NAME: '修改图层名称',
            SHOW_LAYER: '显示图层',
            LOCK_LAYER: '锁定图层',
            HIDE_LAYER: '隐藏图层',
            UNLOCK_LAYER: '解锁图层',
            NODE_MOVE: '图层/控件移动',
            CREATE_WIDGET: '创建控件',
            DELETE_WIDGET: '删除控件',
            CHANGE_WIDGET_NAME: '修改控件名称',
            SHOW_WIDGET: '显示控件',
            LOCK_WIDGET: '锁定控件',
            HIDE_WIDGET: '隐藏控件',
            UNLOCK_WIDGET: '解锁控件',
            MOVE_WIDGET: '移动位置',
            RESIZE_WIDGET: '调整大小',
            MOVE_WIDGET_OR_RESIZE_WIDGET: '改变控件位置或者大小',
            CREATE_BUTTON_WIDGET: '创建按钮控件',
            DELETE_BUTTON_WIDGET: '删除按钮控件',
            CHANGE_BUTTON_WIDGET_TEXT: '改变按钮文字',
            CHANGE_BUTTON_WIDGET_STYLE: '改变按钮样式',
            CHANGE_BUTTON_WIDGET_PAGE: '改变按钮控件跳转页面',
            CHANGE_BUTTON_WIDGET_FLOAT: '改变按钮控件跳转页面的浮动',
            CHANGE_BUTTON_WIDGET_ENUMERATE: '改变按钮控件枚举',
            CHANGE_BUTTON_WIDGET_IDDS: '改变按钮控件数据源',
            CHANGE_BUTTON_WIDGET_CUSTOMSTYLE: '改变按钮控件自定义样式',
            CREATE_TEXT_WIDGET: '创建文本控件',
            DELETE_TEXT_WIDGET: '删除文本控件',
            CHANGE_TEXT_WIDGET_TEXT: '改变文本文字',
            CHANGE_TEXT_WIDGET_STYLE: '改变文本样式',
            CHANGE_TEXT_WIDGET_PAGE: '改变文本控件跳转页面',
            CHANGE_TEXT_WIDGET_FLOAT: '改变文本控件跳转页面的浮动',
            CHANGE_TEXT_WIDGET_ENUMERATE: '改变文本控件枚举',
            CHANGE_TEXT_WIDGET_IDDS: '改变文本控件数据源',
            CHANGE_TEXT_WIDGET_CUSTOMSTYLE: '改变文本控件自定义样式',
            CHANGE_TEXT_WIDGET_PRECISION: '改变文本控件的数字精确度',
            CHANGE_TEXT_WIDGET_FONT_FAMILY: "改变文本控件的字体",
            CHANGE_TEXT_WIDGET_FONT_SIZE: "改变文本控件的字号",
            CHANGE_TEXT_WIDGET_FONT_STYLE: "改变文本控件的文本样式",
            CHANGE_TEXT_WIDGET_HORIZONTAL_ALIGN: "改变文本控件的水平对齐",
            CHANGE_TEXT_WIDGET_VERTICAL_ALIGN: "改变文本控件的垂直对齐",
            CHANGE_TEXT_WIDGET_COLOR: "改变文本控件的字体颜色",
            CREATE_HTMLCONTAINER_WIDGET: '创建Html容器控件',
            DELETE_HTMLCONTAINER_WIDGET: '删除Html容器控件',
            CHANGE_HTMLCONTAINER_WIDGET_CONTENT: '改变Html容器控件内容',
            EXPORT_HTMLCONTAINER_WIDGET: '导出Html容器控件',
            IMPORT_HTMLCONTAINER_WIDGET: '导入Html容器控件',
            CREATE_HTMLSCREENCONTAINER_WIDGET: '创建Screen容器控件',
            DELETE_HTMLSCREENCONTAINER_WIDGET: '删除Screen容器控件',
            CHANGE_HTMLSCREENCONTAINER_WIDGET_CONTENT: '改变Screen容器控件页面内容',
            CHANGE_HTMLSCREENCONTAINER_WIDGET_CUSTOMSTYLE: '改变Screen容器控件自定义样式',
            CREATE_PIPE_WIDGET: '创建管道控件',
            DELETE_PIPE_WIDGET: '删除管道控件',
            CHANGE_PIPE_WIDGET_WIDTH: '改变管道控件长度',
            CHANGE_PIPE_WIDGET_COLOR: '改变管道控件颜色',
            CHANGE_PIPE_WIDGET_IDDS: '改变管道控件数据源',
            CHANGE_PIPE_WIDGET_ENUMERATE: '改变管道控件枚举',
            CREATE_IMAGE_WIDGET: '创建图片控件',
            DELETE_IMAGE_WIDGET: '删除图片控件',
            CHANGE_IMAGE_WIDGET_CONTENT: '改变图片控件内容',
            CHANGE_IMAGE_WIDGET_ANGLE: '改变图片控件角度',
            CHANGE_IMAGE_WIDGET_IDDS: '改变图片控件数据源',
            CHANGE_IMAGE_WIDGET_ENUMERATE: '改变图片控件枚举',
            CHANGE_IMAGE_WIDGET_PAGE: '改变图片控件跳转页面',
            CHANGE_IMAGE_WIDGET_FLOAT: '改变图片控件跳转页面的浮动',
            CREATE_HEAT_WIDGET: '创建热力图选区控件',
            CHANGE_HEAT_WIDGET_POINTNUM: "改变热力图选区点的数目",
            CHANGE_HEAT_WIDGET_POINTARR: "改变热力图选区点的集合",
            CHANGE_HEAT_WIDGET_POINTID: "改变热力图选区点的id",
            DELETE_HEAT_WIDGET: '删除热力图选区控件',
            CREATE_HEATP_WIDGET: '创建热力图标记',
            DELETE_HEATP_WIDGET: '删除热力图标记',
            CREATE_HTMLDASHBOARD_WIDGET: "创建HtmlDashboard控件",
            DELETE_HTMLDASHBOARD_WIDGET: "删除HtmlDashboard控件"
        },
        exportModal: {
            EXPORT_INFO: '输入模板名称',
            TEM_NAME: '模板名称:',
            TEM_TYPE: '模板类型',
            TEXT: '文本控件',
            BUTTON: '按钮控件',
            HTML: 'HTML容器控件',
            SURE: '确定',
            CANCEL: '取消',
            WRITE_INFO: '请输入模板名称',
            EDIT_CON: '编辑内容',
            NO_POINT: '未找到相关云点',
            PHOTO: '快照',
            POINT_FORMAT_ERROR: '云点格式错误!',
            PROJECT_ID_ERROR: '该项目未绑定，写入的云点无效！',
            WIDGET: '控件',
            PAGE: '页面',
            LAYER: '图层'
        },
        layerName: {
            TEXT: '文本',
            BUTTON: '按钮',
            HTML: 'HTML容器',
            SCREEN: 'Screen容器',
            IMAGE: '图片',
            PIPE: '管道',
            DEVICE: '设备',
            HEAT: '热力图选区',
            HEATP: '热力图标记',
            POLYGON: '多边形',
            HTML_DASHBOARD: '自定义控件',
            DASHBOARD: 'HtmlDashboard控件'
        },
        attrPanel: {
            attrTab: {
                TITLE: '属性',
                PAGE_MANAGE: '页面管理',
                DATA_SOURCE: '数据源',
                HISTORY_RECORD: '历史记录',
                REPORT_TPL: '报表模板'
            },
            attrRepeat: {
                STYLE: '样式:',
                CONTENT: '内容:',
                DATA_SOURCE: '数据源:',
                CUSTOMSTYLE: '自定义样式:',
                EDIT_CONTENT_TITLE: '编辑内容',
                SAVE_STYLE_TITLE: '应用',
                EXPORT_STYLE_TITLE: '导出模板',
                IMPORT_STYLE_TITLE: '导入模板',
                PAGE: '页面:',
                SELECT_SCREEN: '选择页面',
                LINK_TO: '跳转:',
                LINK_TO_CON: '不跳转页面',
                EXACT_NUMBER: '精确位数:',
                FLOAT: '浮动:'
            },
            attrText: {
                TEXT_CONDITION: '请此处输入文本',
                TEXT_ONE: '正文1',
                TEXT_TWO: '正文2',
                TITLE_ONE: '标题1',
                TITLE_TWO: '标题2',
                TITLE_THREE: '标题3',
                TITLE_FOUR: '标题4',
                TITLE_FIVE: '标题5',
                SUBTITLE: '副标题'
            },
            attrButton: {
                STYLE_ONE: '默认',
                STYLE_TWO: 'Primary',
                STYLE_THREE: 'Success',
                STYLE_FOUR: 'Info',
                STYLE_FIVE: 'Warning',
                STYLE_SIX: 'Danger',
                STYLE_SEVEN: 'Link',
                STYLE_EIGHT: '粉红色',
                STYLE_NINE: '蓝色',
                STYLE_TEN: '绿色'
            },
            attrHtml: {
                TITLE: '代码编辑器',
                RUNCODE: '运行代码',
                SAVEANDEXIT: '保存并退出',
                IMAGEMANAGER: '图片管理器'
            },
            attrImg: {
                IMAGE: '图片: ',
                ROTATE: '旋转: ',
                CHOOSE: '选择',
                ENUMER_INFO: '先输入key值,谢谢!'
            },
            attrPipe: {
                PIPE_WIDTH: '选择管道宽度:',
                PIPE_COLOR: '管道颜色:',
                REVERSE_FLOW: '水流反向:',
                CUSTOM_COLOR: '自定义'
            },
            attrDevice: {
                DEVICE_TYPE: '设备种类：',
                DEVICE_PREFIX: '前缀：',
                DEVICE_PROP: '属性：',
                DEVICE_LINK: '外连：',
                DEVICE_EJECT: '弹出：',
                DEVICE_DIAGNOSIS: '诊断：',
                DEVICE_SKIN: '外观：',
                DEVICE_DROP_INFO: '已有实例对象不可改变!'
            }
        },
        materalPanel: {
            toolbar: {
                TITLE: '项目素材库',
                PRIVATE_MATERAL: '收藏',
                PAGE_MATERAL: '页面',
                LAYER_MATERAL: '图层',
                BUTTON_MATERAL: '控件',
                PUBLIC_MATERAL: '素材'
            },
            materalRepeat: {
                USE_MODAL: '使用素材',
                DELETE_OK: '删除成功',
                ADD_OK: '添加成功',
                PHOTO: '图片',
                ANIMATION: '动画',
                PAGE_NAME: '名称：',
                PAGE_CREATOR: '创建人：',
                PAGE_TIME: '创建时间：',
                PAGE_TYPE: '类型',
                FORMAT_LOG: '内容格式错误！'
            },
            privateMateral: {
                ADD_PHOTO: '从素材添加图片',
                DELETE_PHOTO: '删除图片',
                USE_PHOTO: '使用',
                COPY: '复制',
                COPY_LINK_SUCCESS: '复制ID成功！',
                COPY_LINK_FAILED: '复制ID失败，可能您的浏览器不支持此功能，手动复制。'
            },
            pageMateral: {
                ADD_MODAL: '新建模板',
                BATCH_ADD: '批量生成',
                EDIT_PAGE: '编辑页面',
                DELETE_PAGE: '删除页面',
            },
            layerMateral: {
                EDIT_LAYER: '编辑图层',
                DELETE_LAYER: '删除图层'
            },
            buttonMateral: {
                EDIT_BUTTON: '编辑控件',
                DELETE_BUTTON: '删除控件',
                USE_COPY: '是否保留副本?'
            },
            publicMateral: {
                UPLOAD_PHOTO: '上传',
                ADD_PRIVATE: '添加到收藏',
                DELETE_PHOTO: '删除',
                UPLOAD_INFO: '图片类型应该是.gif,jpg,png,jpeg中的一种',
                UPLOAD_INFO_TIP: '图片应该不大于600K。',
                EDIT_PHOTO: "编辑",
                WRITE_KEYWORD: '请输入关键字'
            }
        }
    },
    report: {
        REPORT_NAME: '报表模板',
        REPORT_SUB_NAME: '未命名',
        REPORT_RIGHT_NAME: '报表',
        VAR_DECLARATION: '变量声明',
        VAR_DECLARATION_NAME: '变量名',
        VAR_DECLARATION_VALUE: '对应值',
        VAR_DECLARATION_DESC: '描述',
        VAR_DECLARATION_DESC_DETAIL: '请输入描述信息',
        VAR_DECLARATION_EDIT_CODE: '编辑代码',
        VAR_DECLARATION_INFO: '数据格式有错误！',
        REMOVE_BTN: '删除控件',
        CONFIG_TEMPLATE_PRAM: '配置模板参数',
        EXPORT_BTN: '导出成模板',
        SELECT_INFO: '请选择一个模板！',
        REMOVE_INFO: '确定删除该模板吗？',
        REMOVE_INFO_SUCCESS: '删除成功！',
        ADD: '新增',
        DELETE: '删除',
        TEMPLATE_EDIT: '模板编辑',
        CONFIRM_DELETE: '确认删除?',
        LABEL_WIDTH: '宽',
        LABEL_HEIGHT: '高',
        ENTER_TEMPLATE_NAME: '请输入模板名称',
        ERROR_TEMPLATE_NAME: '请输入正确的模板名称',
        EXPORT_SUCCESS: '导出成功',
        EXPORT_ERROR: '导出失败',
        NOT_SUPPORT_EXPORT: '当前模块不支持导出',
        optionModal: {
            TITLE: '基本',
            TEXT: '文本',
            HTML: 'Html',
            ECHARTS: '图表',
            CHAPTER: '章节',
            SUMMARY: '汇总',
            BLOCK: '动态报表块',
            DIAGNOSIS_BLOCK: '诊断报表块',
            TABLE: '表格',
            DRAG: '拖拽'
        },
        reportConfig: {
            TITLE: '报表配置',
            REPORT_CYCLE: '报表周期',
            REPORT_CYCLE_DAY: '天',
            REPORT_CYCLE_WEEK: '周',
            REPORT_CYCLE_MOUTH: '月',
            REPORT_CYCLE_YEAR: '年',
            SURE: '确定'
        },
        chapterConfig: {
            TITLE: '章节配置',
            CHAPTER_TITLE: '章节标题',
            CHAPTER_SUMMARY: '章节汇总',
            CONFIG: '配置',
            SHOWORHIDE: '显示/隐藏',
            NUMBER: '第',
            CHAPTER: '章'
        },
        templateConfig: {
            TITLE: '模板参数配置',
            PRAM_NAME: '参数名称',
            PRAM_TYPE: '类型',
            PRAM_VALUE: '值',
            NO_PRAM: '无参数',
            REFRESH: '刷新',
            APPLY: '应用',
            WRITE_VALUE: '请填写值'
        },
        blockConfig: {
            TITLE: '动态报表块配置',
            DATA_ID: '数据ID',
            WRITE_ID: '请填写数据ID'
        },
        diagnosisBlockConfig: {
            TITLE_NO_DATA: "没有数据"
        },
        chartConfig: {
            TITLE: '图表配置',
            CHART_TYPE: '图表类型',
            CHART_LINE: '折线图',
            CHART_RECT: '柱状图',
            CHART_CIRCLE: '饼图',
            CONFIG: '配置',
            DATA_DOINT: '数据源',
            SAMPING_CYCLE: '取样周期',
            BEFORE_DAY: '过去一天',
            BEFORE_WEEK: '过去一周',
            BEFORE_MOUTH: '过去一个月',
            BEFORE_YEAR: '过去一年',
            SAMPING_SPACE: '取样间隔',
            FIVE_MINITER: '5分钟',
            ONE_HOUR: '1小时',
            ONE_DAY: '1天',
            WRONG_INFO: '图表配置中含有错误，将不会被保存！',
            INTER_WORD: '请输入文字',
            COPY_LINK: '复制链接',
            COPY_LINK_SUCCESS: '复制成功',
            COPY_LINK_FAILED: '复制失败',
            COPY_IMAGE_SUCCESS: '图片URL已被复制到粘贴板'
        },
        tableConfig: {
            TYPE: '类型',
            DATASOURCE: '数据源',
            TITLE: '表格配置',
            ISCHANGE: '行列互换'
        },
        reportWrap: {
            PDFDOWNLOAD: 'PDF',
            WORDDOWNLOAD: 'WORD',
            GENERATED_BY_BEOP: 'BeOP提供'
        }
    },
    screen: {
        UNSAVED_PAGE_TIP: '您还有未保存的数据，确定离开吗？'
    },
    iot: {
        IOT: '设备',
        PARAMS_CONFIG: '参数配置',
        //QUERY_KEYWORD:'搜索关键字...',
        TREE_ALL: '全部',
        TREE_HIDE: '隐藏',
        ADD_THING: '添加Thing',
        ADD_GROUP: '添加Group'
    },
    modal: {
        memberSelected: {
            CONFIRM: '确认',
            TITLE: "请选择人员",
            INPUT_INFO: "请输入用户名称",
            ALL: '全部',
            MEMBER_SELECTED: '已选成员'
        }
    },
    diagnosis: {
        OVERVIEW: '导航',
        DIAGNOSIS_LOG: '诊断日志',
        LOG_MORE: '更多...',
        LOG_NO_MORE: '已全部显示',
        config: {
            TITLE: '配置',
            CONFIRM: '确认',
            CANCEL: '取消',
            NORMAL: 'Normal级',
            ALERT: 'Alert级',
            WARNING: 'Warning级',
            RULE_SET: '报警规则设置',
            AUTO_PUSH_WO: '自动推送工单',
            DIAGNOSIS_PAUSE_SET: '诊断暂停设置',
            SET: '设置',
            ACTIVE: '启用',
            DIAGNOSIS_SHOW: '诊断每小时显示',
            CHOOSE_DIAGNOSIS_SHOW: '选择诊断每小时显示',
            defaultPeriod: {
                REAL_TIME: '实时',
                DELAY_1H: '延迟1小时',
                DELAY_12H: '延迟12小时',
                DELAY_24H: '延迟24小时',
                DELAY_7D: '延迟7天',
                DELAY_1M: '延迟1月',
                DELAY_FOREVER: '不报'
            },
            subConfig: {
                CREATE_CASE: '创建方案',
                CASE_NAME: '方案名称',
                CHOOSE_BUILD: '选择楼宇',
                CHOOSE_AREA: '选择区域',
                CHOOSE_EQUIPMENT_TYPE: '选择设备类型',
                CHOOSE_STOP_TIME: '选择停用时间',
                CHOOSE_DISTRIBUTE_PERSON: '选择分配人员',
                ALARM_LEVEL: '警报级别',
                PROJECT: '项目',
                USER: '人员',
                NORMAL: 'Normal',
                ALERT: 'Alert',
                WARNING: 'Warning',
                UPDATE_FAIL: '保存失败',
                MUST_CHOOSE_EQUIP: '请选择设备类型',
                MUST_FILL_IN: '请输入要填写的内容'
            },
            CHANGE_LEVEL: '更改级别',
            CHANGE_ALARM_TIME: '更改报警时间',
            LEVEL_SET: {
                NORMAL: '一般',
                CRITICAL: '异 常',
                URGENT: '故 障'
            }
        },
        historyLog: {
            TITLE: '历史记录',
            TIME: '时间',
            GRADE: '级别',
            EQUIPMENT: '设备',
            ZONE: '区域',
            FAULT: '故障',
            STATUS: '状态',
            EXECUTOR: '处理人',
            RESPONSE_TIME: '响应时间',
            RESPONSE_CONTENT: '未响应'
        },
        diagnosticLog: {
            HISTORY: '历史记录',
            STICKY_POST: '固定或悬浮',
            CHECK: '检查',
            HIDE_SHOW: '显示或隐藏',
            HIDE_SHOW_URGENT: '显示或隐藏诊断日志',
            ENERGY_CONSSERVATION: '每小时能耗浪费约 '
        }
    }
}