var i18n_resource = {
    admin: {
        login: {
            PANE_TITLE: "Log in",
            PANE_LABEL_ACCOUNT: "Account：",
            PANE_LABEL_PWD: "Password：",
            PANE_CHECKBOX_REMEMBER: "Remember",
            PANE_REGIST: "Register",
            PANE_FORGET: "Forgot",
            PANE_BTN_LOGIN: "Log in",
            PANE_PLACEHOLDER_ACCOUNT: "Please enter your account",
            PANE_PLACEHOLDER_PWD: "Please enter your password"
        },
        register: {
            CREATE_NEW_ACCOUNT: "Create a new account",
            NEW_ACCOUNT: "New username:",
            MAIL: "Email address",
            PASSWORD: "Password:",
            OK: "Yes",
            CLOSE: "Close",
            FILL_REGISTER_INFORMATION: 'Fill in register information',
            EMAIL: 'email',
            ACCOUNT: 'Account',
            PASSWORD_CONFIRM: 'Password confirm',
            ENTER_USER_INFORMATION: 'Enter user information...',
            COMPLETE_REGISTRATION: 'Complete registration',
            JOIN_NOW: 'Join now',
            ACCOUNT_VALIDATE: '2-10 Chinese characters or 5-10 characters',
            USERNAME_ALREADY_EXISTS: 'Username already exists',
            PASSWORD_IS_WRONG: "Password doesn't match",
            PASSWORD_CONFIRM_INFO: '6 - 15 characters',
            REGISTER_SUCCESSFUL_GOTO: 'Register successful, redirecting to BeOP Platform home page in 5 seconds',
            REGISTER_FAILED: 'Register failed',
            MAIL_TIPS: 'Please enter your email such as beop.cloud@rnbtech.com.hk'
        },
        resetPassword: {
            RESET_PASSWORD: "Reset password",
            ACCOUNT: "Account",
            MAIL: "Email address",
            OK: "Yes",
            CLOSE: "Close",
            MAIL_SENDING: 'Email sending',
            MAIL_COMPLETE: 'Email sent successful',
            OLD_PASSWORD: 'Original password',
            NEW_PASSWORD: 'New password',
            NEW_PASSWORD_CONFIRM: 'New password confirm',
            PASSWORD: 'Password',
            PASSWORD_CONFIRM: 'Password confirm',
            PASSWORD_RESETTING: 'Password resetting...',
            RESET_PASSWORD_SUCCESSFUL: 'Reset password successful',
            PASSWORD_DONOT_MATCH: "Password doesn't match",
            PASSWORD_INFO: '6 - 15 characters',
            RESET_SUCCESSFUL_GOTO: 'Reset password successful, auto redirecting to BeOP Platform home page in 5 seconds',
            PASSWORD_RESET_FAILED: 'Password reset failed'
        },
        featurePane: {
            OPTIMIZATION: "Optimization",
            DIAGNOSTIC: "Diagnostic",
            TRANSACTION: "Event Detection",
            TEAM: "Team management",
            MULTIPALTFORM: "Multi-platform"
        },
        featureDisplay: {
            DEFAULT_1: "Smart service",
            DEFAULT_2: "for energy and facility management",
            OPTIMIZATION_1: "Operating principle of energy saving and optimization system ",
            OPTIMIZATION_2: "BeOP (Behavior based-Optimization Platform) is an energy saving control system based on equipment model to optimize the energy consumption",
            DIAGNOSTIC_1: "Optimization engine and diagnostic engine",
            DIAGNOSTIC_2: "As a system platform, real-time fault detection and diagnostics platform integrate data collection and mining, monitor and display, equipment and system diagnostic analysis, report and overall optimization, and etc.",
            TRANSACTION_1: "Real-time fault detection and diagnostics",
            TRANSACTION_2: "Admin of the building can know real-time information such as operation status of equipment, fault detection, diagnostic information and  building energy consumption  through mobile client application (Iphone or IPad)",
            TEAM_1: "Team management",
            TEAM_2: "Platform can record diagnoses in real time and send these information to relevant operating and maintenance admin for processing",
            TEAM_3: "Relevant operating and maintenance admin will not receive work orders continuously until they solve it.",
            TEAM_4: "Platform record occurrence time and solutions of all problems, improve working efficiency in further step",
            MULTIPALTFORM_1: "Real-time mobile client",
            MULTIPALTFORM_2: "Admin of the building can know real-time information such as operation status of equipment, fault detection, diagnostic information and  building energy consumption  through mobile client application (Iphone or IPad)"
        },
        navIndex: {
            LOGO: "Energy leader",
            LINK_HOME: "Home",
            LINK_CASES: "Cases",
            LINK_MOBILE: "Mobile version",
            LINK_COMPANY: "R&B Tech",
            LINK_DOWNLOAD: "Download support",
            LINK_LANGUAGE: "Language"
        },
        navAdmin: {
            LINK_PROJECTS: "Project",
            LINK_WORKFLOW: "Work order"
        },
        projectConfigure: {
            NEXT: "Next",
            FINISH: "Finish",
            READ_DATA_FAILED: "Read data failed",
            UPLOAD_PROJECT_FAILED: "Upload project failed",
            UPDATE_FAILED: "Update project failed",
            SELECT: "Select",
            DATE: "Date",
            NO_DATA_READ: "No data read"
        },
        projectSelector: {
            PANE_TITLE: "Select",
            PANE_TITLE_SUB: "Project",
            PANE_BTN_UPDATE: "Update",
            PANE_BTN_MANAGER: "Setting",
            TITLE_MAPSELECTOR: "Map",
            TITLE_PANELSELECTOR: "List View",
            PROJECT_STATUS: 'Status',
            PROJECT_LAST_RECEIVED_TIME: 'Last update time',
            PROJECT_UPDATE_SUCCESS: 'Update project complete',
            PROJECT_UPDATE_FAILED: 'Update project failed',
            PROJECT_OPEN_FAILED: 'Open {0} project failed',
            TITLE_PROJECT_LIST: 'Project list'
        },
        projectManager: {
            EMAIL_ADDRESS_REQUIRED: 'Email address is required',
            INVALID_EMAIL_ADDRESS: 'Invalid email address',
            NOT_SELECT_OBJ: 'Not select initial project or permission',
            INVITE_NEW_USER: 'Invite new user',
            ADD_PROJECT: 'Add project',
            ADD_NEWUSER_FAILED: 'Add new user failed',
            ERROR: 'Error',
            NO_PERMISSION_ADD: 'No permission to add users on this project',
            PERMISSION: 'Permission',
            DELETE_FAILED: 'Delete failed',
            DELETE: 'Delete',
            PROJECT_ICON: "Project icon",
            UPDATING: "Updating",
            UPDATE_COMPLETE: "Update complete",
            UPDATE_FAILED: "Update failed",
            PROJECT_PERMISSION_LIST: "Project List",
            SEND_INVITATION: 'Send invitation',
            EMail_ADDRESS: 'Mail address',
            INIT_PROJECT: 'First project',
            PERMISSION: 'Permission',
            INVITE_SUCCESS: 'invitation succeeded',
            CANCEL: "Cancel",
            SEND: 'Send'
        },
        projectCreator: {
            REGIST_STEP1_TITLE: 'Create Project',
            REGIST_STEP2_TITLE: 'Upload Data',
            REGIST_PREV_STEP_TITLE: 'Prev',
            REGIST_NEXT_STEP_TITLE: 'Next',
            PANE1_TITLE: 'Welcome to the Beop system. If you are visiting for the first time, please create projects follow the guide. Wish you have a pleasant experience.',
            PANE1_FORM_ITEM1_LABEL: 'Project Name',
            PANE1_FORM_ITEM1_PLACEHOLDER: 'Please enter your project name.',
            PANE1_FORM_ITEM1_TIP: 'Name criteria: Contains only letters and numbers.',
            PANE1_FORM_ITEM2_LABEL: 'Project Address',
            PANE1_FORM_ITEM2_PLACEHOLDER: 'Please choose your project address on the map.',
            PANE1_FORM_ITEM2_TIP: 'Address criteria: Manually changing is not supported.Please choose it on the map.',
            PANE1_FORM_ITEM3_LABEL: 'City Name',
            PANE1_FORM_ITEM3_PLACEHOLDER: 'Please choose your project coordinate on the map.',
            PANE1_FORM_ITEM3_TIP: 'Coordinate criteria: Manually changing is not supported.Please choose it on the map.',
            PANE1_FORM_ITEM4_LABEL: 'Project Preview Image (click the image below to modify it)',
            PANE2_TITLE: 'OK! You could upload your project data now, or you could skip this step and upload later.',
            PANE2_FORM_ITEM1_LABEL: 'Please choose your project data file on your local system (you can also upload a file by dragging it to this page):',
            PANE2_FORM_ITEM1_TIP1: '(Please choose a file)',
            PANE2_FORM_ITEM1_TITLE: 'Upload File',
            PANE2_FORM_ITEM1_TIP2: 'File criteria：.csv/.xls/.xlsx file are currently supported, please check it before upload.',
            PANE2_TABLE_TITLE: 'Sample Data',
            ERROR_NOT_EMPTY: 'The project name cannot be empty.',
            ERROR_WRONG_CRITERIA: 'Contains only letters and numbers.',
            ERROR_EXIST_NAME: 'Project name already exists. Please select another.',
            ERROR_NOT_CHOOSE_ADDRESS: 'Please choose your project address on the map.'
        },
        ddlUser: {
            MENU_WORKFLOW: "Work order system",
            MENU_OPERATING_RECORD: "Operation record",
            MENU_ALARM_LOGGING: "Alarm logging",
            MENU_REALTIME_DATA: "Real-time data",
            MENU_CHANGE_PROJECT: "Switch to another project",
            MENU_RESET_PASSWORD: "Change Password",
            MENU_POINT_MANAGER: "Data management",
            MENU_DATA_SOURCE: "Data source",
            MENU_LOGOUT: "Sign out",
            MENU_FORGET_PWD: "Forgot"
        },
        panelManagement: {
           ACCOUNT_RECORD_OPERATION: 'Account Operation Record',
           ALL_RECORDS: 'All history',
           ACCOUNT_LOGIN_RECORD: 'Login history',
           USER_MANAGEMENT_RECORD: 'Account management history',
           PAGE_MANAGEMENT_RECORD: 'Page management history',
           TIME: 'Date',
           TO: 'To',
           DETERMINE: 'Confirm',
           DATE_CANNOT_EMPTY: 'Date is required',
           MODIFY_THE_PASSWORD: 'Change password',
           ORIGINAL_PASSWORD: 'Old password',
           NEW_PASSWORD: 'New password',
           CONFIRM_NEW_PASSWORD: 'New password confirm',
           PASSWORD_FORMAT: 'Password format is from 4 to 22 characters, with upper case, lower case, numbers, @, !, #, $, & and .',
           CANCEL: 'Cancel',
           CONFIRM: 'Confirm',
           PROMPT: 'Information',
           CONFIRM_THE_CHANGE: 'Confirm change',
           CIPHER: 'Password',
           SUPERIOR: 'superior',
           MANAGEMENT_AUTHORITY_OK: 'Admin authority: yes',
           MANAGEMENT_AUTHORITY_NO: 'Admin authority: no',
           ENTER_A_QUERY: 'Please enter an account name',
           ADD_STAFF: 'Add a staff',
           INVITATION_TO_SEND: 'Invitation sending',
           DELETE_IT: 'Are you sure you want to delete',
           AT_LOWER_LEVEL: 'subordinate',
           NOT_ACTIVATED: 'Not activated',
           MANAGEMENT_AUTHORITY: 'Admin authority',
           YES: 'Yes',
           NO: 'No',
           DELETE: 'Delete',
           SET_INITIAL_PROJECT: 'Set initial project',
           SET_INITIAL_ROLE: 'Set initial role',
           SET_INITIAL_GROUP: 'Set initial group',
           SET_SUPERVISOR: 'Assign superior',
           GIVEN_AUTHORITY: 'Assign admin authority',
           USER_NAME: 'Account name',
           MAILBOX: 'E-mail',
           MAILBOX_FORMAT_WRONG: 'E-mail format error, please enter again',
           ALL_ITEMS: 'All projects',
           ADD_ITEMS: 'Add a project',
           GROUP_NAME: 'Group name',
           ENTER_GROUP_NAME: 'Please enter a group name',
           GROUP_NAME_NOTNULL: 'Group name is required',
           CONFIGURATION_PAGE: 'Setting',
           PAGE_CONFIGURATION: 'Setting',
           SAVEING: 'Saving',
           ADD_GROUPING: 'Add group',
           ACCOUNT_MANAGEMENT: 'Account management',
           ACCOUNT: 'Account',
           STAFF_MANAGEMENT: 'Staff management',
           PROJECT_MANAGEMENT: 'Authority management',
           SIGN_IN: 'Log in',
           EMAIL_FORMAT: 'Password is from  2 to 10 characters, with numbers, upper case, lower case, - and _',
           ORIGINAL_PASSWORD_NULL: 'Old password is required',
           NEW_PASSWORD_NULL: 'New password is required',
           CONFIRMED_PASSWORD_NULL: 'Password confirm is required',
           PASSWORD_CONSISTENT_ERROR: 'Password does not match',
           PASSWORD_FORMAT_ERROR: 'Invalid new passpord',
           REQUEST_ERROR: 'Request error',
           FILE_SIZE_LIMITED: 'File size cannot exceed 1M',
           IMMEDIATE_SUPERIOR_NULL: 'Superior is required',
           MAILBOX_CHECKINFO_REPEATED: 'E-mail cannot be the same. Please enter again!',
           INITIAL_PROJECT_NOTNULL:  'Initial project is required',
           INITIAL_ROLE_NOTNULL:  'Initial role is required',
           PLEASE_ADD_USER: 'Please add a user',
           MAILBOX_CHECKINFO_APPLY: 'E-mail is already registered',
           MAILBOX_CHECKINFO_INVITED: 'E-mail is already invited',
           MAILBOX_CHECKINFO_REGISTERED: 'E-mail is already registered',
           SEND_MAIL_FAILED: 'E-mail sent failed',
           SEND_EMAIL_SUCCESS: 'E-mail sent successful',
           GROUPINGNAME_NOT_REPEAT : 'Group name cannot be the same',
           START_TIME_CHECKINFO: 'Start date is required',
           END_TIME_CHECKINFO: 'Close date is required',
           TIME_GREATER_CHECKINFO: 'Start date cannot be later than close date',
           MENU_NOT_CONFIGURED : 'Project menu has not been configured',
           ADD_AS_SHORTCUT : 'Add as a shortcut'
        }
    },

    observer: {
        analysis: {
            AVERAGE: 'Average',
            TOTAL_AMOUNT: 'Total',
            SORT_FAILED: 'Sort failed',
            ENTER_WORKSPACE_NAME: 'Enter the name of workspace',
            RETURN: 'Return'
        },
        entities: {
            BIG_DATA_COMPARISON: 'comparison in big data',
            RELATIVELY_POOR: 'Relatively poor',
            GENERAL: 'General',
            GOOD: 'Good',
            EXCELLENT: 'Excellent',
            MAIN_SCALE_INFO: 'Main scale space of ruler cannot be 0',
            CURRENT_PROJECT: 'Current project',
            WORKING_CONDITION_RATE: 'Efficiency of same working condition',
            REQUEST_DATA_FAILED: 'Request real-time data failed'
        },
        widgets: {
            PLEASE_SELECT_PROJECT: 'Please select project',
            CUSTOMIZE_NAME: 'Customize name',
            USERNAME: 'Account',
            PROJECT_NAME: 'Project name',
            POINT_NAME: 'Point name',
            NOTES: 'Notes',
            PARAMETER: 'Parameter',
            DATABASE_OPERATION_FAILED: 'Database operation failed',
            FAIL_BEFORE_EXECUTING: 'Fail to manage database before executing',
            READ_DATA_FAILED: 'Read data failed',
            MAXIMUM: 'Maximum',
            MINIMUM: 'Minimum',
            ACTION_CONFIRM: 'Action confirm',
            CONFIRM: 'Confirm',
            YES: 'Yes',
            EXECUTING: 'Executing',
            CANCEL: 'Cancel',
            START_SENDING_REQUEST: 'Start sending request',
            REQUEST_SENT_CONFIRM: 'Request sent, please confirm data',
            DATA_OPERATION_COMPLETE: 'Data operation complete',
            TIMES_DATA_CONFIRM: 'times data confirm',
            FAIL_TRY_AGAIN: 'Fail to operate, please try again',
            FAIL_SEND_REQUEST: 'Fail to send request',
            NO_OPERATIONS_TODAY: 'No operations today',
            FAIL_FIND_POINT: 'Fail to find the point',
            SELECT_START_TIME: 'Please select start time',
            SELECT_CLOSING_TIME: 'Please select end time',
            PLEASE_SELECT_POINT: 'Please select point',
            HISTORY_CURVE_FAILED: 'Generate history curve failed',
            ENTER_STAT_TIME: 'Please  enter stat time',
            ENTER_CLOSING_TIME: 'Please enter end time',
            FAIL_SAVE_CONFIGURATION: 'Fail to save history curve configuration',
            FAIL_LOAD_CONFIGURATION: 'Fail to load history curve configuration',
            UPDATE_TABLE: 'Update table',
            FAILED: 'failed',
            NO_DATA_READ: 'No data read',
            DATA_REQUEST_FAILED: 'Data request failed',
            TOTAL_AMOUNT: 'Total',
            EMAIL_ADDRESS_REQUIRED: 'Email address is required',
            INVALID_EMAIL_ADDRESS: 'Invalid email address',
            EMAIL_PASSWORD_SENT: 'Email of resetting password has already been sent',
            EMAIL_NOT_EXIST: 'Email address does not exist',
            EMAIL_FAILED_SEND: 'Email of resetting password failed to send',
            ENTER_YOUR_USERNAME: 'Please enter your username',
            ENTER_YOUR_PASSWORD: 'Please enter your password',
            LOAD_PROJECT_FAILED: 'Load project failed: ',
            NO_PERMISSION_PROJECT: 'No permission on any project',
            LOG_IN_FAILED: 'Log in failed: ',
            INVALID_ACCOUNT_PASSWORD: 'Invalid account or password',
            CONFIG_MODE: 'Config',
            CONFIG_SAVE:'Save',
            BACKTRACE: 'Replay',
            TRACE_RANGE: 'Range',
            TRACE_PERIOD:'Step',
            LAST_DAY: 'Yesterday',
            TODAY: 'Today',
            THIS_WEEK: 'This week',
            LAST_WEEK: 'Last week',
            CUSTOM: 'Custom',
            TO: 'To',
            START: 'Start',
            FRAME: 'Frame',
            START_TIME: 'Start',
            CLOSE: 'close',
            OPERATING_RECORD: 'Operation record',
            TIME: 'Time',
            OPERATOR: 'User',
            INFORMATION: 'Info'
        },
        menu: {
            TITLE_OBSERVERSCREEN: "Visualization",
            TITLE_DIAGNOSISSCREEN: "Diagnosis",
            TITLE_ANALYSIS: "Analysis",
            TITLE_REPORTSCREEN: "Report",
            TITLE_STATISTICS: "Dashboard",
            TITLE_WORKFLOWSCREEN: "Work order management",
            TITLE_MENU_CONFIGURE: "MENU Configure"
        },
        observerScreen: {
            DIALOG_TITLE: "Detail",
            TEXT_EDITOR_CONFIRM: 'Confirm',
            TEXT_EDITOR_SEND_SUCCESS: 'Data set successful',
            TEXT_EDITOR_SEND_FAIL: 'Data set failed',
            TEXT_ADD_TO_DATASOURCE:'Add To My Data Analysis'
        },
        projectSelector: {
            TITLE_NAVIGATION: "Project guide",
            TITLE_ADDRESS: "Address: ",
            TITLE_NEARBY_PROJECT: "Projects near by"
        },
        reportScreen: {
            TITLE_WEEKLY_REPORT: "Weekly report",
            TITLE_DAILY_REPORT: "Daily operating report",
            ALERT_CAN_NOT_FIND_REPORT: "Project report is not found.",
            TITLE_WEEK_YEAR: "{0} year {1} week",
            TITLE_DATE_FORMAT: "MM/dd/yyyy",
            TITLE_NO_DATA: "No data",
            REPORT_FAIL_INFO: "Fail to find the report from selected time period. Please select again from the right column."
        }
    },

    workflow: {
        nav: {
            LINK_HOME: "",
            LINK_NOTICE: "",
            LINK_REPORT: "",
            LINK_TEAM: "",
            LINK_EFFICIENCY: "",
            LINK_MINE: ""
        },
        pageInfo: {
            TITLE_MAIN_PAGE: "Project",
            TITLE_WO_DYNAMIC: "Status",
            TITLE_WEEK_REPORT: "Weekly report",
            TITLE_TEAM: "Team",
            TITLE_EFFIC: "Efficiency",
            TITLE_WO_MY: "My order",
            PEOPLE_SEL: "User filter",
            GROUP: "Group",
            MEMBER: "Member",
            ALL_MEMBER: "All members",
            NEWS: "Latest status",
            LOAD_MORE: "Load more",
            SET: "SET"
        },
        main: {
            ADD: "Add work order",
            ALARM_CONTENT: "Description",
            NEW: "New order",
            ASSIGNED: "Assigned",
            DEALING: "Processing",
            PAUSED: "Suspend",
            FINISHED: "Complete",
            DELETED: "Deleted",
            SAVE: "Save",
            CANCEL: "Cancel",
            NAME_NOT_NULL: "Name is required",
            ALL: "All work orders",
            MAIN_PAGE: "Homepage",
            NOTE: "Attention",
            DEL_SURE: "Do you really want to delete this work order?",
            SURE: "Yes",
            SUM: "In total",
            DELAY: "Delay",
            ADD_FAULT: "Add work order",
            FAULT_TITLE: "Work order name",
            FAULT_INFO: "Work order detail",
            FINISH_TIME: "Deadline",
            PEOPLE: "Staff",
            EDIT: "Edit",
            DELETE: "Delete",
            TIP1: "This work order is not assigned, please assign first",
            TIP2: "This work order is not assigned",
            FINISH_TIME_NOT_NULL: "Deadline is required",
            PEOPLE_NOT_NULL: "Staff is required",
            ADD_SUCCESS: "Add successful",
            CREATE_TASK: "Create order",
            FINISH: "Finish",
            START: "Start",
            RESTART: "Restart",
            PAUSE: "Pause",
            ASSIGN_AGAIN: 'Assign again',
            WORK_ORDER_DELETED: 'This work order is deleted'
        },
        notice: {
            DYNAMIC_TIME: "updated",
            COOLER_ALARM_FAULT: "Chiller fault alarm",
            TASK_RENAME: "Renamed to",
            TASK_EDIT: "edited order",
            TASK_FINISH: "completed order",
            TASK_RESTART: "restarted order",
            TASK_START: "started order",
            TASK_PAUSE: "suspended order",
            TASK_REPLY: "replied order",
            TASK_CREATE: "created order",
            NO_FOUND: "Content matching the filter criteria is not found",
            ORDER_STATUS: "Status",
            ORDER: "Work order",
            DEADLINE: "Deadline",
            FAULT_CHART: "Info",
            TOPIC: "Topic discussion",
            COMMENTS: "Comment",
            REPLAY_ORDER: "Reply",
            BACK: "Back",
            FAULT_CURVE: "Fault snapshot",
            WORK_ORDER_HISTORY: "Work order history",
            CREATOR: 'Creator'
        },
        report: {
            WORKFLOW_SEL: "Work order filter",
            PEOPLE_SEL: "User filter",
            PROJ_NAME: "Project name",
            ALL_TASK_NUM: "Total",
            UNFINISH_NUM: "Unfinished",
            FINISH_SCALE: "Completed",
            MAJOR_PEOPLE: "Main participants",
            ALL_DEAL_NUM: "Total",
            FINISH_NUM: "Completed",
            COOLER_FAULT_ALARM: "Chiller fault alarm",
            SHOW_TEXT: "Show difference and point operator",  //缺
            FINISH: "Finish",
            UNFINISH: "Unfinished",
            LOAD_MORE: "Load more",
            MONTH: "Month",
            WEEK: "Week",
            DAY: "Day",
            TITLE_TIME1: " week ",  //缺
            TITLE_TIME2: "{0} {1}nd week",
            TITLE_TIME3: "{1}th {0}~ {3}th {2}"
        },
        mine: {
            CHECK_COMPLETED: "Completed",
            TASK: "Order",
            STARRED: "Star",
            CANCEL_STARRED: "Cancel the star",
            CATEGORY: "Classification",
            TASK_TYPE_NEW_TASK: "New order",
            TASK_TYPE_URGENT_TASK: "Urgent order",
            TASK_TYPE_PEND_TASK: "Order to do",
            TASK_EMPTY_MESSAGE_NEW_TASK: "No new order",
            TASK_EMPTY_MESSAGE_URGENT_TASK: "Drag urgent order here",
            TASK_EMPTY_MESSAGE_PEND_TASK: "Drag order to do here",
            TASK_STATUS_NEW: "New order",
            TASK_STATUS_DISTRIBUTED: "Assigned",
            TASK_STATUS_PROCESSING: "Processing",
            TASK_STATUS_PAUSED: "Suspend",
            TASK_STATUS_COMPLETED: "Complete",
            SAVE: "Save",
            CANCEL: "Cancel",
            ASSIGN_ORDER: "Assign order",
            WORK_ORDER_TITLE: "Work order title",
            STATUS: "Status",
            DEADLINE: "Deadline",
            CREATE_DATE: "Create date",
            WORK_ORDER_NAME: "Work order name",
            ALL_ORDER: "All order",
            EXECUTOR: "Executor"
        },
        efficiency: {
            TOTAL_TASK_EFFICIENCY_STATISTICS: "Efficiency statistic",
            END_TIME: "Deadline:",
            GATHER_ALL: "Summary",
            TOTAL_QUANTITY_OF_TASK_1: "Total task:",
            DELAY_QUANTITY_OF_TASK_1: "Delayed:",
            DELAY_RATE_1: "Delay rate:",
            PROJECT_TOTAL: "Summary",
            PROJECT_NAME: "Project name",
            TOTAL_QUANTITY_OF_TASK_2: "Total task",
            UNCOMPLETED_QUANTITY_OF_TASK: "Delayed tasks amount",
            COMPLETION_RATE: "Completed",
            DELAY_QUANTITY_OF_TASK_2: "Delayed tasks amount",
            DELAY_RATE_2: "Delay rate",
            MORE: "More",
            TASK_DIAGRAM: "Rank",
            WITHOUT_DELAY: "Not delayed:",
            DELAY: "Delay:",
            LOADING: "Loading",
            THIS_MONTH: "This month",
            TOTAL: "Total",
            LAST_MONTH: "Last month",
            HIDE: "Hide",
            VIEW: "View"
        },
        team: {
            WORKFLOW_FILTER: "Work order filter",
            WORKFLOW: "Work order:",
            DEPARTMENT_STAFF: "Team view",
            DELETE: "Delete",
            STAFF_ASSIGNMENT: "Assign staff",
            CANCEL: "Cancel",
            SAVE: "Save",
            TIP1: "Can not delete the last admin",
            TIP2: "No staff can be assigned"
        },
        urgencyLevel: {
            URGENCY_LEVEL: "Urgency level",
            0: "General",
            1: "Serious",
            2: "Urgent",
            URGENCY_LEVEL_REQUIRED: "Urgency level is required"
        },
        insert: {
            SELECT_PROJECT: "Select Project",
            EXECUTOR: "Executor",
            LEVEL: "Level",
            CONFIRM: "Confirm",
            DEADLINE_REQUIRED: "Deadline is required",
            TITLE_REQUIRED: "Title is required"
        },
        set: {
            EMAIL_NOTIFICATION_OPTION: "E-mail notification option",
            TASK_COMMENTED_UPON: "Receive comment from work order",
            TASK_ABOUT_EXPIRE: "Order deadline is due",
            ASSIGNMENT_COMPLETE: "Assign order finish",
            ASSIGNMENT_STARTS: "Assign order start",
            TASK_SUSPENDED: 'Assign order suspend',
            ASSIGNMENT_REVIEWED: 'Receive comment from assign order',
            SELECT_LEAST_ONE: 'Please select at least one option',
            CONFIRM: 'Confirm'
        },
        common: {
            NEW: "New order",
            DEALING: "Processing",
            PAUSED: "Suspend",
            FINISHED: "Complete",
            CANCEL: "Cancel",
            CONFIRM: 'Confirm',
            PROMPT: 'Information',
            DELETE_IT: 'Are you sure you want to delete',
            NUMBER: 'No.',
            DEADLINE: 'Deadline'
        }
    },
    diagnosis: {
        OVERVIEW: 'Overview',
        DIAGNOSIS_LOG: 'Diagnosis logs',
        LOG_MORE: 'More...',
        LOG_NO_MORE: 'No more data !',
        config:{
            TITLE: 'Config',
            CONFIRM: 'Confirm',
            CANCEL: 'Cancel',
            NORMAL: 'Normal Level',
            ALERT: 'Alert Level',
            WARNING: 'Warning Level',
            RULE_SET: 'Alarm rule config',
            AUTO_PUSH_WO: 'Auto push WO',
            DIAGNOSIS_PAUSE_SET: 'Diagnosis pause config',
            SET: 'Config',
            ACTIVE: 'Active',
            DIAGNOSIS_SHOW:'Show diagnosis Per hour',
            CHOOSE_DIAGNOSIS_SHOW: 'Choose Show diagnosis Per hour',
            defaultPeriod:{
                REAL_TIME: 'Real time',
                DELAY_1H: 'Delay 1 hour',
                DELAY_12H: 'Delay 12 hours',
                DELAY_24H: 'Delay 24 hours',
                DELAY_7D: 'Delay 7 days',
                DELAY_1M: 'Delay 1 month',
                DELAY_FOREVER: 'Delay forever'
            },
            subConfig: {
                CREATE_CASE: 'Create case',
                CASE_NAME: 'Case name',
                CHOOSE_BUILD: 'Choose building',
                CHOOSE_AREA: 'Choose area',
                CHOOSE_EQUIPMENT_TYPE: 'Choose equipment type',
                CHOOSE_STOP_TIME: 'Choose pause time',
                CHOOSE_DISTRIBUTE_PERSON: 'Choose distribute person',
                ALARM_LEVEL: 'Alarm level',
                PROJECT: 'Project',
                USER:'Person',
                NORMAL: 'Normal',
                ALERT: 'Alert',
                WARNING: 'Warning',
                UPDATE_FAIL: 'Save fail',
                MUST_CHOOSE_EQUIP: 'Please choose a Equipment',
                MUST_FILL_IN: 'Please Fill in requirement info'
            },
            CHANGE_LEVEL: 'Change Level',
            CHANGE_ALARM_TIME: 'Change alarm time',
            LEVEL_SET : {
                NORMAL: 'Normal',
                CRITICAL: 'Critical',
                URGENT: 'Urgent'
            }
        }
    },

    analysis: {
        TITLE: "Analysis",
        PANE_POINTS_ALL_TITLE: "All point(click to select)",
        PANE_POINTS_SELECTED_TITLE: "Selected point (click to delete)",
        MARK_SELECTED: "Selected",
        PANE_ADD_NOTE: 'New Note',
        PANE_CONFIG: 'Config',
        PANE_FULL_SCREEN: 'Full Screen',
        modalType: {
            TENDENCY: "Tendency",
            STACK: "Area",
            SPECTRUM: "Spectrum",
            SCATTER: "Scatter",
            HISTORY_COMPARE: "History Bar",
            HISTORY_COMPARE_LINE: "History Line",
            ENERGY: "Energy",
            CLUSTER: "Classification",
            PIE_REAL_TIME: "Real-time Pie",
            CLUSTER_AHU:"Diag.AHU",
            CLUSTER_CHILLER: "Diag.Chiller"
        },
        paneConfig: {
            TITLE: "Configure data source",
            DATA_CONFIG_TITLE: "Data Point（the upper limit is 5 for each）",
            DATA_DRAG_TIP: "Please drag data here",
            LABEL_INVERAL: "Time interval",
            LABEL_TIME_START: "Start",
            LABEL_TIME_END: "End",
            ALIGN_MODE: "Completion method",
            ALIGN_FORWARD: "Complete forward",
            ALIGN_BACKWARD: "Complete backward",
            ALIGN_LINEAR: "linear interpolation",
            START_ANALYSIS: "Analyze now",
            FUNCTION: "Function",
            DATA_DEAL: "Data process",
            DATA_DIVIDE: "Data classification",
            TREND_ANALYSE: "Trend analysis",
            FREQ_ANALYSE: "Spectrum analysis",
            YEAR: "Year",
            MONTH: "Month",
            DAY: "Day",
            HOUR: "Hour",
            MINUTE: "Minute",
            SECOND: "Second",
            RECFG_SRC_DATA: "re-configure data",
            SEL_PT_NAME: "Selected point",
            TREND_DISTRIBUTE: "Trend of distribution",
            TYPE_POINT: "Classification of scatter",
            TYPICAL_CONDITION: "Typical working condition",
            DIAGNOSES_RESULT: "Diagnostic result",
            DATE: "Date",
            POINT_NUM: "Amount of points",
            MISS_NUM: "Loss amount",
            MISS_RATE: "Loss rate",
            ARGUMENTS: "Parameter",
            NAME: "Name",
            DESC: "Description",
            MAX: "Maximum",
            MIN: "Minimum",
            MED: "Median",
            AVG: "Average",
            STD: "Standard",
            RANGE_TO:"To",
            MODE_FIXED: "Fixed period",
            MODE_RECENT: "Recent period",
            MODE_CURRENT: "Predefined period",
            MODE_ACTUAL_TIME: "Real Time",
            INTERVAL_MIN1: "1 min",
            INTERVAL_MIN5: "5 min",
            INTERVAL_HOUR1: "1 hour",
            INTERVAL_DAY1: "1 day",
            INTERVAL_MON1: "1 month",
            TIME_RANGE_SEC: "second",
            TIME_RANGE_MIN: "minute",
            TIME_RANGE_HOUR: "hour",
            TIME_RANGE_DAY: "day",
            TIME_RANGE_MON: "month",
            DATA_TYPE_DEFAULT:"Data Points",
            ERR1: "Request data failed!",
            ERR2: "Already exist in the list!",
            ERR3: "Have not selected any point!",
            ERR4: "Fail to request data!",
            ERR5: "no data in specified period, please choose again!",
            ERR6: "No history point :",
            ERR7: "Automatically removed!",
            ERR8: "Time format error: Start Time is later than Closing Time!",
            ERR9: "Time format error: Closing Time is later than current time!",
            ERR10: "Repeated point: The point you drag here exists!",
            ERR11: "Data Error:There is no data during this period!",
            ERR12:"Too many data points，you can't drag more！"
        },
        paneMenu: {},
        workspace: {
            PROMPT_WORKSPACE_NAME: 'Enter the name of workspace',
            PROMPT_WORKSPACE_RENAME: 'Enter the new name of workspace',
            CONFIRM_WORKSPACE_DELETE: 'Delete this workspace?',
            CONFIRM_PAGE_DELETE: 'Delete this chart?',
            CONFIRM_NOTE_DELETE: 'Delete this note?',
            WORKSPACE_NAME: 'Workspace',
            BTN_WORKSPACE_NEW: 'Create',
            BTN_WORKSPACE_DELETE: 'Delete',
            BTN_WORKSPACE_RENAME: 'Rename',
            BTN_WORKSPACE_VIEWALL: 'Config',
            BTN_PAGE_NEW: 'Create',
            BTN_PAGE_UP: 'Shift Up',
            BTN_PAGE_DOWN: 'Shift Down',
            INPUT_PLACEHOLDER_PAGE_NAME: 'Enter the name'
        }
    },
    modalConfig:{
        TITLE: 'Configure',
        option:{
            LABEL_MODE:"Mode",
            MODE_FIXED: "Fixed period",
            MODE_RECENT: "Recent period",
            MODE_CURRENT: "Fast Config",
            MODE_REAL_TIME: "Real Time",
            MODE_COMPARISON:"Year-On-Year Comparison",
            MODE_COMPARE_EASY:"Easy Config",
            MODE_COMPARE_SENSOR:"Sensor Data",
            MODE_COMPARE_METER:"Meter Data",
            MODE_GAUGE:"Gauge",
            MODE_WEATHER:"Weather",
            LABEL_INTERVAL:"Interval",
            INTERVAL_MIN1: "1 minute",
            INTERVAL_MIN5: "5 minutes",
            INTERVAL_HOUR1: "1 hour",
            INTERVAL_DAY1: "1 day",
            INTERVAL_MON1: "1 month",
            LABEL_PERIOD:"Time Period",
            PERIOD_DROP_DOWN_TODAY:"Last 24 hours",
            PERIOD_DROP_DOWN_YESTERDAY:"Yesterday（24 hours）",
            PERIOD_DROP_DOWN_THREE_DAY:"Last 72 hours",
            PERIOD_DROP_DOWN_THIS_WEEK:"Last 7 days",
            PERIOD_DROP_DOWN_LAST_WEEK:"Last week（7 days）",
            PERIOD_DROP_DOWN_THIS_YEAR:"Last 12 months",
            PERIOD_UNIT_SEC: "Second",
            PERIOD_UNIT_MIN: "Minute",
            PERIOD_UNIT_HOUR: "Hour",
            PERIOD_UNIT_DAY: "Day",
            PERIOD_UNIT_MON: "Month",
            LABEL_TIME_RANGE:"Time Range",
            TIP_RANGE_TO:"To",
            LABEL_GAUGE_MODE:"Error mode",
            GAUGE_MODE_LOW:"Low value error",
            GAUGE_MODE_HIGH:"High value error",
            GAUGE_GREEN:"Green",
            GAUGE_NORMAL:"Normal",
            GAUGE_RED:"Attention",
            LABEL_REAL_TIME_INTERVAL:"Refresh Interval",
            REAL_TIME_INTERVAL_30_SEC:"30 seconds",
            REAL_TIME_INTERVAL_1_MIN:"1 minute",
            REAL_TIME_INTERVAL_5_MIN:"5 minutes",
            REAL_TIME_INTERVAL_10_MIN:"10 minutes",
            REAL_TIME_INTERVAL_30_MIN:"30 minutes",
            LABEL_WEATHER:"City Code",
            LABEL_COMPARE_PERIOD:"Comparison Period",
            LABEL_COMPARE_DATE1:"Date1",
            LABEL_COMPARE_DATE2:"Date2",
            COMPARE_PERIOD_HOUR:"1 hour",
            COMPARE_PERIOD_DAY:"1 day",
            COMPARE_PERIOD_WEEK:"1 week",
            COMPARE_PERIOD_MONTH:"1 month",
            COMPARE_PERIOD_YEAR:"1 year",
            LABEL_HISTORY_RANGE:"Time Range",
            HISTORY_RANGE_HOUR:"1 hour",
            HISTORY_RANGE_DAY:"1 day",
            HISTORY_RANGE_WEEK:"1 week",
            HISTORY_RANGE_MONTH:"1 month",
            HISTORY_RANGE_YEAR:"1 year"
        },
        data:{
            DATA_CONFIG_TITLE_PRE:"Data Point:",
            //DATA_CONFIG_TITLE_TYPE1:"the upper limit is 5 for each ",
            DATA_TYPE_MAX_NUM: " (the upper limit is <%maxNum%>)",
            DEFAULT_NAME:"Data Point"
        },
        err:{
            TYPE1:"Too many data points，you can't drag more!",
            TYPE2:"Repeated point: The point you drag here exists!",
            TYPE3:"Time format error: Start Time is later than Closing Time!",
            TYPE4:"Time format error: Closing Time is later than current time!",
            TYPE5: "Gauge parameters error：parameters are not sorted from small to big!",
            TYPE6: "No data history!",
            TYPE7: "The database hasn't got the time!",
            TYPE8: "Time format can't be recognized!",
            TYPE9: "Time period value is too long for current time period unit!",
            TYPE10: "Some parameters are not numbers ,please check!"
        },
        btnStartConfig:{
            TYPE1:"Start Analysis",
            TYPE2:"Confirm"
        }
    },
    core: {
        beopMap: {
            LOADED_SUCCESSFUL: 'Loaded_successful',
            LOADED_FAILED: 'Loaded_failed',
            AMAP: 'Amap',
            MAP: 'Map'
        },
        BROWSER_NOT_SUPPORT: 'Browser not support'
    },

    dashboard: {
        carbonFootprint: {
            TITLE: 'Emission of carbon footprint:',
            ENERGY_SAVING: 'Energy-saving rate',
            STANDARD_COAL_SAVING: 'Cumulative saving energy (ton of standard coal equivalent)',
            CO2_SAVING: 'Cumulative saving of CO2 emission'
        },
        modalHistoryChart: {
            MAXIMUM: 'Maximum',
            MINIMUM: 'Minimum',
            EnergyConsumption: 'Energy consumption'
        },
        modalConfig:{
            POINT_DRAG_TIP: "Please drag points here……",
            ERR: "Too many points,fail to add more"
        },
        resize: {
            ERR1: "Input value is bigger than the max value of target,please input again!",
            ERR2: "Input value is smaller than the minimum value of target,please input again!",
            ERR3: "Input value must be number only,please check the format!"
        },
        show: {
            TITLE_TIP:"Please input the title."
        }
    },

    dataSource: {
        MONTH: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'July', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], //缺
        WEEK: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], //缺
        TITLE: 'Data source',
        DS_CONFIG: 'Data configuration',
        PROJECT_NAME: 'Project Name',
        PROJECT_SEARCH: 'Search',
        NUMBER: 'No.',
        POINT_NAME: 'Point name',
        POINT_DESC: 'Notes',
        SURE: 'Confirm',
        CANCEL: 'Cancel',
        PARAM: 'Parameter',
        USER_NAME: 'Account',
        CUSTOM_NAME: 'Customize name',
        CUSTOM_REPEAT: 'Duplicate customized name',
        CUSTOM_NOT_NULL: 'Customized name is required',
        FILTER_REPEAT_ITEM: 'Filter duplicates',
        FORMULA_TIPS: 'Please enter the formula ( according to parameter list ):',
        FORMULA_NAME: 'Formula Name',
        FORMULA_VARIABLE_NAME: 'Variable',
        FORMULA_VARIABLE_VALUE: 'Point name',
        REMOVE_CONFIRM: 'Ensure remove ?',
        REMOVE_CONFIRM_TIPS: 'It is effect relative illustration when delete point, ensure remove ?',
        REMOVE_RESULT: 'deleted.',
        WORKSPACE: 'Workspace',
        TIME_YESTERDAY: 'Yesterday',
        TIME_TODAY: 'Today',
        NO_MATCH_FOUND: 'No matches found',
        NO_SELECT_POINT: 'Please select points !',
        GROUP_SELECTED: 'Selected',
        NO_SELECT_GROUP: 'Please select group !',
        INPUT_GROUP_NAME: 'Please input group name !',
        ADD_GROUP: '+ Add group'
    },
    code: {
        '1000': 'Request real-time data failed', //以1开头为错误信息代码
        '2000': '' //以2开头为正常信息代码
    },
    toolBox: {
        TITLE: 'Optional Modal',
        modal: {
            HIS_CHART: 'History Chart',
            HIS_CHART_ENERGY_LINE: 'Bar of History of Energy breakdown',
            HIS_CHART_ENERGY_BAR: 'Bar of History of Energy breakdown',
            HIS_CHART_YEAR_LINE: 'Line of History Chart year-on-year',
            HIS_CHART_YEAR_BAR: 'Bar of History Chart year-on-year',
            REAL_TIME_CHART: 'Real time Chart',
            REAL_TIME_CHART_PIE_ENERGY: 'Pie of Energy breakdown',
            REAL_TIME_CHART_PIE_DATAROOM: 'Pie of Data room Energy breakdown',
            REAL_TIME_CHART_LINE_OUTDOOR: 'Outdoor temperature trend',
            REAL_TIME_CHART_LINE_PUE: 'PUE trend',
            REAL_TIME_CHART_GAUGE: 'Dash board',
            REAL_TIME_CHART_BAR_ENERGY: 'Bar chart of Energy breakdown',
            REAL_TIME_CHART_LINE_ENERGY: 'Line chart of Energy breakdown',
            REAL_TIME_CARBON_FOOTPRINT: 'Carbon of Footprint',
            REAL_TIME_WEATHER: 'Weather trend',
            REAL_TIME_ENERGY_SAVE_RATE: 'Energy save rate',
            REAL_TIME_COAL_SAVE_TOTAL: 'Coal save total',
            REAL_TIME_CO2_SAVE_TOTAL: 'CO₂ save total',
            REAL_TIME_KPI_CHART: 'KPI chart',
            TRANSIT: 'Data Analysis'
        }
    }
};