var i18n_resource = {
    error: {
        token: {
            0: '身份凭证有效',
            1: '未登录',
            2: '身份凭证无效',
            3: '身份凭证过期',
            4: '无效的用户'
        },
        relogin: '请重新登录',
        noPermission: '您没有权限访问。'
    },
    admin: {
        navTitle: {
            ROOM: '房间',
            CONTROLLERS: '控制器列表',
            HISTORY_CURVE: '历史曲线',
            PATTERN: '模式',
            SETPWD: '设置密码',
            SHOW_SENSOR: '显示传感器',
            HIDE_SENSOR: '隐藏传感器',
            INFO: '消息',
            SCHEDULE: '日程',
            LAST_VERSION: '最新版本  '
        },
        index: {
            INTER_NAME: '填写用户名',
            INTEE_PASSWORD: '输入密码',
            REGISTER: '注册',
            LOGIN: '登录',
            LANGUAGE:'语言',
            FORGET_PASS: '忘记密码',
            NAME_ERROR: '用户名或密码错误！',
            LOGIN_ERROR_INFO: '登录失败，没有任何项目的权限！',
            LOGIN_ERROR: '登录失败！',
            CONTRY_TITTLE: '国家地区',
            CONTRY: '中国',
            YOUR_NUM: '你的手机号',
            NEXT: '下一步',
            AGREE: '我已阅读并同意',
            TOU: '使用条款和隐私政策',
            ENTER: '请输入',
            VERI_CODE: '的短信收到的验证码:',
            SMS_CODE: '短信校验码',
            SET_PASS: '请设置密码:',
            MAN: '男',
            WOMEN: '女',
            PASS_INFO: '密码由6-20位字符组成',
            OVER: '完成',
            REPEAT_SEND: '重新发送',
            NUM_INFO: '请填写手机号码！',
            NUM_ERROR_INFO: '手机号码为11位数字！请正确填写！',
            NUM_REPEAT_INTER: '您的手机号码不正确，请重新输入！',
            NUM_ELEVEN: '请填写完整！',
            PASS_INFO: '请至少设置6位密码！',
            USER_INFO: '用户名或密码错误！',
            USER_PASSWORD_INFO: '用户密码错误!',
            ROOM_PASSWORD_INFO: '房间密码错误!',
            VERI_INFO: '验证码错误，请重新输入！',
            REGISTER_INFO: '手机号码已经注册，请登录！',
            CHECH_INFO: '网络未连接，请检查',
            CHECH_INFO_ONE: '网络连接不可能，部分功能可能受影响',
            CHECH_INFO_TWO: '网络已连接',
            MECINE_INFO: '服务器繁忙',
            SERVICE_ONE: '1、服务条款的确认和接纳本网站及APP的各项内容和服务的所有权归本公司拥有。',
            SERVICE_ONE_ONE: '用户在接受本服务之前，请务必仔细阅读本条款。',
            SERVICE_ONE_TWO: '用户使用服务，或通过完成注册程序，表示用户接受所有服务条款。',
            SERVICE_TWO: '2、用户同意：',
            SERVICE_TWO_ONE: '(1) 提供及时、详尽及准确的个人资料。',
            SERVICE_TWO_TWO: '(2) 不断更新注册资料、符合及时、详尽、准确的要求。',
            SERVICE_TWO_THREE: '如果用户提供的资料不准确，本网站有结束服务的权利。',
            SERVICE_TWO_FOUR: '本网站及APP将不公开用户的姓名、地址、电子邮箱、帐号和电话号码等信息（请阅隐私保护条款）。',
            SERVICE_TWO_SIX: '用户在本网站和APP的任何行为必须遵循：',
            SERVICE_TWO_SEVEN: '(1) 传输资料时必须符合中国有关法规。',
            SERVICE_TWO_EIGHT: '(2) 使用信息服务不作非法用途和不道德行为。',
            SERVICE_TWO_NIEN: '(3) 不干扰或混乱网络服务。',
            SERVICE_TWO_TEN: '(4) 遵守所有使用服务的网络协议、规定、程序和惯例。用户的行为准则是以因特网法规，政策、程序和惯例为根据的。',
            SERVICE_THREE: '3、服务条款的修改',
            SERVICE_THREE_ONE: '本网站及APP有权在必要时修改条款，将会在页面公布。',
            SERVICE_THREE_TWO: '如果不接受所改动的内容，用户可以主动取消自己的会员资格。如果您不取消自己的会员资格，则视为接受服务条款的变动。',
            SERVICE_FOUR: '4、 用户的帐号、密码和安全性',
            SERVICE_FOUR_ONE: '一旦成功注册成为会员，您将有一个密码和用户名。',
            SERVICE_FOUR_TWO: '用户将对用户名和密码的安全负全部责任。另外，每个用户都要对以其用户名进行的所有活动和事件负全责。您可以随时改变您的密码。',
            SERVICE_FOUR_THREE: '用户若发现任何非法使用用户帐号或存在安全漏洞的情况，请立即通告本公司。',
            SERVICE_FIVE: '5、拒绝提供担保',
            SERVICE_FIVE_ONE: '用户明确同意使用本公司服务，由用户个人承担风险。',
            SERVICE_FIVE_TWO: '本网站及APP不担保服务一定满足用户的要求，也不担保服务不会中断，对服务的及时性、安全性、出错发生都不作担保。',
            SERVICE_FIVE_THREE: '用户理解并接受：任何通过服务取得的信息资料的可靠性有用性取决于用户自己的判断，用户自己承担所有风险和责任。',
            SERVICE_SIX: '6、有限责任',
            SERVICE_SIX_ONE: '本网站及APP对任何由于使用服务引发的直接、间接、偶然及继起的损害不负责任。',
            SERVICE_SIX_TWO: '这些损害可能来自（包括但不限于）：不正当使用服务，或传送的信息不符合规定等。',
            SERVICE_SEVEN: '7、对用户信息的存储和限制',
            SERVICE_SEVEN_ONE: '本网站及APP不对用户发布信息的删除或储存失败负责，本公司有判定用户的行为是否符合服务条款的要求和精神的保留权利。如果用户违背了服务条款的规定，有中断对其提供服务的权利。',
            SERVICE_EIGHT: '8、结束服务',
            SERVICE_EIGHT_ONE: '本网站及APP可随时根据实际情况中断一项或多项服务，不需对任何个人或第三方负责或知会。',
            SERVICE_EIGHT_TWO: '同时用户若反对任何服务条款的建议或对后来的条款修改有异议，或对服务不满，用户可以行使如下权利：',
            SERVICE_EIGHT_THREE: '(1) 不再使用本公司的服务。',
            SERVICE_EIGHT_FOUR: '(2) 通知本公司停止对该用户的服务。',
            SERVICE_NINE: '9、信息内容的所有权',
            SERVICE_NINE_ONE: '本公司的信息内容包括：文字、软件、声音、相片、录象、图表；以及其它信息，所有这些内容受版权、商标、标签和其它财产所有权法律的保护。',
            SERVICE_NINE_TWO: '用户只能在授权下才能使用这些内容，而不能擅自复制、再造这些内容、或创造与内容有关的派生产品。',
            SERVICE_TEN: '10、隐私保护条款',
            SERVICE_TEN_ONE: '本网站及APP将严格保守用户的个人隐私，承诺未经过您的同意不将您的个人信息任意披露。',
            SERVICE_TEN_TWO: '但在以下情形下，我们将无法再提供您前述保证而披露您的相关信息。这些情形包括但不限于：',
            SERVICE_TEN_THREE: '* 为了您的交易顺利完成，我们不得不把您的某些信息，如您的姓名、联系电话、e-mail等提供给相关如物流服务方，以便于他们及时与您取得联系，提供服务。',
            SERVICE_TEN_FOUR: '* 当您在本网站的行为违反的服务条款，或可能损害他人权益或导致他人遭受损害，只要我们相信披露您的个人资料是为了辨识、联络或采取法律行动所必要的行动时。',
            SERVICE_TEN_FIVE: '* 法律法规所规定的必须披露或公开的个人信息。',
            SERVICE_TEN_SIX: '* 当司法机关或其它有权机关依法执行公务，要求提供特定个人资料时，我们必须给予必要的配合。',
            SERVICE_ELEVEN: '11、适用法律',
            SERVICE_ELEVEN_ONE: '上述条款将适用中华人民共和国的法律，所有的争端将诉诸于本网所在地的人民法院。',
            SERVICE_ELEVEN_TWO: '如发生服务条款与中华人民共和国法律相抵触时，则这些条款将完全按法律规定重新解释，而其它条款则依旧保持约束力。'
        },
        indexMap: {
            EQUIPMENT: '设备',
            HUMIDITY: '湿度',
            PAIR: '配对',
            HISTORY: '历史',
            WIND_SPEED_SETTIG: '风速设定',
            CORRECT_ROOM_INFO: '请先关联房间',
            LAST_REFRESH: '最后刷新：',
            OPEN_CLOSE_INFO: '只有手动模式才可以操作启停',
            SET_SPEED_INFO: '只有手动模式才可以设置风速',
            CURRENT_MODE: '当前为节能模式',
            SET_TEMPERATURE: '确认设定温度?',
            SET_WIND_SPEED: '确认设定风速?',
            HANDOL_INFO: '操作失败',
            LADY_FIRST: '当前是女生优先模式,只有女生才可以设置温度哦',
            SEX_INFO_REQUIRE: '当前是女生优先模式,请到个人中心完善个人信息'
        },
        roomPage: {
            EDIT: '编辑',
            ADD: '添加',
            SWEEP: '扫一扫',
            INVITE_CODE: '邀请码',
            MY_QR_CODE: '我的二维码',
            DIRECT_ACCESS:'直联进入',
            GENERATE_QR_CODE: '生成二维码',
            MAP: '地图',
            LIST: '列表',
            INTER_INVITE_CODE: '输入邀请码',
            BACK: '返回',
            SURE: '确定',
            CANCEL: '取消',
            NO_ROOM_TIP:'尚未关联任何房间，请点击添加按钮关联。',
            SELECT_ROOM: '请选择房间',
            CORRECT_ASSOCIATION: '关联成功',
            ASSOCIATED_FAILURE: '关联失败',
            INVALID: '失效',
            DELETE: '删除',
            INVITE_CODE: '邀请码',
            COPY_INVITE_CODE: '复制邀请码'
        },
        setUp: {
            SCHEDULE_TABLE: '日程',
            INFOS: '消息',
            LOGOUT: '注销',
            LANGUAGE: '语言',
            CHINESE: '中文',
            INSTALL: '设置',
            CONFIG: '选项',
            VERSION: '版本号',
            PERSONAL_CENTER: '个人中心',
            YOUR_PASSWORD: '您的账户密码',
            SET_ROOM_PASSWORD: '设置房间管理密码',
            ROOM_PASSWORD: '房间管理密码',
            HOSTNAME: 'Hostname',
            IP: 'IP',
            DOWNLOAD_ROOM: '下载房间',
            SWITCH_TO_LOCAL: '切换到本地版'
        },
        controllers: {
            NAME: '名称',
            TEMPERATURE: '温度',
            WIND_SPEED: '风速',
            OPEN_CLOSE: '启停',
            SEANSONAL_PATTERN: '季节模式',
            VALVE: '阀位',
            AUTO: '自动',
            CLOSE: '停',
            OPEN: '开',
            REFRIGERATION: '制冷',
            HEATING: '制热',
            HANDLE: '手动',
            SELECT_ONE: '请至少选择一项！',
            SET_WIND_SPEED: '-风速设定(数字量)',
            SELECTED_ALL: '批量'
        },
        pattern: {
            MS_PRIORITY_MODE: '女士优先模式',
            ENERGY_SAVING_MODE: '节能模式',
            COMFORTABLE_MODE: '舒适模式',
            MANUAL_MODE: '手动模式',
            SEASON_MODE_COOLING: '季节模式 : 制冷',
            SEASON_MODE_HEATING: '季节模式 : 制热',
            CONFIRM_SWITCH: '确认切换为',
            SWITCHED: '已切换为',
            SWITCHED_ERROR:'切换模式失败'
        },
        schedule: {
            MS_FIRST: '女士优先',
            ENERGY_CONSERVE: '节能',
            COMFORTABLE: '舒适',
            HANDLE: '手动',
            SELECT_TIME: '请选择时间',
            SAVE: '保存',
            REPEAT: '重复',
            SEVEN: '日',
            ONE:'一',
            TWO: '二',
            THREE: '三',
            FOUR: '四',
            FIVE: '五',
            SIX: '六',
            SUNDAY: '周日',
            MONDAY: '周一',
            TUESDAY: '周二',
            WEDNESDAY: '周三',
            THURSDAY: '周四',
            FRIDAY: '周五',
            SATURDAY:'周六',
            EXIST_SCHEDULE: '已存在相同时间的日程'
        },
        personalCenter: {
            AVATAR: '头像',
            SEX: '性别',
            PHONE_NUM: '手机',
            EMAIL: '邮箱',
            EDIT: '编辑',
            FINISH: '完成',
            EMAIL_FORMAT_ERROR: '邮箱格式不正确',
            EMAIL_SEND_SUCCESS: '邮件发送成功,请到邮箱查收',
            EMAIL_SEND_FAIL: '邮件发送失败,请再试一次',
            EMAIL_CHANGED_SUCCESS: '邮箱修改成功',
            SEX_CHANGED_SUCCESS: '性别修改成功',
            SEX_CHANGED_FAILED: '性别修改失败'
        },
        avatar: {
            MY_AVATAR: '我的头像',
            TAKE_PHOTO:'拍照',
            FROM_ALBUM:'从手机相册选择',
            SAVE_PHOTO: '保存图片',
            CANCEL: '取消',
            FAIL_CHANGE: '头像未更换成功'
        },
        phoneNumber:{
            TITLE: '绑定手机号',
            INPUT_VALID_PHONE_NUM: '手机号码格式不正确,请检查一下格式',
            PHONE_NUM_IS_SAME: '输入的手机号码和原来的一样',
            BIND_PHONE_SUCCESS: '绑定手机成功',
            SMS_CODE_ERROR: '短信验证码不正确',
            SEND_SMS_CODE_FAIL: '发送验证码失败',
            PHONE_NUM_EXIST: '手机号码已经存在'
        }
    },
    iot: {
        IOT: '设备',
        PARAMS_CONFIG: '参数配置',
        //QUERY_KEYWORD:'搜索关键字...',
        TREE_ALL:'全部',
        TREE_HIDE:'隐藏',
        ADD_THING:'添加Thing',
        ADD_GROUP:'添加Group'
    },
    dataSource: {
        MONTH: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
        WEEK: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
        TITLE: '数据源',
        DS_CONFIG: '数据源配置',
        PROJECT_NAME: '项目名',
        PROJECT_SEARCH: '搜索',
        NUMBER: '编号',
        POINT_NAME: '点名',
        POINT_DESC: '注释',
        POINT_ATTR: '属性',
        SURE: '确认',
        CANCEL: '取消',
        PARAM: '参数',
        USER_NAME: '用户名',
        CUSTOM_NAME: '自定义名',
        FILTER_REPEAT_ITEM: '已过滤重复项',
        CUSTOM_REPEAT: '自定义名重复',
        CUSTOM_NOT_NULL: '自定义名不能为空',
        FORMULA_TIPS: '请输入公式（参数请按照参数列表中参数名输入）：',
        FORMULA_NAME: '公式名',
        FORMULA_VARIABLE_NAME: '变量名',
        FORMULA_VARIABLE_VALUE: '实际值',
        REMOVE_CONFIRM: '确认删除？',
        REMOVE_CONFIRM_TIPS: '已关联',
        REMOVE_RESULT: '已删除',
        WORKSPACE: '工作空间',
        TIME_YESTERDAY: '昨天',
        TIME_TODAY: '今天',
        NO_MATCH_FOUND: '未找到匹配结果',
        NO_SELECT_POINT: '请选择点！',
        GROUP_SELECTED: '已选',
        NO_SELECT_GROUP: '请选择组！',
        INPUT_GROUP_NAME: '请输入组名！',
        ADD_GROUP: '+ 添加分组',
        POINT_TYPE_CUSTOM: '自定义',
        POINT_TYPE_SYSTEM: '系统',
        POINT_TYPE_DEVICE: '设备',
        POINT_TYPE_TYPE: '类型',
        ERROR: '你的数据源已被删除，图表无法生成！',
        ICON_SYS_HVAC: '暖通',
        ICON_SYS_POWER: '动力',
        ICON_SYS_LIGHT: '照明插座',
        ICON_SYS_CRAC: '精密空调',
        ICON_DEV_CHIL: '冷机',
        ICON_DEV_PUMP: '水泵',
        ICON_DEV_COOL: '冷却塔',
        ICON_DEV_AHU: 'AHU',
        ICON_DEV_VAV: 'VAV',
        ICON_DEV_SYS: '系统',
        ICON_TYPE_TEMP: '温度',
        ICON_TYPE_FLOW: '流量',
        ICON_TYPE_FREQ: '频率',
        ICON_TYPE_ONOFF: '启停',
        ICON_TYPE_ELEPOW: '功率',
        ICON_TYPE_ELEPOWMET: '电量表',
        ICON_TYPE_THER: '冷量表',
        ICON_TYPE_PRES: '压力',
        ICON_TYPE_ALARM: '报警',
        ICON_TYPE_CURFLOW: '电流',
        NAV_MINE: '我的',
        NAV_CLOUD: '公共',
        ALREADY_EXIST: '添加已去除重复项',
        ADD_POINT_GROUP: '添加分组',
        ADD_POINT: '添加点',
        ADD_FORMULA: '添加公式',
        RENAME: '重命名',
        REMOVE: '删除',
        DELETE_GROUP_INFO: '确认删除数据源组?',
        SEARCH_KEYWORD: '搜索关键字...'
    }
};