var i18n_resource = {
    error: {
        token: {
            0: '身份凭证有效',
            1: '未登录',
            2: '身份凭证无效',
            3: '身份凭证过期',
            4: '无效的用户'
        },
        relogin: '请重新登录',
        noPermission: '您没有权限访问。'
    },
    energyManagement: {
        LABEL_FUNCTION:'功能',
        LABEL_STRUCTURE:'结构',
        overview: {
            ENERGY_MANAGEMENT: '能源管理',
            ENERGY_OVERVIEW: '能耗概览',
            TODAY_ENERGY: '今日能耗',
            MONTH_ENERGYS: '本月能耗',
            YEAR_ENERGY: '今年能耗',
            TODAY_ENERGY_NEW:'本日用电能耗 (费用仅供参考)',
            MONTH_ENERGY_NEW:'本月用电能耗 (费用仅供参考)',
            YEAR_ENERGY_NEW:'今年用电能耗 (费用仅供参考)',
            TODAY_WATER_NEW:'本日用水 (费用仅供参考)',
            MONTH_WATER_NEW:'本月用水 (费用仅供参考)',
            YEAR_WATER_NEW:'本年用水 (费用仅供参考)',
            TODAY_GAS_NEW:'本日用气 (费用仅供参考)',
            MONTH_GAS_NEW:'本月用气 (费用仅供参考)',
            YEAR_GAS_NEW:'本年用气 (费用仅供参考)',
            TODAY_OIL_NEW:'本日用油 (费用仅供参考)',
            MONTH_OIL_NEW:'本月用油 (费用仅供参考)',
            YEAR_OIL_NEW:'本年用油 (费用仅供参考)',
            TODAY_WATER_SUPPLY:'本日供水 (费用仅供参考)',
            MONTH_WATER_SUPPLY:'本月供水 (费用仅供参考)',
            YEAR_WATER_SUPPLY:'本年供水 (费用仅供参考)',
            TODAY_WATER_DRAINAGE:'本日排水 (费用仅供参考)',
            MONTH_WATER_DRAINAGE:'本月排水 (费用仅供参考)',
            YEAR_WATER_DRAINAGE:'本年排水 (费用仅供参考)',            
            ACCUMULATIVE_ENERGY: '累计能耗量',
            ACCUMULATIVE_COST:'累计电价',
            COMPARISON_YESTERDAY: '相比昨日',
            COMPARISON_LAST_YEAR: '相比去年',
            COMPARISON_LAST_MONTH:'相比上月',
            YOY: '同比',
            MOM: '环比',
            TOTAL_STATISTICS: "能耗统计",
            SUB_ENERGY: "能耗分项",
            SUB_ITEM_CONPARSION: "分项对比",
            HOURLY_ENERGY: '逐时用电',
            DAILY_ENERGY: '逐日用电',
            MONTH_ENERGY: '逐月用电',
            HOURLY_WATER: '逐时用水',
            DAILY_WATER: '逐日用水',
            MONTH_WATER: '逐月用水',
            HOURLY_GAS: '逐时用气',
            DAILY_GAS: '逐日用气',
            MONTH_GAS: '逐月用气',
            HOURLY_OIL: '逐时用油',
            DAILY_OIL: '逐日用油',
            MONTH_OIL: '逐月用油',
            HOURLY_WATER_SUPPLY: '逐时供水',
            DAILY_WATER_SUPPLY: '逐日供水',
            MONTHLY_WATER_SUPPLY: '逐月供水',    
            HOURLY_DRAINAGE: '逐时排水',
            DAILY_DRAINAGE: '逐日排水',
            MONTH_DRAINAGE: '逐月排水',                      
            QUERY: '查询',
            NO_POINT_ALERT:'由于缺少点导致部分图表无法显示！',
            MONTH:'月',
            DAY:'日',
            WEEK:'周',
            HOURLY_COST: '逐时费用',
            DAILY_COST: '逐日费用',
            MONTH_COST: '逐月费用',
            TO:'到',
            TIME_INTERVAL: "时间间隔",    
            TIME_RANGE: '时间范围',
            SELECT_START_TIME: '请选择开始时间',
            SELECT_CLOSING_TIME: '请选择结束时间',
            HOUR: '小时',
            TODAY: '今天',
            THIS_WEEK: '本周',
            THIS_MONTH: '本月',
            CONFIRM: '确认',
            MORE:'更多',
            YESTERDAY:'昨天',
            LAST_WEEK:'上周',
            LAST_MONTH:'上月',
            THIS_YEAR:'今年',
            LAST_YEAR:'去年',
            NO_DATA_TIP:'无数据',   
            CATEGORY:'类别'

        },
        history: {
            HISTROY_QUERY: '历史查询',
            CYCLE: "周期",
            THIS_YEAR: "本年",
            THIS_MONTH: "本月",
            THIS_DAY: "本日",
            ENERGY_CONSUMPTION: '能耗',
            WATER_CONSUMPTION:'用水量',
            GAS_CONSUMPTION:'用气量',
            OIL_CONSUMPTION:'用油量',
            FLOW_RATE:'流量',
            POWER: '功率',
            FIVE_MIMUTES:'5分',
            HOUR:'时',
            DAY:'日',
            MONTH:'月',
            ADD_YOY: '增加同比',
            YOY_QUERY: '同比查询',
            TOTAL:'总计:',

        },
        subTable: {
            METER_QUERY: '分表查询',
            PARAMETERS_ANALYSIS: '参数分析',
            METER_READING: '一键抄表',
            TOTAL_METER: '总电表',
            TODAY_ENERGY: '今日能耗',
            DAILY_ACC_ENERGY: '日累计量',
            MONTHLY_ACC_ENERGY: '月累计量',
            YEARLY_ACC_ENERGY: '年累计量',
            POWER_TRENDY: '昨今用电趋势',
            REAL_AMOUNT: '实际用量',
            METER_TABLE_TIME: '时间',
            SELECT_TIME: '请选择导出时间',
            EXPORT: '导出',
            CANCEL: '取消',
            STARTTIME: '开始时间',
            ENDTIME: '结束时间'
        },
        projectBenchmark: {
            PROJECT_STANDARD: '项目对标',
            WATER: "水",
            ELECTRICITY:"电",
            GAS:"煤",
            OIL:'油',
            TOTAL: "总计",
            COUNTRY: "中国",
            BUSSINESS_TYPE: "业务类型",
            CITY: "城市"         
        },
        energyAnalysis:{
            ENERGY_ANALYSIS:'能效分析'
        },
        reports: {
            REPORT: '能耗报表'
        },
        
        param_config:{
            PARAM_CONFIG:'参数配置',
            CONFIG_SUCCSS: '配置成功',
            CONFIG_FAILED: '配置失败'
        },
        md:{
            MD:"最大需量",
            TODAY_DEMAND:"今日需量",
            YESTERDAY_DEMAND:"昨日需量",
            DECLARATION:"申报额度",
            DAY_DEMAND:"日最大需量",
            MONTH_DEMAND:"月最大需量",
            NOW_MONTH_DEMAND:"本月需量",
            NOW_YEAR_DEMAND:"今年最大需量",
            LAST_YEAR_DEMAND:"去年最大需量",
            LAST_MONTH:'上月',
            THIS_MONTH:'当月',
            NEXT_MONTH:'下月',
            RATED_CAPACITY:'额定容量(KVA)',
            DECLARATION_KVA:'申报额度(KVA)',
            MONTH_DEMAND_KVA:"月最大需量(KVA)",
            MONTH_USING:'月最大使用率',
            REALITY_USING:'实时使用率',
            THIS_MONTH_USING:'本月实时使用量',
            YEAR_TREND:'年趋势分析',
            MONTH_TREND:'月趋势分析',
            DAILY_TREND:'日趋势分析',
            PARAMETER:'参数管理',
            PERIOD:'时间周期',
            WITHIN:'申报额度内',
            WITHOUT:'申报额度外',
            OVERVIWE:'概览',
            ANALYSIS:'分析',
            TITLE_ONE:'时序特征',
            TITLE_TWO:'关联性特征',
            TITLE_THREEE:'预测历史',
            TITLE_FOUR:'未来24小时预测',
            WEEKDAY:'工作日',
            WEEKEND:'周末',
            RANK:'排名',
            FACTOR:'因素',
            CONTRIBUTE:'权重',
            FORMART:'预测需量',
            REALITY:'实际需量',
            Declaration:'申报需量',
            SCHEME:'优化方案',
            SCHEME_PROPOSAL:'建议方案',
            REDUCTION:'预计降低需量',
            FORMART_TIP:'预测值',


        },
    },
    dataSource: {
        MONTH: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
        WEEK: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
        TITLE: '数据源',
        DS_CONFIG: '数据源配置',
        PROJECT_NAME: '项目名',
        PROJECT_SEARCH: '搜索',
        NUMBER: '编号',
        POINT_NAME: '点名',
        POINT_DESC: '注释',
        POINT_ATTR: '属性',
        SURE: '确认',
        CANCEL: '取消',
        PARAM: '参数',
        USER_NAME: '用户名',
        CUSTOM_NAME: '自定义名',
        FILTER_REPEAT_ITEM: '已过滤重复项',
        CUSTOM_REPEAT: '自定义名重复',
        CUSTOM_NOT_NULL: '自定义名不能为空',
        FORMULA_TIPS: '请输入公式（参数请按照参数列表中参数名输入）：',
        FORMULA_NAME: '公式名',
        FORMULA_VARIABLE_NAME: '变量名',
        FORMULA_VARIABLE_VALUE: '实际值',
        REMOVE_CONFIRM: '确认删除？',
        REMOVE_CONFIRM_TIPS: '已关联',
        REMOVE_RESULT: '已删除',
        WORKSPACE: '工作空间',
        TIME_YESTERDAY: '昨天',
        TIME_TODAY: '今天',
        NO_MATCH_FOUND: '未找到匹配结果',
        NO_SELECT_POINT: '请选择点！',
        GROUP_SELECTED: '已选',
        NO_SELECT_GROUP: '请选择组！',
        INPUT_GROUP_NAME: '请输入组名！',
        ADD_GROUP: '+ 添加分组',
        POINT_TYPE_CUSTOM: '自定义',
        POINT_TYPE_SYSTEM: '系统',
        POINT_TYPE_DEVICE: '设备',
        POINT_TYPE_TYPE: '类型',
        ERROR: '你的数据源已被删除，图表无法生成！',
        ICON_SYS_HVAC: '暖通',
        ICON_SYS_POWER: '动力',
        ICON_SYS_LIGHT: '照明插座',
        ICON_SYS_CRAC: '精密空调',
        ICON_DEV_CHIL: '冷机',
        ICON_DEV_PUMP: '水泵',
        ICON_DEV_COOL: '冷却塔',
        ICON_DEV_AHU: 'AHU',
        ICON_DEV_VAV: 'VAV',
        ICON_DEV_SYS: '系统',
        ICON_TYPE_TEMP: '温度',
        ICON_TYPE_FLOW: '流量',
        ICON_TYPE_FREQ: '频率',
        ICON_TYPE_ONOFF: '启停',
        ICON_TYPE_ELEPOW: '功率',
        ICON_TYPE_ELEPOWMET: '电量表',
        ICON_TYPE_THER: '冷量表',
        ICON_TYPE_PRES: '压力',
        ICON_TYPE_ALARM: '报警',
        ICON_TYPE_CURFLOW: '电流',
        NAV_MINE: '我的',
        NAV_CLOUD: '公共',
        ALREADY_EXIST: '添加已去除重复项',
        ADD_POINT_GROUP: '添加分组',
        ADD_POINT: '添加点',
        ADD_FORMULA: '添加公式',
        RENAME: '重命名',
        REMOVE: '删除',
        DELETE_GROUP_INFO: '确认删除数据源组?',
        SEARCH_KEYWORD: '搜索关键字...',
        TAG_ALL: '全部',
        TAG_EQUIPMENT: '设备',
        TAG_FLOOR: '楼层',
        TAG_ENERGY: '能耗'
    },
}