from beopWeb.mod_iot.model.thing.ThingHVAC import ThingHVAC

class Ch(ThingHVAC):
    """description of class"""

    config = {
        'attrs': {
            "ChAmpLmtSetPointFeedback":{},
            "ChAMPS":{},
            "ChChWTempSupplySetPoint":{},
            "ChChWTempSupplyActiveSetPoint":{},
            "ChLeaveEvapTemp":{},
            "ChEnterEvapTemp":{},
            "ChEnterCondTemp":{},
            "ChLeaveCondTemp":{},
            "ChEvapAppT":{},
            "ChCondAppT":{},
            "ChEvapSatuTemp":{},
            "ChCondSatuTemp":{},
            "ChWarningFaultCode":{},
            "ChCondPressure":{},
            "ChEvapPressure":{},
            "ChEvapTemp":{},
            "ChCondTemp":{},
            "ChGasExhaustTemp":{},
            "ChRunHour":{},
            "ChOILPD":{},
            "ChOILT":{},
            "ChGearT":{},
            "ChCoilT":{},
            "ChInletValvePosition":{},
            "ChPressureRiserPosition":{},
            "ChVoltage":{},
            "ChCurrent":{},
            "ChRunCode":{},
            "ChErr":{},
            "ChChWTempSupplySetPointEnable":{},
            "ChEnable":{},
            "ChAutoMode":{},
            "ChOnOff":{},
            "ChOnOffSet":{},
            "ChOnOffSetEnable":{},
            "ChPower":{},
            "ChElecUse":{},
            "ChPowerFactor":{},
            "ChLnVoltAB":{},
            "ChLnVolt":{},
            "ChLnVoltPercent":{},
            "ChLnCurrent":{},
            "ChLnCurrentL1":{},
            "ChOILFilterP":{},
            "ChGasExhaustSuperhrat":{},
            "ChMotorAmps":{},
            "ChMotorCurrent":{},
            "ChSpoolValvePosition":{},
            "ChOILTankPressure":{},
            "ChOILPumpPressure":{},
            "ChRemoteMode":{}
        }
    }